### ISSUE TITLE
Procedural Primitives not working

### ISSUE THREAD

**Issue by ItsAKaime** [pokepetter/ursina#10]
I was looking around at the prefabs and tried to test out the VideoRcorder, and noticed I was getting an error at the procedural primitive call "RedCube()".  Here's the error log:

`File "ursina_game.py", line 6, in <module>
    cube = primitives.RedCube()
  File "<string>", line 4, in __init__
  File "C:\Users\Kai\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ursina\entity.py", line 80, in __init__
    if len(_stack)>2 and 'super().__init__()' in _stack[1].code_context[0]:
TypeError: 'NoneType' object is not subscriptable`

**Comment by pokepetter** [comment]
It seems there was a problem with a newly added debug feature and the classes generated by ursina/prefabs/primitives.py. Fixed by checking if code_context exists.
