### ISSUE TITLE
Cannot import lit_with_shadows shader

### ISSUE THREAD

**Issue by Toulonnais72** [pokepetter/ursina#105]
Hi all,

I am trying to implement the lit_with_shadows_shader from ursina.shaders but I get an error message:
"ImportError: cannot import name 'lit_with_shadows_shader' from 'ursina.shaders' (C:\Users\Starfleet\AppData\Roaming\Python\Python37\site-packages\ursina\shaders\__init__.py)
"

Any suggestion ?

Thanks a lot
Christophe

**Comment by DiamondsBattle** [comment]
Hey, you should try updating your ursina version (`pip install ursina --upgrade`). Also, the directory is invalid (should be `shaders\__init__.py`, not `shaders__init.py__`).

**Comment by Toulonnais72** [comment]
Thank you ! It worked.
