### ISSUE TITLE
Interacting with mesh generated cubes

### ISSUE THREAD

**Issue by PawelMP** [pokepetter/ursina#111]
Hey, I am trying to make a simple mesh generated cubes based on a heightmap. It works like a charm, everything loads very quickly but when I am in FirstPersonController I fall through the mesh generated cubes - I don't know how to make them work like cubes in your minecraft-clone example. I am missing something but I don't know what. Here is my code :

`cube = load_model('cube')

class MeshVoxel(Button):
    def __init__(self, texture = grass_texture,position = (0,0,0)):
        super().__init__(
            parent = scene,
            collider = cube,
            texture = texture,
            model=Mesh(),
            #position = position,
            color = color.color(0, 0, random.uniform(0.9, 1.0)),
        )

grass = MeshVoxel()
grassModel = grass.model

...

texture = load_texture('heightmap_1.jpg')

for y in range(texture.height):
    for x in range(texture.width):
        col = texture.get_pixel(x,y)
        #print(col)
        if col.v > .45: #
            grassModel.vertices.extend([Vec3(x, 0, y)+ v for v in cube.vertices])

grassModel.uvs = (cube.uvs) * (texture.width * texture.height)
grassModel.generate() 
`

**Comment by pokepetter** [comment]
Sounds like you need to place colliders. You can see the colliders if you press F10 a few times.
