### ISSUE TITLE
 [Improvements]  Some better import logic implementation to work better with most IDE's auto-completion?

### ISSUE THREAD

**Issue by SuperMarioSF** [pokepetter/ursina#119]
Hello. I've found this library very powerful and useful. But when I using this with my development environment, my IDE reported many errors about the demo code. 

Demo code works just fine, so I attempt to add type hints to bypass the issue, this also enables auto-completion feature.

For example, usually we want to add type hints on variable to enforce IDE to use specified type to do auto-complete works. Like this:
```python
from ursina import *
from ursina.window import Window  # Importing original class for window object

window: Window  # Type hints here.
window.fps_counter.enabled = False  # Auto complete should works here
```
And in IDE, auto-complete works fine now.

But running this code will cause a import error:
```
Traceback (most recent call last):
  File "C:\Users\SuperMarioSF\PycharmProjects\ursina-test\main.py", line 6, in <module>
    from ursina.window import Window
ImportError: cannot import name 'Window' from '<unknown module name>' (unknown location)
```
I checked the code and found the module reference is overridden with a class object instance:
```python
sys.modules[__name__] = Window()
```

This overrides module object itself, thus the origin module cannot be referenced anymore in runtime, caused original class cannot be accessed.

I thought you implements in this way in order to implement object auto registration for Ursina related objects, but replacing module reference is really a bad idea. It may works fine, but many people rely on IDE features, like auto-completion and type checking, to keep productive. 

Maybe the object instance initialization code can be put in `__init__.py` file of the package root, and the class file name should different with object variable, to prevent module object name colliding with the variable name.

If there is a suggested way to enable auto-completion and type checking, I'd like to know, maybe it also should be noted in documentations.

Thanks for your attention.

- - - 

Tested with Visual Studio Code and JetBrains PyCharm Professional. Both IDEs struggle with those replaced module objects and cannot provide proper auto-completion and type checking features.

**Comment by SuperMarioSF** [comment]
Maybe this is a temporary way to do type hinting. But this is a bad hack.
Seems only works in PyCharm.

```python
from ursina import *

app = Ursina()

# ======================================================
# Bad hack to made type hinting works...
# hopefully there is a proper way to resolve this issue.
# also, this approach is not working well if you need multiple source code file to work with.

# fix IDE's "probably undefined" notification
global window  
global camera

 # optionally run type hinting code if code is not running as entrypoint.
if __name__ != '__main__': 
    # import modules. IDE knows what you really want.
    from ursina.window import Window 
    from ursina.camera import Camera
    # do type hinting
    window: Window  
    camera: Camera

# ======================================================

window.fps_counter.enable = False  # auto-completion will work from now on.
window.color = color.black

# more codes...

app.run()
```

**Comment by pokepetter** [comment]
What if I do `window = Window()` instead of `sys.modules[__name__] = Window()` and import it like this: `from ursina.window import window`. Would that work?

**Comment by pokepetter** [comment]
At least in VS Code it seems to work.

**Comment by SuperMarioSF** [comment]
> What if I do `window = Window()` instead of `sys.modules[__name__] = Window()` and import it like this: `from ursina.window import window`. Would that work?

If I done the change right, then it doesn't work. 

I replaced `sys.modules[__name__] = Window()` with `window = Window()` in `ursina/window.py`, then tested with this code:
```python
from ursina import *
from ursina.window import window

app = Ursina()

# current `window` object is from `ursina.window.window`

window.fps_counter.enable = False  # auto-completion will work from now on.
window.color = color.black

# more codes...

app.run()
```

and it throws another exception:
```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "(path omitted...)/ursina-test/venv/lib/python3.8/site-packages/ursina/__init__.py", line 12, in <module>
    from ursina.ursinastuff import *
  File "(path omitted...)src/ursina-test/venv/lib/python3.8/site-packages/ursina/ursinastuff.py", line 129, in <module>
    def print_on_screen(text, position=window.top_left, origin=(-.5,.5), scale=1, duration=1):
AttributeError: module 'ursina.window' has no attribute 'top_left'
```

I doubt this approach will work, and this will probably breaks compatibility with existing code.

- - - 

By the way, I changed to a Linux environment with PyCharm at same version in this output. I also tested on previous Windows environment, The same exception raised.

**Comment by SuperMarioSF** [comment]
I also tried this:

1. In `ursina/window.py`, remove `sys.modules[__name__] = Window()` line;
2. in `ursina/__init__.py`, add following lines at the bottom of the file:
    ```python
    # ... original code above ...
    
    from ursina.window import Window
    window = Window()
    ```
3. Test with following code:
    ```python
    from ursina import *
    
    app = Ursina()
    
    # current `window` object is from `ursina.window`, which is `window = Window()` in `__init__.py`.
    
    window.fps_counter.enable = False  # auto-completion will work from now on.
    window.color = color.black
    
    # more codes...
    
    app.run()
    ```

And it failed with the same exception shown above.
Something went wrong while processing sub-module import inside module.

**Comment by SuperMarioSF** [comment]
Maybe the solution you given will work if all reference to `ursina.window` replaced with `ursina.window.window`. 

But still, this may break compatibility with existing code. Not only `ursina,window` has this problem, but also `ursina.camera`, `ursina.scene`, `ursina.mouse` , `ursina.raycaster` has the same problem.

**Comment by SuperMarioSF** [comment]
Update: I have tried to resolve the issue, but failed.

Currently the code logic is heavily depends on those replaced objects to work. I tried to replaced all occurrence of modules, and circular import error were shown. Resolving this may need a whole fleet of refactor actions to get done.

**Comment by SuperMarioSF** [comment]
The updated "bad hack"exampl code to temporarily fix the problem. 

**Note**: This example only works in PyCharm, and only works in `__main__` module of the project. Will not work in module files within a multiple file project structure.

```python
from ursina import *

app = Ursina()

# ======================================================
# Bad hack to made type hinting works...
# hopefully there is a proper way to resolve this issue.
# also, this approach is not working well if you need multiple source code file to work with.
# Tested with PyCharm. Only works in PyCharm.

# fix IDE's "probably undefined" notification
global window
global camera
global scene
global mouse
global raycast
global boxcast

# optionally run type hinting code if code is not running as entrypoint.
if __name__ != '__main__':
    # import modules. IDE knows what you really want.
    from ursina.window import Window
    from ursina.camera import Camera
    from ursina.scene import Scene
    from ursina.mouse import Mouse

    # do type hinting
    window: Window
    camera: Camera
    scene: Scene = Scene()
    mouse: Mouse

    # extra: raytracing package imported function
    from math import inf
    from ursina.hit_info import HitInfo

    def raycast(self, origin, direction=(0, 0, 1), distance=inf, traverse_target=scene, ignore=list(),
                debug=False) -> HitInfo: pass

    def boxcast(self, origin, direction=(0, 0, 1), distance=9999, thickness=(1, 1), traverse_target=scene,
                ignore=list(), debug=False) -> HitInfo: pass
# ======================================================

# auto-completion will work from now on.

window.fps_counter.enable = False
window.color = color.black

# more codes...

app.run()
```

**Comment by pokepetter** [comment]
I already found the solution and I can make the changes to ursina soon. raycaster is the only one I still have trouble with.
window is imported several places, not just in __init__.py. That's why you got an error.

**Comment by pokepetter** [comment]
I've refactored it now, if you want to give it a try. Auto-complete works in VS Code at least.

**Comment by SuperMarioSF** [comment]
> I've refactored it now, if you want to give it a try. Auto-complete works in VS Code at least.

I have tried latest commit (ecfc52d), it also works flawlessly in PyCharm now. Great job.  :)
