### ISSUE TITLE
Error while attempting to install Ursina Engine

### ISSUE THREAD

**Issue by maximilian8181** [pokepetter/ursina#13]
Why did this happen?
![image](https://user-images.githubusercontent.com/60683437/73812347-16bd4c00-47a2-11ea-9936-5642e61e35ec.png)

**Comment by pokepetter** [comment]
If you want to be able to automatically import .psd files, you' ll need psd-tools. psd-tools need aggdraw, and aggdraw need Microsoft C++ Build Tools installed it seems.

You can either omit that dependency and not get the .psd import or you can download the build tools here: https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by pokepetter** [comment]
You can do this to install ursina only:

pip install git+https://github.com/pokepetter/ursina.git --no-dependencies

The only absolutely required dependency is panda3d which you can install with:

pip install panda3d
