### ISSUE TITLE
regarding hot reload: dont use string splitting, use AST

### ISSUE THREAD

**Issue by laundmo** [pokepetter/ursina#157]
i have recently made a [PR for a small library called reloading](https://github.com/julvo/reloading/pull/11) which also accomplishes hot reload in python.

From my experience there, I recommend using the `ast` module to parse and filter and run the code.
The `ast` module has the great advantage of parsing python code structures to a format that's easier to work with, as it exposes features of the code as python objects, allowing for easier filtering.

**Comment by pokepetter** [comment]
too complicated
