### ISSUE TITLE
Question: Texture Atlas 

### ISSUE THREAD

**Issue by Eternal-plasma** [pokepetter/ursina#166]
Is there a way to use a texture atlas in the engine

**Comment by Evolution0** [comment]
Seeing as Entity has a `texture_offset` variable If its what I think it is you should be able to.

**Comment by Eternal-plasma** [comment]
Thanks, I will try that

**Comment by Eternal-plasma** [comment]
Stupid question here how would I do that

**Comment by Evolution0** [comment]
It would likely be used the same the other options are when creating an Entity, in the init.
