### ISSUE TITLE
line 40 of texture importer

### ISSUE THREAD

**Issue by JacktheFabricRipper** [pokepetter/ursina#171]
In line 40 of texture_importer.py, there are two spaces after the equal sign, and this causes it to not work. Please fix this sometime soon! Thanks!!

**Comment by pokepetter** [comment]
I'll remove those, but that's not why it's not working for you. There must be something else, because it's still valid python

**Comment by JacktheFabricRipper** [comment]
Thank you! I'm not sure what it is then, but all I know is there is definitely an issue in line 40, because when I ran my project, the window said there was an issue in texture importer line 40. I'll try some other things, thank you!
