### ISSUE TITLE
Move game window

### ISSUE THREAD

**Issue by JuenTingShie** [pokepetter/ursina#18]
Hey I had try some tutorials for minutes, and the game window cannot moving to another screen is bothering me a lot, it block my vscode window for "real-time".

Is there any solution to make a "move bar"(Window title) ?

**Comment by pokepetter** [comment]
window.borderless = False
Set it before creating Ursina().

You can also set position, but I'm not sure how well it works with multiple monitors.
window.position = (x, y)

**Comment by JuenTingShie** [comment]
Nice, thanks for answering my question!
