### ISSUE TITLE
Sprite scale_x not working

### ISSUE THREAD

**Issue by Jael-G** [pokepetter/ursina#180]
It seems the scale_x is broken and not working properly. When running my code as well as an example from the cheat sheet, changing scale_y extends or shortens the image vertically, but scale_x does nothing. I tried a workaround which would be using scale = (x,y,z), however it did not work as I expected it, changing the x did nothing, but changing the y changed both x and y. In other words, changing the y in scale=(x,y,z) does the same thing as doing scale = n. Either I'm not understanding the docs, or it's broken.

**Comment by pokepetter** [comment]
That's the point of the Sprite class, to automatically scale the quad to fit the aspect ratio of the image
This will work:
```
s = Sprite('shore')
s.scale_x = 1
```
