### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by ghost** [pokepetter/ursina#185]
hi

Thank you so much for this incredibly easy 3d engine for python!
I was stuck in all other engines because i'm a beginner in game dev.

I would like to ask if you can add more example files on github for doing various things with the engine?
Even if the examples are very basic, it would provide me (and other users) with correct ways to do various things with the engine.

Thx
Jessica

**Comment by dreamsoftunitedkingdom** [comment]
What is the default way to install ursina now?

**Comment by RedHenDev** [comment]
Hi -- here's a playlist of video tutorials I made (https://youtube.com/playlist?list=PLmP1LNMzp97on-P6xoQV6r68e9F6rFceW): intended for beginners, and actually covers quite a bit. I'm absolutely LOVING Ursina!

**Comment by PratangsuRakshit** [comment]
You might watch my tutorial series in ursina.
My channel name - Pratangsu Dev
I upload ursina videos every 2 days

**Comment by nirbhay12345** [comment]
its awesome how this amount of code and produce a game so exicted

**Comment by pokepetter** [comment]
There's lots of example in the `samples` folder. There's also often code at the bottom of each file showing how to use the module/class.
