### ISSUE TITLE
building exe using auto-py-to-exe with embedded resources

### ISSUE THREAD

**Issue by ghost** [pokepetter/ursina#186]
Hi

After building an EXE file using auto-py-to-exe using these instructions: https://www.ursinaengine.org/building.html

The problem is that auto-py-to-exe needs some code in the python source code to find the resource file like this:

https://nitratine.net/blog/post/issues-when-using-auto-py-to-exe/#the-one-file-resource-wrapper

If I apply this for example to this line in my ursina code:

import sys
import os

def resource_path(relative_path):
    """ Get the absolute path to the resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)

grass_texture = load_texture(resource_path("assets/grass_block.png"))

Then after running, I get this error on the code line above to  load_texture():

**"F:\PyCharm project\minecraft\venv\Scripts\python.exe" "F:/PyCharm project/minecraft/minecraft.py"
ursina version: 3.5.0
package_folder: F:\PyCharm project\minecraft\venv\lib\site-packages\ursina
asset_folder: F:\PyCharm project\minecraft
blender_paths:
{'default': WindowsPath('F:/Programma/Blender Foundation/Blender/blender.exe')}
screen resolution: (2560, 1440)
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
size; LVector2f(2048, 1152)
render mode: default
no settings.py file
Traceback (most recent call last):
  File "F:\PyCharm project\minecraft\minecraft.py", line 15, in <module>
    grass_texture = load_texture(resource_path("assets/grass_block.png"))
  File "F:\PyCharm project\minecraft\venv\lib\site-packages\ursina\texture_importer.py", line 39, in load_texture
    for filename in folder.glob('**/' + name):
  File "F:\Programma\Python\lib\pathlib.py", line 1166, in glob
    for p in selector.select_from(self):
  File "F:\Programma\Python\lib\pathlib.py", line 600, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "F:\Programma\Python\lib\pathlib.py", line 532, in _select_from
    if (is_dir if self.dironly else exists)(path):
  File "F:\Programma\Python\lib\pathlib.py", line 1422, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "F:\Programma\Python\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] De syntaxis van de bestandsnaam, mapnaam of volumenaam is onjuist: 'F:\\PyCharm project\\minecraft\\F:'

Process finished with exit code 1
**

I use python  Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)] on win32
and ursina version: 3.5.0

This way for the path to a resource file works correctly in a Pygame program.

Can you tell me please how to reference a resource file correctly in ursina for making an EXE file using  auto-py-to-exe ?

Thx

**Comment by catornot** [comment]
I am no expert but Ursina has built-in compiler to bat files 
[https://www.ursinaengine.org/cheat_sheet.html#build](this could help you)

**Comment by crjase** [comment]
Try using pyinstaller. The arguments go like this: [cd project directory] > [pyinstaller minecraftclone.py]. Then it builds an exe for you.
