### ISSUE TITLE
[Bug] world_rotation doesn't work properly

### ISSUE THREAD

**Issue by ELginas** [pokepetter/ursina#190]
I have made an example, where I parented my frozen rotation block to FirstPersonController. Code is shown below.
```python
from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController

class NoRotateBlock(Entity):
    def __init__(self, **kwargs):
        super().__init__(model='cube', color=color.lime)

        for key, value in kwargs.items():
            setattr(self, key, value)
    
    def update(self):
        self.world_rotation = Vec3(25, 25, 25) # doesn't change
        print(self.world_rotation)

app = Ursina()

floor = Entity(model='cube', collider='box', texture='white_cube', color=color.cyan, scale=(50, 1, 50), y=-15)
player = FirstPersonController()
block = NoRotateBlock(parent=player)

app.run()
```

The problem is that world rotation doesn't change anything. I tried running this code without parenting to FirstPersonController, but results are still same. To make sure my code isn't broken, I replaced `self.world_rotation` with `self.rotation` and it worked perfectly as long as it was parented to scene. As soon as I parented it to FirstPersonController, it did anything.
I thought that FirstPersonController is changing it's own rotation every update call and I checked it.
```python
def update(self):
        self.rotation_y += mouse.velocity[0] * self.mouse_sensitivity[1]

        self.camera_pivot.rotation_x -= mouse.velocity[1] * self.mouse_sensitivity[0]
        self.camera_pivot.rotation_x= clamp(self.camera_pivot.rotation_x, -90, 90)
```
Camera pivot isn't even important here, so the only code line which changes rotation is only changing y direction, but not x and z directions. `self.world_rotation` is also immediately changed after setting it.
```python
def update(self):
        self.world_rotation = Vec3(25, 25, 25) # doesn't change
        print(self.world_rotation) # prints parent position, but not self position, expected result Vec3(25, 25, 25)
```

**Comment by pokepetter** [comment]
Fixed ^^ 
Thanks for the report
