### ISSUE TITLE
Render distance

### ISSUE THREAD

**Issue by SuperZombi** [pokepetter/ursina#196]
How do I limit the render distance for the player's camera? Due to the fact that there are a lot of objects on the map, the game starts to freeze.

**Comment by Password-Classified** [comment]
Have you tried adding fog, or changing any entities `visible` attribute when a certain distance away (perhaps calculate distance using Pythagoras' Theorem). @SuperZombi

**Comment by SuperZombi** [comment]
Fog is a post effect. It does not help

**Comment by Password-Classified** [comment]
Have you tried the `visible` attribute solution? @SuperZombi

**Comment by SuperZombi** [comment]
Yes, but this option is not very efficient. If I want to load the map, when starting the game, it will take a long time. It is necessary to implement dynamic loading of the map at the engine level.

**Comment by RedHenDev** [comment]
myCamera = EditorCamera()
camera.clip_plane_far=200

Try that, buddy.

**Comment by SuperZombi** [comment]
This is not exactly what I need. This is a 2D camera with a side view. And I need 3D.

**Comment by yellowwithblue** [comment]
Is your game First Person or Third Person?

**Comment by SuperZombi** [comment]
> Is your game First Person or Third Person?

1st person

**Comment by yellowwithblue** [comment]
Do you have from ursina.prefabs.first_person_controller import FirstPersonController
on your game?

**Comment by pokepetter** [comment]
`camera.clip_plane_far = 200` is correct

**Comment by Flymeth** [comment]
This modification resets the Sky element

**Comment by Yar6352** [comment]
It would be nice to find a way to change the color to transparent, I use ursina to retrain the yolo detector to my classes, it is inconvenient to mark up data without limiting the drawing range.

**Comment by KOD2009** [comment]
uhh, I making a minecraft clone and thanks.but ı using camera.clip_plane_far = 15. beacuse it is Very big world.
