### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by HamishHamiltonSmith** [pokepetter/ursina#197]
Hey, 

I am getting an error when trying to clone this repository, my computer doesn't recognize the package panda3d, I get this error:

Collecting https://github.com/pokepetter/ursina/archive/master.zip                                                                                                                                                               
  Downloading https://github.com/pokepetter/ursina/archive/master.zip                                                                                                                                                            
     | 7.9 MB 3.0 MB/s
Requirement already satisfied: numpy in ./.local/lib/python3.9/site-packages (from ursina==3.5.0) (1.20.1)                                                                                                                       
ERROR: Could not find a version that satisfies the requirement panda3d (from ursina)
ERROR: No matching distribution found for panda3d

Is there a way I can update my packages list or something so that panda3D is available?

**Comment by pokepetter** [comment]
What's your OS?

**Comment by TheGamaray** [comment]
My OS is kali linux.

**Comment by pokepetter** [comment]
panda3d doesn't have have prebuilt wheels for rpi, but will have very soon I think.
