### ISSUE TITLE
Doesnt have mouse.entity

### ISSUE THREAD

**Issue by VladKing12** [pokepetter/ursina#202]
I'm using mouse.entity, but i'm having an error(AttributeError: 'Mouse' object has no attribute 'entity'). Maybe I don’t understand how it works? (I'm using this tutorial https://www.ursinaengine.org/entity_basics.html)

**Comment by pokepetter** [comment]
Oh, that should be .hovered_entity, not .entity. Will fix

**Comment by VladKing12** [comment]
Thanks, it works!
