### ISSUE TITLE
Generate Ore In Sample Minecraft Clone

### ISSUE THREAD

**Issue by gobrit** [pokepetter/ursina#210]
Hi,

I am trying to Generate ores in the Minecraft Clone but I am new to urine Engine and a beginner in python. I tried to select a random block and destroy it and place a new block but I cannot because the destroy() function does allow only to destroy the entity and not with coordinates. Please help me to destroy the block or is there any other way? 

Thank you in advance,
Rithik Gobinath.

**Comment by RedHenDev** [comment]
Hey, buddy. I've started creating my own version(s) of Minecraft (LOVING Ursina -- Petter is a genius) -> and have a simple system of deleting blocks here: https://github.com/RedHenDev/python/tree/master/ursina%20dev/python%20minecraft 

Try the June 20th version. 

Here is a video tutorial -- I've not got round to ores etc. with this, but have made larger (and as of today, infinitely procedural terrains): https://youtube.com/playlist?list=PLmP1LNMzp97pQe1FiGpdOLKeWYfTMZM7n

**Comment by CyberDeveloper-sys** [comment]
@gobrit  please close the issue if possible
