### ISSUE TITLE
[REQUEST] Add a function to unload all items that aren't visible to the player

### ISSUE THREAD

**Issue by alf1e** [pokepetter/ursina#212]
Add a function to unload all items that aren't visible to the user in `FirstPersonController()` , this will help reduce lag

**Comment by alf1e** [comment]
Is this done?

**Comment by pokepetter** [comment]
No, and it doesn't sound like you know what you're talking about to be honest. This would introduce lag and make most games break, like when walking backwards into a wall, the wall would be 'unloaded' and there's no longer a wall there. Culling is already on by default
