### ISSUE TITLE
3D level editor not working

### ISSUE THREAD

**Issue by PratangsuRakshit** [pokepetter/ursina#213]

**Comment by pokepetter** [comment]
What does that mean?

**Comment by PratangsuRakshit** [comment]
Sir/ma'am, I mean that the level editor is unable to select any entity
other then that everything is fine.

**Comment by pokepetter** [comment]
Got an example? Because I can select entities just fine

**Comment by PratangsuRakshit** [comment]
Ohhhh, sorry I used a earlier version of ursina
