### ISSUE TITLE
Ursina can't compile to .exe file

### ISSUE THREAD

**Issue by LeeFuuChang** [pokepetter/ursina#218]
Is it impossible to compile Ursina python file to .exe？
here's the code I use to test compiling Ursina program to .exe type file
```python
from ursina import *
app = Ursina()
app.run()
```
and the code to generate .exe file
```bat
pyinstaller --onefile -w ss.py
```
the Terminal shows that the compiling process was completed successfully

<img width="547" alt="1" src="https://user-images.githubusercontent.com/77952182/123530029-baf1bb00-d728-11eb-9b6e-37f70b2559e3.png">

but the .exe file that came out can't be executed properly

![image](https://user-images.githubusercontent.com/77952182/123530011-8a118600-d728-11eb-8fc5-8c914366a02a.png)

and then I tried to bring up the console
here's the Error Traceback
![image](https://user-images.githubusercontent.com/77952182/123530226-9c8cbf00-d72a-11eb-9371-e24ec5ad9b00.png)

**Comment by Password-Classified** [comment]
I have been able to convert it to a .exe file. A good way is by running
```
pip install auto-py-to-exe
```
then, find the .exe file for *auto-py-to-exe* in the Scripts folder in Python's Appdata folder. Then, follow the instructions as on Urisna's docs (or as below).

**For Windows, but should be the same for linux, apple, etc.**
Once opened the exe for auto py to exe, you'll see the UI.
Then, choose your file, icon, etc.
Finally, click add folders and add the `ursina` and `ursina-dist-info` folders from the site-packages folder where python packages are stored. Then click the button to create your .exe in the output folder you specified. You'll find the .exe in the dist folder.


--------------------------------

The thing you missed was adding the `ursina` and `ursina-dist-info` folders from site packages. What auto-py-to-exe does is create the pyinstaller command, but makes it easier for you by providing you with a UI.

**Comment by LeeFuuChang** [comment]
> I have been able to convert it to a .exe file. A good way is by running
> 
> ```
> pip install auto-py-to-exe
> ```
> 
> then, find the .exe file for _auto-py-to-exe_ in the Scripts folder in Python's Appdata folder. Then, follow the instructions as on Urisna's docs (or as below).
> 
> **For Windows, but should be the same for linux, apple, etc.**
> Once opened the exe for auto py to exe, you'll see the UI.
> Then, choose your file, icon, etc.
> Finally, click add folders and add the `ursina` and `ursina-dist-info` folders from the site-packages folder where python packages are stored. Then click the button to create your .exe in the output folder you specified. You'll find the .exe in the dist folder.
> 
> The thing you missed was adding the `ursina` and `ursina-dist-info` folders from site packages. What auto-py-to-exe does is create the pyinstaller command, but makes it easier for you by providing you with a UI.

It still doesn't work after I added ursina and ursina-dist-info in to compiling
![image](https://user-images.githubusercontent.com/77952182/123565555-e55a7b80-d7ef-11eb-93bb-c6ca4c4ccb68.png)
here's how I add the folder
and I even tried to add the whole site-packages folder in to compiling
and it still doesn't work

**Comment by darkerbess** [comment]
try adding
```
panda3d-1.10.6.dist-info,
panda3d,
panda3d_tools,
ursina-3.1.0.dist-info,
ursina,
```
download panda3d if you don't have the files
```
pip install panda3d
```

and use one directory, if you want use one file you need put only your assets in the same directory of the exe like this 
![2021-06-29-152433_1366x768_scrot](https://user-images.githubusercontent.com/48066881/123862583-246ef680-d8ee-11eb-8fb8-4278b5f359dc.png)

PD: Sorry for my english, i speak spanish

**Comment by PratangsuRakshit** [comment]
It worked for me atleast

**Comment by Maciej-dev** [comment]
where i can find folders like panda3d or panda dist info

**Comment by Password-Classified** [comment]
Open the windows start menu and search `%appdata%`. It should open a directory called AppData/Roaming. Go out  of roaming into appdata, the parent directory.

Then, go to Local/Programs/Python/Python39/Lib/site-packages.

The folders should be there.

**Comment by FinnBoiG** [comment]
I dont have ursina 2.5.0 dist info thing, how do i get it cause i have everything else

**Comment by FinnBoiG** [comment]
it mainly works but it keeps on giving errors like these, how do i fix it?
![image](https://user-images.githubusercontent.com/90984764/133906241-1e45ad54-995a-40f0-a8c8-f6f8c6c56f66.png)

**Comment by Password-Classified** [comment]
Have you tried `pip install ursina` again?

**Comment by FinnBoiG** [comment]
yeah i have

**Comment by pokepetter** [comment]
Try this to get rid of the error: Go under "Advanced" to "–paths" and add folder "YOUR_PYTHON_FOLDER/Lib/site-packages/panda3d"

**Comment by DragonlordNewb** [comment]
it isn't working for me either, it's saying that i'm not providing a graphics pipe

**Comment by kowshik1234** [comment]
Worked like a charm, thanks !
