### ISSUE TITLE
Installing on Raspberry Pi 4b+ Fails

### ISSUE THREAD

**Issue by raytopianprojects** [pokepetter/ursina#219]
I had seen in the discord server that a few people were using Ursina on the Raspberry Pi (using the 64 bit version of Raspberry Pi OS). I thought it would be fun to try it out and see how far I could push the Pi but when I attempted to install Ursina via pip the installation failed when attempting to install the Panda3d wheels.

So I was wondering if there is a way to install the Ursina Engine/Panda3d on the Raspberry Pi? If it is not possible I will close the issue.

Thanks for your time!

**Comment by pokepetter** [comment]
You can build it yourself or maybe find a wheel somewhere
