### ISSUE TITLE
No "mouse wheel up" and "mouse wheel down" in keys_held

### ISSUE THREAD

**Issue by BlockOG** [pokepetter/ursina#220]
I would want to make it so when I scroll make camera moves on the z axis but I can't because there's no way of knowing when the mouse wheel is scrolled from the update() function
If it's possible let me know

**Comment by pokepetter** [comment]
`mouse.middle`

**Comment by pokepetter** [comment]
Mouse scroll isn't a continuous thing as far as I know. get the inputs in the input function instead.

**Comment by BlockOG** [comment]
`mouse.middle` gives True or False depending on if the middle mouse button is clicked
And I'm pretty sure mouse scroll is continuous

**Comment by BlockOG** [comment]
> Mouse scroll isn't a continuous thing as far as I know. get the inputs in the input function instead.

How do I do that, the camera inherits from Entity() not Button()

**Comment by pokepetter** [comment]
https://www.ursinaengine.org/introduction_tutorial.html

**Comment by pokepetter** [comment]
https://www.ursinaengine.org/entity_basics.html

**Comment by BlockOG** [comment]
But if I do `camera.input = cameraInput # <-- function I made` it doesn't get the key parameter

**Comment by pokepetter** [comment]
Yes, it does:
```py
def camera_input(key):
    print(key)

camera.input = camera_input
```

**Comment by BlockOG** [comment]
Ohhhh, thanks
