### ISSUE TITLE
ModuleNotFoundError: No module named 'ursina.prefabs'; 'ursina' is not a package

### ISSUE THREAD

**Issue by Trolto** [pokepetter/ursina#226]
I have no idea why I'm getting this error, I have tried installing both from GitHub and PyPI.

Python version: 3.8.6

**Comment by pokepetter** [comment]
This is not enough information to help you. It's clear you haven't installed ursina though, or have installed to a different Python than the one you're running the script with. Since this is a general python/pip thing, you should be able to find out how to install packages.

**Comment by Trolto** [comment]
I checked and I did do everything correct. I tried googling but I'm still clueless.

**Comment by Trolto** [comment]
I have also tried using every installing method

**Comment by omeco4christ** [comment]
I am having a similar problem!
