### ISSUE TITLE
ursina wont download as a package on my raspberry pi

### ISSUE THREAD

**Issue by ShortsKing** [pokepetter/ursina#230]
i am trying to download ursina and i cant because it comes up with the following error: `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e6VVGx/ursina/`

all you have to do to repeat the problem is type the terminal `pip install ursina`

**Comment by HeyItsAnushtubh** [comment]
Try the github version - `git clone https://github.com/pokepetter/ursina.git`
It should work then (maybe)

**Comment by pokepetter** [comment]
https://github.com/pokepetter/ursina/issues/219
