### ISSUE TITLE
Add arrow keys to the FirstPersonController

### ISSUE THREAD

**Issue by Timely10** [pokepetter/ursina#231]
I am left-handed and find it hard to use WASD. Is it possible to add arrow-key support to the FirstPersonController?

**Comment by Lewis7Lewis** [comment]
`https://github.com/pokepetter/ursina/pull/232`
there are all change but wait the Pull

**Comment by pokepetter** [comment]
add rebinds in settings.py
` bind(original_key, alternative_key)` or `rebind(to_key, from_key)`
like this:
`rebind('w', 'z')`
