### ISSUE TITLE
Ursina 3.6.0 changing behaviour of .combine() from 3.5.0?

### ISSUE THREAD

**Issue by RedHenDev** [pokepetter/ursina#233]
Does anyone know of any change that may be causing this? -- child entities are no longing combining correctly (or at all?) into their parent entity.

**Comment by pokepetter** [comment]
The only change was a fix to make sure origin is taken into account.
How do I reproduce this?

**Comment by RedHenDev** [comment]
Thanks for reply, Petter. Very kind.

Yes, I think the following correction may be the issue (for me): 

![Screenshot 2021-07-28 at 12 38 56](https://user-images.githubusercontent.com/24874180/127316620-bcf140e3-7b4f-4b62-9334-672c9eae7df7.png)

Sorry -- will try to give you something to reproduce this with asap: it wasn't actually my issue, but a subscriber of mine (I've been making a Minecraft series using your Ursina Engine (wonderful, wonderful work, by the way!) for an infinitely procedural Perlin terrain, where I combine every 16 cubes of the terrain into a single chunk/subset. This was working for me [(tutorial 7)](https://youtu.be/8RtTgxJFVO0) but was producing strange effects for a subscriber: [issue discussion](https://github.com/RedHenDev/python/issues/1)

I think each child cube is taking the position of its parent instead of the preferred behaviour (in my case) of populating the empty subset entity with the combined meshes of its children.

Hope that makes some sense. 

Best

Brian

**Comment by RedHenDev** [comment]
OK -- have found the key issue.

It depends on how we are loading in our model.

I had thought that `blockModel=load_model('block.obj')` and then `e=Entity(model='blockModel') `would be equivalent to `e=Entity(model='block.obj')` but this is clearly not the case.

[See here](https://github.com/RedHenDev/ursina_tutorials/tree/main/combine%20issue) for a simple reproduction of the difference in behaviour, which does indeed manifest with the combine() update. 

![Screenshot 2021-07-30 at 10 36 36](https://user-images.githubusercontent.com/24874180/127634037-4e6e0993-a393-47bd-ba1f-add1818316ad.png)
Versus:
![Screenshot 2021-07-30 at 10 37 06](https://user-images.githubusercontent.com/24874180/127634051-610775fd-4962-48ac-92af-4895ddf65e11.png)

Thanks again -- solution for now is easy, i.e. I'll not use load_model() and there's no problem. But I'll look into your load_model() code to see how I'm using it wrong; or is it supposed to be equivalent?

Thanks

Brian

**Comment by pokepetter** [comment]
When setting the model to an actual model, you need to copy it: `model=copy(blockModel)` or `model=deepcopy(blockModel)` if you need access to the vertices and such. It not, it will just reparent the model.

You could also do `model=load_model('blockModel')`.
Keep in mind loaded models are cached anyway, so there's no downside to `model='blockModel'`

**Comment by RedHenDev** [comment]
Thanks so much, Petter. That's so clear now.

Thanks for taking the time, buddy.
