### ISSUE TITLE
Terrain creator wont work

### ISSUE THREAD

**Issue by BellVirtual** [pokepetter/ursina#241]
Anytime I try to generate terrain like this 

ground = Entity(model=Terrain("noise_1/noise_Texture" , skip=8), scale=(100, 20, 100), position=(0,0,0))

I get this error

TypeError: C++ object is not yet constructed, or already destructed.

**Comment by BellVirtual** [comment]
This is strange becuase ive gotten the terrain generator to work before

**Comment by pokepetter** [comment]
You have to create Ursina() first

**Comment by BellVirtual** [comment]
I did this is the full code
`app = Ursina()



def gen_world():
    noisenum = str(random.randint(1, 98))
    Entity(model=Terrain("noise_1/noise_Texture" + noisenum, skip=8), scale=(100, 20, 100), position=(0,0,0))


gen_world()
app.run()
`

**Comment by BellVirtual** [comment]
It should also be noted that I got a similar error whenever I would use terraincast

**Comment by BellVirtual** [comment]
After changing images for the height map suddenly it is not giving me this error
This is the original image
![noiseTexture](https://user-images.githubusercontent.com/79067920/128928568-cc7bf2ad-09cb-4e45-8fbf-ec3d55669449.png)

I then used the height map texture found in the ursina samples file and it didnt give me any errors 
![height_map](https://user-images.githubusercontent.com/79067920/128928726-bdecb1e7-e80e-4b1c-869c-eb3d83450143.png)


I dont know why it crashed when using the original image however
