### ISSUE TITLE
Rotation-y not in line with entity

### ISSUE THREAD

**Issue by Neleird** [pokepetter/ursina#242]
Rotation_y it's not in line with the entity but stays in line with world. 
When using rotation_x = 90, rotation_y and rotation_z have the same effect on the entity!

Is this a bug or is it as designed?

**Comment by pokepetter** [comment]
That's just how it works. It's the same in Unity for example. If you're having trouble getting the rotation you want I recommend either using `look_at()` or parent several entities and rotate them individually one axis each.
