### ISSUE TITLE
How to create a texture for ursina engine

### ISSUE THREAD

**Issue by AbdulWahab321** [pokepetter/ursina#243]
I created uv mapped image in blender but How to export it and use it in ursina?

Please help me

**Comment by pokepetter** [comment]
No, you created an uv mapped model. If you drew the texture in Blender too, you can export it from there. There's a menu somewhere in the unwrapping window.

**Comment by AbdulWahab321** [comment]
Yeah 
I exported but That UV mapped model doesn't contain the image

**Comment by pokepetter** [comment]
That's true, you load the model and texture separately. 
1) Export the image, as a .png for example.
2) Load the model and texture like you normally would, `Entity(model='name_of_the_blend_file', texture='name_of_the_image_you_exported'`
