### ISSUE TITLE
App window is getting shifted and doesn't work properly

### ISSUE THREAD

**Issue by FrCln** [pokepetter/ursina#255]
Ursina installed successfully on Manjaro linux. When I start any of example applications, the window first opens properly, but when a message "application successfully started" appears, window title shifts strangely. It looks like another window is opened above the old one. When the title bar is clicked, window disappears. No error messages are shown. When I close application via ctrl-C, window blinks for a moment and application stops normally.
![Screenshot_20210827_210709](https://user-images.githubusercontent.com/54150197/131170494-bda0d4bd-4967-4d3c-a4d7-d81ee38dc037.png)
When application is running, it also doesn't handle mouse moves correctly.

I tried it on Ubuntu as well, and it works fine.

**Comment by alovictor** [comment]
I'm getting the same in manjaro... when I click outside, the window disappears!

**Comment by y2bad** [comment]
i had that problem to, it's because borderless window is not supported just put window.borderless=False in your code

**Comment by AlfonsodRioss** [comment]
> i had that problem to, it's because borderless window is not supported by KDE just put window.borderless=False in your code

I had the same problem in Manjaro with gnome and this solved my problem.

**Comment by SamMatzko** [comment]
[y2bad's comment](https://github.com/pokepetter/ursina/issues/255#issuecomment-1011199564) also works on Ubuntu 20.04 (with GNOME).
