### ISSUE TITLE
Wierd camera behaviour 

### ISSUE THREAD

**Issue by ayi-afk** [pokepetter/ursina#26]
While playing with your 'minecraft' example a created a grid 10x10x10 blocks and notices that camera starts shaking once i look at the 'megacube' once I look away shaking stops.

Win 10
Py 3.7 64bit
ursina==0.1

Video as ref: https://www.youtube.com/watch?v=mYnGFlW_7_A

**Comment by pokepetter** [comment]
It seems it only happens when the fps drops below 60. The issue was with camera position smoothing in the FirstPersonController, but I think I've fixed it now.

I never would have found this bug on my own, haha, so thank you.
