### ISSUE TITLE
my obj turns to a gray, transparent block.

### ISSUE THREAD

**Issue by newbies155** [pokepetter/ursina#266]
My OBJ file (made in blender) just becomes black when it is imported, here is the screenshot (and yes i did try triangulating it.)
![image](https://user-images.githubusercontent.com/69512353/132538668-f453b8b1-dd7b-41b9-ba39-656994caf503.png)

Here is the code aswell as the OBJ file.
https://anonfiles.com/zf560eGdue/untitled_obj
https://anonfiles.com/375800G4u2/main_py

**Comment by pokepetter** [comment]
What's the default color for Buttons?

**Comment by newbies155** [comment]
its in the file, this is an old project so i dont really remember, however i think its the same as the minecraft clone.py.

**Comment by pokepetter** [comment]
No, it's (0,0,0, 0.66), which is meant for ui elements, and you never change it to white for example.

**Comment by newbies155** [comment]
Oh thanks, ill try that solution.
