### ISSUE TITLE
Sphere texturing / generating problems

### ISSUE THREAD

**Issue by kesslmar** [pokepetter/ursina#27]
Trying to set up a little planet, i quickly ran into issues to texture the standard sphere that you provide in the library. Loading a texture on it with texture='myTex' results into just covering the sphere in the most dominant color of the texture. So even loading your texture 'brick' ends up as a greyish ball, where if i load it onto the cube i can clearly see the brick pattern.

I then tried the same with your procedural sphere object, which ended in the same result. In addition, the subdivision doesent seem to work for me. With subdivision=0 i see the Icosahedron, just with 3 missing triangles (i can see through the object). But as soon as i increase the subdivision, the object absolutely deforms with faces shooting out of the window.

Chances are high im doing something wrong here, but i thought this needed to be pointed out.

Environment:
Windows 10
Python 3.7.6 64-Bit
Panda3D 1.10.5
Ursina 0.1 obv.

Normal cube:
![cube](https://user-images.githubusercontent.com/5538542/75918918-e4644480-5e5c-11ea-84ac-d80af834ab3d.PNG)
Normal sphere:
![shpere_model](https://user-images.githubusercontent.com/5538542/75918942-efb77000-5e5c-11ea-86a9-e3af5f1b8cf5.PNG)
Subdivision 0 sphere:
![subdivision0](https://user-images.githubusercontent.com/5538542/75918962-f80fab00-5e5c-11ea-99c9-7249b93e5c56.PNG)
Subdivision 3 sphere:
![subdivision3](https://user-images.githubusercontent.com/5538542/75918979-fe9e2280-5e5c-11ea-921d-0643cb7015c1.PNG)

BTW: Thank you for your awesome work in giving panda3d the overhaul it so urgently needs :->

**Comment by pokepetter** [comment]
Added uvs to the 'sphere' model:
![image](https://user-images.githubusercontent.com/6485988/76150189-f4bc2f80-60a7-11ea-947b-34be75927f33.png)

I will take a look at the icosphere soon.

**Comment by kesslmar** [comment]
Awesome. UVs are working. I'm looking foreward to the icosphere. Thanks again for your great work! Keep it up!
