### ISSUE TITLE
Crashes as soon as it starts.

### ISSUE THREAD

**Issue by HeronErin** [pokepetter/ursina#270]
I'm running kubuntu, when I run the example code, as soon as I click the window's title bar, the window disappears but the program is still running. 

Here is the log:
>  /home/name/PycharmProjects/cubeRende/venv/bin/python /home/name/PycharmProjects/cubeRende/main.py
>  package_folder: /home/name/PycharmProjects/cubeRende/venv/lib/python3.8/site-packages/ursina
>  asset_folder: /home/name/PycharmProjects/cubeRende
>  blender_paths:
>  {'default': '/usr/bin/blender'}
>  OS: posix
> screen resolution: (1366, 768)
>  Known pipe types:
>    glxGraphicsPipe
>  (4 aux display modules not yet loaded.)
>  size; LVector2f(1092, 614)
>  render mode: default
>  :pnmimage:png(warning): iCCP: known incorrect sRGB profile
>  development mode: True
 >  application successfully started
 >  interrupt by keyboard

**Comment by sheeepdev** [comment]
I got the same problem

**Comment by pokepetter** [comment]
It works fine on Pop OS and Arch, so my guess is there's something about your configuration, or Kubuntu's.
Also, how can it crash, but still run?

**Comment by sheeepdev** [comment]
> It works fine on Pop OS and Arch, so my guess is there's something about your configuration, or Kubuntu's. Also, how can it crash, but still run?

I'm on arch

**Comment by zeopticz** [comment]
Same thing. Windows 11

**Comment by zeopticz** [comment]
Are you sure the `app.run` line has a `()` after it?
So the last line of the code should be `app.run()` 
(app or any variable that has the `Ursina()` value, however you named it)

**Comment by y2bad** [comment]
i had that problem to, it's because borderless window is not supported just put window.borderless=False in your code
