### ISSUE TITLE
Position-dependent arguments in Entity?

### ISSUE THREAD

**Issue by UplinkPhobia** [pokepetter/ursina#274]
I'm discovering ursina, so this issue might seem normal or whatnot. However, saying it disturbs me would be an understatement.

I was following the inventory tutorial, and fiddling around a bit. Was having really weird results despite having the same code logic, and ended up copy-pasting from the samples, which worked.
Apparently, the issue was that the order of named arguments matters, which to me is a bug. 

As such, this works:
```python
class Inventory(Entity):
    def __init__(self):
        super().__init__(
            parent=camera.ui, model='quad', scale=(.5, .8), origin=(-.5, .5), position=(-.3,.4),
            texture='white_cube',
            texture_scale=(5,8), color=color.dark_gray
            )

        self.item_parent = Entity(parent=self, scale=(1/5,1/8))
```
But this doesn't:
```python
class Inventory(Entity):
    def __init__(self):
        super().__init__(
            texture='white_cube',
            parent=camera.ui, model='quad', scale=(.5, .8), origin=(-.5, .5), position=(-.3,.4),
            texture_scale=(5,8), color=color.dark_gray
            )

        self.item_parent = Entity(parent=self, scale=(1/5,1/8))
```

Various buggy results can be achieved by moving things around, in this example the entity will simply not be visible, while putting the texture argument last for example will ignore the texture_scale.

This behaviour is weird at best, since one of the main points of named arguments are supposed to be position-independent.

**Comment by pokepetter** [comment]
Yes, it just loops through all the keyword arguments and sets them in order. However, I've now changed it so it shouldn't matter. You can update with `pip install https://github.com/pokepetter/ursina/archive/master.zip --upgrade`

**Comment by UplinkPhobia** [comment]
Seems to be working, thanks for the work!
