### ISSUE TITLE
Upload a game

### ISSUE THREAD

**Issue by JuhilModi** [pokepetter/ursina#275]
I had made a game in ursina, now how to upload the game to any appstore ?

**Comment by pokepetter** [comment]
To build for Windows, cd to the project folder and run:
`python -m ursina.build`

Make sure to inlude any extra modules with `--include_modules PIL,numpy` for example.
Any errors will be logged in log.txt.

I haven't uploaded a game on every app store in existence, but the process will probably be different for each. I have uploaded to itch.io though. To upload to itch.io, run this. See their guide for more info.
`butler push build username/game-name:windows`

(optional) To make it launchable in the Itch launcher, add a `.itch.toml` file :
```
[[actions]]
name = "play"
path = "your_game.bat"
```
change "your_game.bat" to the name of your .bat file.

**Comment by Tech-Helper503** [comment]
I compile using either pyinstaller or py2exe. Those take files from python and convert them to bundles or to exe files
