### ISSUE TITLE
Loaded model deletes previous instance if new one is created

### ISSUE THREAD

**Issue by ShadowNightX** [pokepetter/ursina#278]
Sorry if this is a glitch in my code, because I am rather new to ursina.
I exported a UV model from blender as a .obj file which I have loaded in my main script.
This is my main script:
```python3
from ursina import *
from player import Player
app = Ursina()
block = load_model("resources/block.obj")
grass_texture = load_texture("resources/grass_texture.png")
dirt_texture = load_texture('resources/dirt_texture.png')

class Voxel(Entity):
    def __init__(self, texture, position=(0, 0, 0), model="cube"):
        # Ends up with default position if no information is being passed
        super().__init__(
            parent=scene,
            position=position,  # Right in the middle
            model=model,
            origin_y=0.66,
            texture=texture,
            color=color.color(0, 0, random.uniform(0.9, 1)),  # Each block has a random grayscale shade
            scale=1
        )
        self.collider = self.model

# Grass Layer
for z in range(24):
    for x in range(24):
        voxel = Voxel(grass_texture, position=(x, 10, z), model=block)
# Dirt Layer
y = 10
while y > 1:
    y = y - 1
    for z in range(24):
        for x in range(24):
            voxel = Voxel(dirt_texture,  position=(x, y, z))

player = Player()
app.run()

```
BTW, the grass_texture.png is an unwrapped texture for the block.obj.
In the same directory is another script called ```player.py``` for instancing the player:
```python3
from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController


class Player(FirstPersonController):
	def __init__(self):
		super(Player, self).__init__()
		self.camera = camera
		self.speed = 8
		camera.fov = 60
		self.mouse = mouse
		self.in_menu = False
		self.crouching = False
		self.sprinting = False
		self.position = (0, 10, 0)
```

My problem is that when I run it, I end up with just one grass block at the point where the world gen code should place the last block. When I added a simple block placing function, and tried to place a block, the one placed before it would just delete itself and create a new instance.

The help is appreciated,
ShadowNightX

**Comment by pokepetter** [comment]
Don't use load_model. It's mainly for internal use or when you need to load a model without attaching it to an Entity. Load models as described in the documentation instead, see entity basics.
If you still need to use load_model, you can use copy or deepcopy to copy it.

**Comment by ShadowNightX** [comment]
Thanks! Implementing that worked and fixed another issue I had as well.
