### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Tomda8** [pokepetter/ursina#28]
Hello,

I wanted to try ursina, but when trying to get any ursina game running, I get this :

File "/Users/tmd/Library/Python/2.7/lib/python/site-packages/ursina/sequence.py", line 132
    Func(print, 'one'),
             ^
SyntaxError: invalid syntax

(the caret is actually under the "t" of print)
I just saw this file was corrected for a typo 4 days ago, could there be another bug in it ?

Thanks a lot anyway for this very cool project.

**Comment by pokepetter** [comment]
You have to use python3.
