### ISSUE TITLE
Destroy a Animator object ursina

### ISSUE THREAD

**Issue by YuvanLohia** [pokepetter/ursina#287]
I have an animator object in ursina. I want to destroy it.
```from ursina import *
app = Ursina()
walka = Animation("assets/zombies/zombie1/walk/",fps = 5,loop=True)
animator1 =  Animator(animations= {"walk":walka})
animator1.state = "walk"
destroy(animator1)
app.run()
```
This doesn't seem to work and throws this error: `AttributeError: 'Animator' object has no attribute 'eternal'`

**Comment by YuvanLohia** [comment]
[https://stackoverflow.com/questions/69444950/destroy-a-animator-object-ursina?noredirect=1#comment122745374_69444950](url)

**Comment by pokepetter** [comment]
Why do you want to destroy it? Animator is not an Entity, so it's not meant to be destroyed. You can remove references to it so it gets garbage collected or use the del keyword.

**Comment by YuvanLohia** [comment]
I am making a game in which we need to shoot zombies. I want the zombies to appear that they are moving, so I used an animation. So the problem is how do I destroy that object as when many zombies are present and the dead ones also, it reduces the fps to 2. How do I remove the references and how to used del keyword?
