### ISSUE TITLE
rotation_y=180 makes sprite disappear

### ISSUE THREAD

**Issue by Innoviox** [pokepetter/ursina#29]
I was trying to flip a slime sprite around the y-axis:

![areg](https://user-images.githubusercontent.com/21976953/76167213-727d4b00-613b-11ea-9a47-944eb6b5f7ad.png)

This is the goal:
<img width="60" alt="Screen Shot 2020-03-08 at 12 51 24 PM" src="https://user-images.githubusercontent.com/21976953/76167224-888b0b80-613b-11ea-811d-dbc1fa80fa99.png">

But I can't use any combinations of `.scale` and `.rotation`. Is there any programmatic solution or do I need to make a new texture?

Also, on an unrelated note - doing `entity.shake()` returns an error since `random` isn't imported in `entity.py`.

**Comment by pokepetter** [comment]
Set double_sided = True

**Comment by Innoviox** [comment]
Awesome, thanks!
