### ISSUE TITLE
How add walking animation to player in 3d game   ?

### ISSUE THREAD

**Issue by PremKumarMishra** [pokepetter/ursina#296]
Hello Pokepetter, Well i am not so pro in this engine but i was making a multiplayer game and i need a walking animation for my 3d player so that others players can see it  but i cant figure out how to do it?

**Comment by RedHenDev** [comment]
You can use the FrameAnimation3d() function, where you can pass in the name of, for instance, an .obj model file, which is the first in a sequence of model files representing the keyframes in an animation you have made in blender or blockbench etc.

Then, this function will automatically load in any other .obj files you have created with the same prefix (e.g. 'walk_animation_1.obj', 'walk_animation_2.obj', 'walk_animation_3.obj', '...').

E.g. 
`walking_character = FrameAnimation3d('walk_animation_')`

You can then control the animation by setting the fps: -

`walking_character.fps = 12`

And can pause and resume the animation with the following: -

```
def input(key):
      if key=='w':
              if walk_animation.is_playing:
                  walk_animatio.pause()
                  walk_animatio.is_playing=False
              else: 
                  walk_animatio.resume()
                  walk_animatio.is_playing=True
```

Well, that should give you the basics. A more developed system would lerp() or slerp() between keyframes by accessing the vertex lists on the mesh. But I haven't tried that myself, so probably not a good solution!

Good luck!
