### ISSUE TITLE
Viewport Turns black when mouse.locked is set to False in an update cycle

### ISSUE THREAD

**Issue by BiolessInteractive** [pokepetter/ursina#297]
Project Files:
[myGame.zip](https://github.com/pokepetter/ursina/files/7401685/myGame.zip)

**Comment by y2bad** [comment]
you create an entity called scene in your main file
but there is already an entity called scene used by ursina so you need to change the name to something different

**Comment by pokepetter** [comment]
Don't set mouse.locked in update
