### ISSUE TITLE
Partially transparent texture bug?

### ISSUE THREAD

**Issue by NitroxKnight** [pokepetter/ursina#3]
I'm working on a simple vertical shooter game to try some ideas. However, I have noticed that if a texture has a partially transparent part it will apply the background color again resulting in a weird frame effect. 

![image](https://user-images.githubusercontent.com/10372216/69906295-a3721500-13c1-11ea-92f2-f28679f940be.png)

isolated case:

![image](https://user-images.githubusercontent.com/10372216/69906436-89393680-13c3-11ea-8e98-dd449efe3f60.png)

Any way around this problem of partially transparent textures?

script to reproduce the showcase problem

```python
from ursina import *
from pathlib import Path

class Bullet(Entity):
    def __init__(self,texture=None,x=0.,y=0.):
        super().__init__()
        self.model = 'quad'
        self.texture = texture
        self.scale = 1/8
        self.x = x
        self.x = y

app = Ursina()
tex_bullet = Texture(Path('./bullet.png'))
b1 = Bullet(texture=tex_bullet)
b2 = Bullet(texture=tex_bullet,x=0.05,y=0.05)

camera.orthographic = True
camera.fov = 1
app.run()     
```
the texture I use: ./bullet.png:
![bullet](https://user-images.githubusercontent.com/10372216/69906424-6444c380-13c3-11ea-91f7-e4c70a484896.png)

**Comment by pokepetter** [comment]
Thank you for the feedback. I have fixed this in the newest commit by changing the default transparency mode.
