### ISSUE TITLE
Set background color of app

### ISSUE THREAD

**Issue by Innoviox** [pokepetter/ursina#30]
My app has a background color of #404040:

<img width="158" alt="Screen Shot 2020-03-08 at 1 48 56 PM" src="https://user-images.githubusercontent.com/21976953/76168186-a8bec880-6143-11ea-9e97-710b3c928e31.png">

How can I change this? Is it customizable?

**Comment by pokepetter** [comment]
You can set window.color

`window.color = color.black`
`window.color = color.color(210, .5, .8) # hsv color`
