### ISSUE TITLE
Could not open window Error

### ISSUE THREAD

**Issue by Abdouflih** [pokepetter/ursina#318]
im having a error when trying to launch a code
The Code : 
`from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController

app = Ursina()
class Voxel(Button):
    def __init__(self, position=(0,0,0)):
        super().__init__(
            parent = scene,
            position = position,
            model = 'cube',
            origin_y = .5,
            texture = 'white_cube',
            color = color.color(0, 0, random.uniform(.9, 1.0)),
            highlight_color = color.lime,
        )

    def input(self, key):
        if self.hovered:
            if key == 'left mouse down':
                voxel = Voxel(position=self.position + mouse.normal)

            if key == 'right mouse down':
                destroy(self)

for z in range(8):
    for x in range(8):
        voxel = Voxel(position=(x,0,z))

player = FirstPersonController()
app.run()`

Python Version : Python 3.8 32bit
Ersina Version : Latests one installed using -pip

**Comment by pokepetter** [comment]
What's the error?

**Comment by Abdouflih** [comment]
when i try to run the project i get an error saying ; expection : ('could not open window')

**Comment by Abdouflih** [comment]
erreur in terminal :
blender_paths:
{'default': WindowsPath('C:/Program Files/Blender Foundation/Blender/blender.exe')}
screen resolution: (1024, 768)
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
:display(error): The application requested harware acceleration, but your OpenGL
:display(error): driver, GDI Generic, only supports software rendering.
:display(error): You need to install a hardware-accelerated OpenGL driver, or,
:display(error): if you actually *want* to use a software renderer, then
:display(error): alter the hardware/software configuration in your Config.prc file.
:display(warning): Unable to load libtinydisplay.dll: Path not found
:display(warning): Unable to load libpandadx8.dll: Path not found
:display(warning): Unable to load libpandadx9.dll: Module not found
:ShowBase(warning): Unable to open 'onscreen' window.
Traceback (most recent call last):
  File "c:/Users/106/Documents/Projects/MyFirstGame.py", line 4, in <module>
    app = Ursina()
  File "C:\Users\106\AppData\Roaming\Python\Python38\site-packages\ursina\main.py", line 27, in __init__
    super().__init__()
  File "C:\Users\106\AppData\Roaming\Python\Python38\site-packages\direct\showbase\ShowBase.py",
line 339, in __init__
    self.openDefaultWindow(startDirect = False, props=props)
  File "C:\Users\106\AppData\Roaming\Python\Python38\site-packages\direct\showbase\ShowBase.py",
line 1021, in openDefaultWindow
    self.openMainWindow(*args, **kw)
  File "C:\Users\106\AppData\Roaming\Python\Python38\site-packages\direct\showbase\ShowBase.py",
line 1056, in openMainWindow
    self.openWindow(*args, **kw)
  File "C:\Users\106\AppData\Roaming\Python\Python38\site-packages\direct\showbase\ShowBase.py",
line 801, in openWindow
    raise Exception('Could not open window.')
Exception: Could not open window.

**Comment by pokepetter** [comment]
You need a GPU in your computer. And a driver for it.
