### ISSUE TITLE
get_mouse_position() not working

### ISSUE THREAD

**Issue by OkiStuff** [pokepetter/ursina#32]
So I'm trying to create a simple world editor using Ursina Engine, but when I looked on the documentation I couldn't find anything that would help me with the mouse position. I did already tried doing mouse.position, but the output wasn't an integer. And when I tried get_mouse_position() it wasn't there. So by any chance would you help me by either telling me if my code is wrong, or maybe showing me where in your code you have the Cursor() function or any other function that uses the position of the mouse. Thanks love your engine. `if held_keys['left mouse down']:
        player.x = mouse.position
    `

**Comment by pokepetter** [comment]
mouse.position returns position in ui space, see https://www.ursinaengine.org/coordinate_system.html

**Comment by pokepetter** [comment]
Now that I read this again, what I think you want is: `player.x = mouse.x`
