### ISSUE TITLE
When using 3D it doesn't work

### ISSUE THREAD

**Issue by yavda1** [pokepetter/ursina#322]
For an hour or so all was fine, it was working I could move and it could detect all keypresses however I left for a while came back and nothing was working. I could jump, but I couldn't move. Almost all the walls I created disappeared. I have tried uninstalling and reinstalling ursina however it doesn't work. Any idea why this is happening?

**Comment by pokepetter** [comment]
That's very vague. Can you be more specific?
Code doesn't actually rot, even if sometimes seems like it.

**Comment by yavda1** [comment]
Just look at this video:


Also here is the terminal output:

package_folder: /Users/yavda/Library/Python/3.9/lib/python/site-packages/ursina
asset_folder: .
OS: posix
screen resolution: (2240, 1260)
read obj at: cube.obj
Known pipe types:
  CocoaGraphicsPipe
(3 aux display modules not yet loaded.)
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
read obj at: wasp.obj
read obj at: gun.obj
info: development mode: True
application successfully started
:display:gsg:glgsg(error): An error occurred while compiling GLSL vertex shader created-shader:
ERROR: created-shader:1: '' :  version '130' is not supported
:display:gsg:glgsg(error): An error occurred while compiling GLSL fragment shader created-shader:
ERROR: created-shader:2: '' :  version '140' is not supported
info: changed aspect ratio: 1.778 -> 1.778

**Comment by pokepetter** [comment]
Seems like an issue with your code. Try creating a minimal reproducible example

**Comment by yavda1** [comment]
My code:

`from ursina import *
from random import uniform
from ursina.prefabs.first_person_controller import FirstPersonController

app = Ursina()

def input(key):
    if key == "left mouse down":
        for wasp in wasps:
            if wasp.hovered:
                destroy(wasp)  
class Wasp(Button):
    def __init__(self, x, y, z):
        super().__init__(parent = scene, model = "wasp.obj", scale = .1, position = (x, y, z), rotation = (0, 90, 0), collider = "box")
        
class Spider(Button):
    def __init__(self, x, y, z):
        super().__init__(parent = scene, model = "spider.obj", scale = .02, position = (x, y, z), rotation = (0, 90, 0), collider = "box")


Sky()

player = FirstPersonController(y = 2, origin_y =-.5)
ground = Entity(model = "plane", scale=(100, 1, 100), color = color.lime, texture = "white_cube", texture_scale = (100,100), collider = "box")
wall_1 = Entity(model = "cube", collider = "box", position = (-8, 0, 0), scale = (8, 5 ,1), rotation = (0,0,0), texture = "brick", texture_scale = (5, 5), color = color.rgb(255, 128, 0))
wall_2 = duplicate(wall_1, z=5)
wall_3 = duplicate(wall_1, z=10)
wall_4 = Entity(model = "cube", collider = "box", position = (-15, 0, 10), scale = (1, 5, 20), rotation = (0,0,0), texture = "brick", texture_scale = (5, 5), color = color.rgb(255, 128, 0))
num = 6

wasps = [None]*num
for i in range(num):
    wx = uniform(-12, -7)
    wy = uniform(.1, 1.8)
    wz = uniform(.8, 3.8)
    wasps[i] = Wasp(wx, wy, wz)
    wasps[i].animate_x(wx+.5, duration = .2, loop = True) 


gun = Entity(model = "gun.obj", parent = camera.ui, scale = .08, color = color.gold, position = (.3, -.2), rotation = (-5, -10, -10))
app.run()`

**Comment by RedHenDev** [comment]
Probably not your issue, but what's this line doing?

`wasps = [None]*num`

Why the *num? Or indeed the [None] ? Why not just wasps=[] ?

Apologies -- this is probably just my ignorance of a technique you're using here that I just haven't seen before!

**Comment by yavda1** [comment]
This chain explain's it pretty well: https://stackoverflow.com/questions/58777374/what-does-none-means-in-python

**Comment by RedHenDev** [comment]
Ahhhh, thank you.

And does populating the list from the beginning like this improve for efficiency, or does it achieve something else?

Thanks again for the link -- really helpful.
