### ISSUE TITLE
render not defined when using class FirstPersonController()

### ISSUE THREAD

**Issue by beggainer-crypto** [pokepetter/ursina#323]
I am getting this **error**:
`package_folder: C:\Users\mayan\AppData\Local\Programs\Python\Python39\lib\site-packages\ursina
asset_folder: c:\Users\mayan\Desktop\Programing\My Games\3D-GameController
screen resolution: (1366, 768)
Traceback (most recent call last):
  File "c:\Users\mayan\Desktop\Programing\My Games\3D-GameController\MINICRAFT.py", line 23, in <module>
    player = FirstPersonController()
  File "C:\Users\mayan\AppData\Local\Programs\Python\Python39\lib\site-packages\ursina\prefabs\first_person_controller.py", line 32, in __init__
    ray = raycast(self.world_position+(0,self.height,0), self.down, ignore=(self,))
  File "C:\Users\mayan\AppData\Local\Programs\Python\Python39\lib\site-packages\ursina\entity.py", line 425, in world_position
    return Vec3(self.get_position(render))
NameError: name 'render' is not defined`

while using this *limited* **code**

`player = FirstPersonController()`
`app = Ursina()`
`app.run()`

I checked into the *issue* through the pointer that vs-code gives me which is the `entity.py` on line *425* and on that line, I see this line of code: 
`return Vec3(self.get_position(render))`

on even further investigation I found out that there was actually no variable/object named *render*, not even on the imports or not even misspelled anywhere.

so yeah my trail ends and it is up to **you** (whoever reads this ) to please help me figure this out, I really like this concept of ursina created by @pokepetter , where it is simple and easy to grasp but has a super-powerful 3d engine

**Comment by pokepetter** [comment]
Python code runs from top to bottom, so make sure you create Ursina() before the FirstPersonController since it depends on the 3d space existing.

**Comment by beggainer-crypto** [comment]
> Python code runs from top to bottom, so make sure you create Ursina() before the FirstPersonController since it depends on the 3d space existing.

thank you so much, appreciate the help : )
