### ISSUE TITLE
Issue with FPC

### ISSUE THREAD

**Issue by vismodo** [pokepetter/ursina#326]
I'll keep this short. When using Ursina's `FirstPersonController`, if I move the mouse too fast, the cursor escapes the game window and you need to bring the cursor back into the window for the FPC to work.

**Comment by RedHenDev** [comment]
Could you set window to fullscreen? (Not a real solution, sorry, but not sure if you're aware that you could do this?)

window.fulscreen=True

Or -- decrease mouse velocity? See https://www.ursinaengine.org/cheat_sheet_dark.html#mouse

Or -- reset the mouse's position if outside of window?

Interested if any of those work for you, buddy!

**Comment by y2bad** [comment]
what os are you using?

**Comment by pokepetter** [comment]
Should be fixed now.
