### ISSUE TITLE
Inventory Tutorial:  Step 11 Stay inside the inventory doesn't work

### ISSUE THREAD

**Issue by shreyasrawat** [pokepetter/ursina#338]
The following code doesn't work in the inventory tutorial at step 11.

```
    '''if outside, return to original position'''               
    if icon.x < 0 or icon.x >= 1 or icon.y > 0 or icon.y <= -1: 
                icon.position = (icon.org_pos)                          
                return 
```
The following condition works for me:
```
 if icon.x < 0 or icon.x > 4 or icon.y > 0 or icon.y < -7:
                icon.position = (icon.org_pos)                          
                return
```

**Comment by shreyasrawat** [comment]
It doesn't work when I am following [Inventory Tutorial](https://www.ursinaengine.org/inventory_tutorial.html)  step by step but it does work when I am running **inventory.py** from **ursina/samples/**. 
So I am not sure what is going on.

**Comment by y2bad** [comment]
I think it's a typo because in the tutorial it's:
'''if outside, return to original position''' 
but on the githubpage it's:
#if outside, return to original position
