### ISSUE TITLE
Ursina for dummies

### ISSUE THREAD

**Issue by Spritekin** [pokepetter/ursina#34]
Hi,

I wrote this for my son but also tried to make it so that it might be used by other people trying to learn the engine. This is completely draft but I have tested each step and verified working. Please read and add to your code base, maybe format it a bit.

Regards,
Guimo

[ursina_for_dummiestxt.txt](https://github.com/pokepetter/ursina/files/4485227/ursina_for_dummiestxt.txt)

**Comment by ZeroCool940711** [comment]
Hey @Spritekin nice tutorial for people starting with Ursina. I would like to ask you if you could convert/adapt a script to run on Ursina, it is a small but powerful [Dungeon Generator](https://gitlab.com/Procedural-Generation/DungeonGenerator), I tried to make it run with Ursina but failed, I was having troubles placing the tiles on the terrain on the right coordinates, also was having troubles with the textures. If you could make it work with Ursina this could be an example of how to do procedural terrain generation on Ursina and also work as an example of a top-down 2d game. We do not have enough examples of how to do stuff on Ursina. The Dungeon Generator wasn't made by me but so far I think it's the only procedural dungeon generator in Python out there, at least the only one that doesn't depend on a specific engine or library, most of the code uses only the built-in python libraries, there is a lot of information on the repository, the code and also there's a link for the original post from where I took the script, if you have any questions or don't know how something on the generator works just let me know. Really hope you can make that work on Ursina as I want to do some stuff with that generator and Ursina but I'm currently stuck.

**Comment by pokepetter** [comment]
Looks great! I'll add it to the website as soon a possible!
Also I'm impressed you figured out the texture scrolling. I noticed it's not in the documentation :P

**Comment by Spritekin** [comment]
@ZeroCool940711 Let me check and see if I can do it.

@pokepetter Grad you like it! I haven't done game development for a while but I can say your project caught my eye and decided to dust my skills a bit and at the same time try and get my son interested. I plan to start a second chapter on this focusing on how to create a start menu, get to a game then an end game menu.
 
I feel what this engine needs is a bit more work on the UI (i.e. standardised x-y coords) and more controls.
 
Let me see how I can help. I got limited time but I will try to help here and there.

Luck!

Meanwhile, please use this new version of the tutorial, I did a reread and is now slightly cleaned up.
[ursina_for_dummies.txt](https://github.com/pokepetter/ursina/files/4490198/ursina_for_dummies.txt)

**Comment by Spritekin** [comment]
@ZeroCool940711 There is a dungeon-generator library in python, will use that one instead. Will create another issue to discuss.

**Comment by allamvignesh2004** [comment]
Hey to use parent please explain
