### ISSUE TITLE
Bug: ursina.build copies my entire /usr/bin and complains of a non-existent /usr/bin/Lib

### ISSUE THREAD

**Issue by majorendian** [pokepetter/ursina#340]
Title explains it.
See pic.
Code:
```
from ursina import *

game = Ursina()

ground = Entity(
	model = "cube",
	color = color.magenta,
	z = - .1,
	y = - .1,
	origin = (0,0),
	scale = (1,1,10),
	collider = 'box'
)

def update():
	ground.x += held_keys["d"] * .1
	ground.x -= held_keys["a"] * .1

game.run()
```
![Screenshot at 2022-01-20 00-59-30](https://user-images.githubusercontent.com/11798362/150238145-35dd7e4f-2f41-495c-b8bc-0876eccc8650.png)

Command I ran: `python -m ursina.build`

**Comment by pokepetter** [comment]
It's only for windows at the moment

**Comment by majorendian** [comment]
Ok good to know.

**Comment by majorendian** [comment]
On a side note, I don't remember encountering a python based program that was windows exclusive. May I know why that is?

**Comment by pokepetter** [comment]
It's not, just the packaging script. There are other modules you can use too to package an application
