### ISSUE TITLE
Sometimes ursina aspect ratio bugs and randomly changes

### ISSUE THREAD

**Issue by csd4ni3l** [pokepetter/ursina#344]
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
info: changed aspect ratio: 1.333 -> 1.778
info: changed aspect ratio: 1.778 -> 1.333
this is in the console i don't know why but its changing its size sometimes randomly and its annoying because i have to close the program and rerun it

**Comment by y2bad** [comment]
this is a bug from ursina. in the newest version on github it should be fixed

**Comment by csd4ni3l** [comment]
Please fix this soon because its so irritating

**Comment by pokepetter** [comment]
Can't reproduce it. Works fine here.

**Comment by csd4ni3l** [comment]
idk why but the window always wants to be 1.333 windowed_size if its not the its glitchy and if i say 1250 750 window size then in the console:
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333
info: changed aspect ratio: 1.333 -> 1.667
info: changed aspect ratio: 1.667 -> 1.333

**Comment by csd4ni3l** [comment]
i solved it if i do the window.size = (1250,750) in the update function it works
