### ISSUE TITLE
Textures are looking weird

### ISSUE THREAD

**Issue by Advik-B** [pokepetter/ursina#347]
I cant exactly pinpoint what does it. but the textures are giving me a headache if i look at it for a while
and no, the textures are 4k and very good

| Keybind | Texture |Image|
|:--------------:|:-----------:|:----------:|
| 1 | white_cube | ![img](https://raw.githubusercontent.com/pokepetter/ursina/master/ursina/textures/white_cube.png) |
| 2 | crate | ![crate](https://user-images.githubusercontent.com/86160411/150798628-1d14f15b-c0b1-466d-b55a-bdb3e3f5529d.jpg) |
| 3 | grass |  ![grass1](https://user-images.githubusercontent.com/86160411/150798819-4a1f6061-290a-439e-a5a8-0a6be2e5240b.jpg) |
| 4 | ground | ![ground](https://user-images.githubusercontent.com/86160411/150799103-d4c56f03-28fd-46bd-95a7-f61f677bd484.jpg) |
| 5 | seamless_wood| [big image (click to load) ](http://memefileserver.ml/uploaded/seamless_wood.jpg)|
| 6 | stone_wall | [big image (click to load) ](http://memefileserver.ml/uploaded/stone_wall.jpg)
| 7 | water | ![water](https://user-images.githubusercontent.com/86160411/150799863-f6f2f42d-82a0-4993-a384-21e20c5c83c6.jpg) |

I have provided an example [here (click to download)](http://memefileserver.ml/uploaded/Error%20example.zip) (the files size is big because it also has a venv)
double click on run_game.bat

### __main__.py
```py
from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController

root = Ursina()
player = FirstPersonController()

print('Texture')
print('1: white_cube\n2: crate\n3: grass1\n4: ground\n5: seamless_wood\n6: stone_wall\n7: water')

def quit_game():
    sys.exit(0)

ground = Entity(
    model='cube',
    scale=3,
    texture='white_cube',
    y=-3.55,
    collider='box',
    )

def update():
    global ground, info
    if held_keys['r']:
        player.position = (0,0,0)
        
    if held_keys['escape']:
        quit_game()
        
    if held_keys['1']:
        ground.texture = 'white_cube'
    if held_keys['2']:
        ground.texture = 'crate'
    if held_keys['3']:
        ground.texture = 'grass1'
    if held_keys['4']:
        ground.texture = 'ground'
    if held_keys['5']:
        ground.texture = 'seamless_wood'
    if held_keys['6']:
        ground.texture = 'stone_wall'
    if held_keys['7']:
        ground.texture = 'water'

root.run()
```
### run_game.bat
```bat
game-runtime\Scripts\python.exe .
```

**Comment by pokepetter** [comment]
Download doesn't work. Don't you have a screenshot?

**Comment by Advik-B** [comment]
@pokepetter 
![image](https://user-images.githubusercontent.com/86160411/151117465-d0c66f18-65e8-4c8c-a571-9384bacc60e4.png)

**Comment by pokepetter** [comment]
?
