### ISSUE TITLE
how can I set a background texture?

### ISSUE THREAD

**Issue by ellaw00** [pokepetter/ursina#352]
how can i set a background texture of the window?

**Comment by RedHenDev** [comment]
```
bg=Entity(model='quad',texture='my_texture',z=camera.clip_plane_far)
bg.scale=camera.clip_plane_far
bg.parent=camera
```

So, this just places a quad in the scene and moves it as far back as possible, scales it up accordingly, and parents to camera so that it appears in front of you at all times (e.g. with player controller or editor camera).

Good luck!
