### ISSUE TITLE
First Person Controller is not working in Linux as it is working in windows

### ISSUE THREAD

**Issue by yegender124001** [pokepetter/ursina#356]
I don't know why it did not working. It looks like and mouse inputs are also not working well.
![level  1_001](https://user-images.githubusercontent.com/57976250/151797575-40aa78dd-8bbe-4076-aaea-0beef5e8f808.png)

My Code:
`from tkinter import Scale
from turtle import position
from numpy import place
from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController

app = Ursina()

background_sound = Audio(sound_file_name='audio/ingame.mp3',autoplay=True,loop=True)
background_sound.volume = 100

ground = Entity(
    model = 'plane',
    texture = 'textures/grass.jpg',
    position = (0,0,0),
    rotation_y = 90,
    collider = 'mesh',
    scale = (100,1,100),
    texture_scale=(10,10)
)

player = FirstPersonController()
player.mouse_sensitivity = Vec2(40,40)

app.run()`

**Comment by y2bad** [comment]
i had this issue earlier maybe try to put `window.borderless = False` somewhere in your code
or install the newest version of ursina with `pip install git+https://github.com/pokepetter/ursina.git -U`
