### ISSUE TITLE
Transparent gif?

### ISSUE THREAD

**Issue by LORD-ME-CODE** [pokepetter/ursina#357]
How can I load transparent gif in Animation? I tried to set a transparent color, but in the end the gif disappeared.

**Comment by Sheepeto** [comment]
Load the animation normally first then print each of the color values then change it accordingly 
Example: var = Animation("Gif File", parent=entity/camera.ui, color=color.rgba(1.0, 1.0, 1.0, 0.5))

**Comment by LORD-ME-CODE** [comment]
![image](https://user-images.githubusercontent.com/83734728/152681071-bf40c726-cf09-4666-9011-eb81b2743ac3.png)
I get this

**Comment by LORD-ME-CODE** [comment]
> Load the animation normally first then print each of the color values then change it accordingly Example: var = Animation("Gif File", parent=camera.ui, color=color.rgba(1.0, 1.0, 1.0, 0.5))

![image](https://user-images.githubusercontent.com/83734728/152681444-1ec42469-23dd-4f81-bb96-e58cc508f605.png)
I get this

**Comment by Tech-Helper503** [comment]
Gifs are working. Maybe something wrong with your ursina or Python installation?
