### ISSUE TITLE
Shaders

### ISSUE THREAD

**Issue by Spritekin** [pokepetter/ursina#36]
Life is much more interesting with shaders. I will now go and make a small demo with shaders. 
This might be hard because I can't remember my shader math and I only used DirectX HLSL years ago and I see ursina uses some kind of python-GLSL hybrid. Lets see.

**Comment by Spritekin** [comment]
Ah I see it now, its GLSL loaded using python. I can work with this.

**Comment by Stihotvor** [comment]
What is this issue about? Why are You flooding here?

**Comment by Spritekin** [comment]
@Stihotvor 
Hi, I was planning to create a demo or tutorial similar to the other two I have submitted in other threads... but to be honest I got other things in life for now and could not continue. So close this thread if you want.
