### ISSUE TITLE
Bypass "ursina" default window

### ISSUE THREAD

**Issue by ShadityZ** [pokepetter/ursina#363]
When running an app using ursina, you get a loading type screen that is black and has the title ```ursina```. I find this a bit annoying. Is there a way to bypass this?

**Comment by y2bad** [comment]
if you want to change the title use `window.title = 'your title'`

**Comment by RedHenDev** [comment]
Do you mean the splashscreen?

You can disable like so: -

`window.show_ursina_splash=False`

**Comment by pokepetter** [comment]
None of these work, but I'll make an update soon, making window.title work like this.

**Comment by ShadityZ** [comment]
Thank pokepetter!

**Comment by ShadityZ** [comment]
No @RedHenDev , I meant when you run a large application, you get this black window that has the title "ursina" and it stays there until the rest of the game loads. Is there any way to eliminate or hide the window until the game loads?

**Comment by RedHenDev** [comment]
@ShadityZ Oh, I see! -- apologies. Looks like next update will be sorted.

**Comment by ShadityZ** [comment]
When will this update be coming out?

**Comment by pokepetter** [comment]
5 days ago

**Comment by pokepetter** [comment]
If you want to shorten the time it takes to open, you should either make it load faster in the first place or just load something like a loading screen or start menu and load the rest later.

**Comment by ShadityZ** [comment]
Thanks for the advice! Do I have to clone the git repository and install that, instead of using PyPi?

**Comment by y2bad** [comment]
you can use folliwing command `pip install git+https://github.com/pokepetter/ursina.git -U`

**Comment by ShadityZ** [comment]
That worked, Thanks!

**Comment by ShadityZ** [comment]
I'm closing this issue now...
