### ISSUE TITLE
PlatformerController2d disappearing when moving left

### ISSUE THREAD

**Issue by LGG6-Master** [pokepetter/ursina#365]
I only have the controller and a box in my code but when I move left, the player disappears

**Comment by pokepetter** [comment]
Code?

**Comment by LGG6-Master** [comment]
`from ursina import *
from ursina.prefabs.platformer_controller_2d import PlatformerController2d

app = Ursina(borderless = False)
window.title = "T-T-T"
camera.orthographic = True
camera.fov = 1

ground = Entity(model = "quad", color = color.green, position = (0, -0.4), scale = (2, 0.2), collider = "box")
player = PlatformerController2d(model = "quad", color = color.blue, scale = (0.05, 0.05), position = (0, -0.2), walk_speed = 0.5, jump_height = 0.2, jump_duration = 0.05, gravity = 0.25)

app.run()`

**Comment by pokepetter** [comment]
You changed the model to a quad. A quad is only visible from one side. In fact all 3d models are only visible from one side unless you set double_sided = True.

**Comment by LGG6-Master** [comment]
thanks :D
