### ISSUE TITLE
Compile to web or android

### ISSUE THREAD

**Issue by ElectriCherph** [pokepetter/ursina#372]
Is there a way I could compile a ursina program to android or the web?

**Comment by ShadityZ** [comment]
Maybe you could check out [python-for-android](https://github.com/kivy/python-for-android)? For the web, you could use the [Flask framework](https://flask.palletsprojects.com/en/2.0.x/). I'm not so sure how you could get ursina working with it. I'll do some more research and get back to you.

**Comment by deangelisdf** [comment]
Try to give a look on https://github.com/panda3d/panda3d#android
