### ISSUE TITLE
Is there a way to use OpenStreetMap with real GPS data and show a 2D minimap in ursina?

### ISSUE THREAD

**Issue by SuperMarioSF** [pokepetter/ursina#374]
I'm currently working on a AR HUD software using ursina. I'm planning to add a minimap feature, and I have no idea how to implement this. (I am a new user to ursina btw)

If there is any kind of browser as a ursina object can run HTML5 code, then all problem solved, however this isn't a good way to done that. I searched and find there are some way to let Panda3D use OpenStreetMap, however I haven't find much information about how to do that, it just says you can do this, but not how.

Any ideas?
Thanks.

* * *
by the way, currently my AR HUD software has those things working right now:
1. External IMU sensor to control ursina's 3D player camera ([sensor data converted from serial](https://github.com/SuperMarioSF/IMU901ComServer))
2. Music player track event listener

**Comment by ShadityZ** [comment]
I don't do this kind of stuff often, so I'm not so familiar with the interface, but is there a way to get an image for the 2D minimal? I could help you from there.

**Comment by SuperMarioSF** [comment]
Just looked into this again, and I found some python based renderer for OpenStreetMap, however they may need to be heavily modified to work with ursina, and they weren't provide any geolocation functions, only map rendering.

So maybe I have to write some kind of navigation software first. Maybe Ursina is a good way to make some applications?

**Comment by pokepetter** [comment]
This seems like a big project and is out of scope for ursina issues, which is intended for reporting issues with using itself, like bugs.
