### ISSUE TITLE
Forking Ursina

### ISSUE THREAD

**Issue by ShadityZ** [pokepetter/ursina#381]
Hi, I'm making an FPS videogame in python called [Vitrix](https://github.com/ShadityZ/Vitrix).
I am planning to make a seperate folder in the source tree for the engine. I also plan to make a few edits for some bug fixes and extra classes. I was wondering how the forking process would work.
I don't know about every part of the licence system, so I'm unsure how to proceed with this.
Any guidance is appreciated.

**Comment by pokepetter** [comment]
I think you can simply git clone it and do the changes you want. Forking is not necessary, but useful of you want to pull request changes to the official repo. If you want updates, you can simply git fetch and merge.

 To install your custom version you can use `python setup.py develop` or have it in your project as you suggested.

**Comment by ShadityZ** [comment]
Yes. Thank you for your help, but are there any certain rules I need to follow doing this, with the MIT licence and all? Vitrix is open source I'd like to point out.
