### ISSUE TITLE
texture issue

### ISSUE THREAD

**Issue by RedsField** [pokepetter/ursina#382]
hello, currently im making a simple 2d game with ursina, but i want to put a texture on the base cube that comes with the platformercontroller2d, but my texture is applied to all the faces of the cube, and when i change to a quad, the colliders have trouble, so i wanted to know i there is a way to put the texture only in 1 face of the cube, only the face we are facing.
thanks,
RedsField

**Comment by ShadityZ** [comment]
I think [this](https://github.com/pokepetter/ursina/issues/44) issue might be useful, it's for a 3D game, but it shouldn't be too hard to get it to work with platformcontroller2d. If you need further help, please send over the code.
