### ISSUE TITLE
Text position incorrect when origin is set

### ISSUE THREAD

**Issue by carlsonmark** [pokepetter/ursina#39]
When the Text class's origin is set, the text is no longer aligned correctly, and the background is not lined up with the text.
```
text_box = Text(
    z=-999,
    eternal=True,
    origin=(-1, 1),
    color=color.red.tint(-.2),
    text=text)
```
Bug?
![Screenshot from 2020-05-09 14-02-36](https://user-images.githubusercontent.com/7170924/81483765-db497800-91fd-11ea-9629-278ed10aaac0.png)

What I expect:
![Screenshot from 2020-05-09 14-03-03](https://user-images.githubusercontent.com/7170924/81483776-e6040d00-91fd-11ea-9fbe-c446a3eeca8b.png)

I have a potential fix and will create a PR

**Comment by pokepetter** [comment]
No, it's supposed to go from -0.5 to 0.5, not -1 to 1, just like when setting Entity origin.

**Comment by carlsonmark** [comment]
Ah, my mistake, sorry!
