### ISSUE TITLE
Use tkinter with Ursina

### ISSUE THREAD

**Issue by parthrangarajan** [pokepetter/ursina#393]
Hey, I want to open a `Tkinter` window when there is a collision with an Entity in Ursina. 
However, I am getting this error:  `_tkinter.TclError: can't invoke "label" command: application has been destroyed`

I am using `root.destroy()` to shut my `Tkinter` application once its functionality has been served and then continue with the Ursina game as usual. 

Could someone help me out with this problem? What I think is happening is that in the `root.destroy()` command from `Tkinter` is conflicting with the `app.destroy()` function present in Ursina (as my Ursina code is contained in a variable `app`). 

Thanks in advance.

**Comment by Genius1512** [comment]
Could you share the part of the code?

**Comment by parthrangarajan** [comment]
Yes definitely. This is the code that calls the tikinter module from a different python file. 
```
def calling_quiz():
    from PlantRunnerQuiz import PlantRunnerQuiz as PRQ
    quiz = PRQ()
```
    
I am using it in this set of code the above function here:
```
for cube in cubes:
    cube.z -= time.dt * 4
    cube.rotation_y +=time.dt * 15

    if abs(finoman.x - cube.x) < 0.3:
        if abs(finoman.z - cube.z) < 0.06:
            put tkinter in a function and call function here
            calling_quiz() 
```

**Comment by Genius1512** [comment]
Sorry, I can't help you. I thought you maybe screwed up some of the naming, but this is fine.

**Comment by parthrangarajan** [comment]
I found it. 
It was because I was creating an object of the class in `quiz = PRQ()` which was initiating the module another time thus causing it to crash. 
Thanks for your help anyways man. I really appreciate it.

**Comment by parthrangarajan** [comment]
Hi, I am unable to open the Tkinter window every time there is a crash with the entity. I am able to open the window only once when there is the first crash. Post the first crash, it is unable to open the window.

Please provide me with some guidance on this. 
Thank you in advance.

**Comment by SamMatzko** [comment]
@parthrangarajan It's very often the case that using two different GUI modules in the same Python program results in a crash (it can happen when using Pygame and `tkinter` as well). You'll probably have to be more specific; what error messages are you getting?
