### ISSUE TITLE
a typo

### ISSUE THREAD

**Issue by liux-pro** [pokepetter/ursina#394]
![image](https://user-images.githubusercontent.com/20764978/160163987-0f5f9344-c40a-4460-8146-87af1e1afe82.png)

**Comment by liux-pro** [comment]
https://github.com/pokepetter/ursina/blob/df7ba92f28d7419027cfa8158dd3f43b18ab8a82/docs/index.txt#L73

**Comment by ShadityZ** [comment]
Maybe you could create a fork of Ursina, fix the typo and create a [PR](https://github.com/pokepetter/ursina/pulls)

**Comment by y2bad** [comment]
the typo is already fixed
