### ISSUE TITLE
how to generate mp4 video if I using ursina to create 3D animation movie?

### ISSUE THREAD

**Issue by ruanjiyang** [pokepetter/ursina#399]
Dear pokepetter

how to generate mp4 video if I using ursina to create 3D animation movie?

thanks lot!

**Comment by Chateauvisionn** [comment]
VideoRecorder should work (low fps and gif only)

**Comment by pokepetter** [comment]
The VideoRecorder supports .mp4 now (requires ffmpeg). It will also halt the game to wait for the recording. This means it won't skip frames and you can record smooth gameplay footage even if lags while recording.
