### ISSUE TITLE
ModuleNotFoundError: No module named '_socket'

### ISSUE THREAD

**Issue by ShadityZ** [pokepetter/ursina#406]
When compiling using ```ursina.build```, I get the error in the title when running my application.

I do indeed use the ```socket``` module, but it says that the socket module tried to import the module in the error. 

I am very confused. Please help.

I have searched many things on google, but the only results i get say that the sys.path is incorrect, but I have no idea how this is relevent to the portable python app inside the build

**Comment by pokepetter** [comment]
Tell the build script to include it.

**Comment by ShadityZ** [comment]
I have tried such, however it has not worked. I am trying to figure out why.

**Comment by ShadityZ** [comment]
It seems that the ```_socket``` is an extension module in the forms of a ```.pyd``` file. I'm looking into fixing it.

**Comment by ShadityZ** [comment]
Ended up using WinPython
