### ISSUE TITLE
Ursina doesn't load .mtl files!

### ISSUE THREAD

**Issue by ShadityZ** [pokepetter/ursina#412]
I have a bit of texture and colouring stored in my .mtl file, however on importing the model to the Entity, it doesn't load the .mtl, and leaves the model black. I have tried not including the .obj extension and renamed the .mtl to the same name as the .obj, but it still doesn't work. Scrolling through Ursina's code, I haven't found something that indicates that either. Does anybody know why or how to import the .mtl?

**Comment by pokepetter** [comment]
It does use .mtl to load material colors into vertex colors, so they do load. It does, however, not load textures. I find it kind of silly to have a separate file just containing the name of the texture. I you really need this feature and really don't want to load it normally, I'm sure you could add this functionality yourself. Just open the mtl file and get the name of the texture.

**Comment by ShadityZ** [comment]
Hmmm. Okay, I have this in my .mtl:
```
newmtl Black
Ns 225.000000
Ka 1.000000 1.000000 1.000000
Kd 0.020000 0.020000 0.020000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2

newmtl Wood_Brown
Ns 225.000000
Ka 1.000000 1.000000 1.000000
Kd 0.548852 0.093832 0.000000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2
```
How come this doesn't work? It is a material colour. Am I doing something wrong?

**Comment by pokepetter** [comment]
Not sure. Are you using an up to date version of ursina from GitHub?

**Comment by ShadityZ** [comment]
No, I'm using 4.1.1 from the PyPi repo, (default pip install) is this a problem?

**Comment by pokepetter** [comment]
Yes, get it from github. It has a lot of fixes and I'd like not to get bug reports about things that's already been fixed or implemented.

**Comment by Chateauvisionn** [comment]
I'm using the github version, i have obj, mtl and textures in the same folder but it still doesn't work

**Comment by pokepetter** [comment]
Please read my first answer
