### ISSUE TITLE
Slight error

### ISSUE THREAD

**Issue by MishaDobrynin** [pokepetter/ursina#416]
Hello! This isn't really anything major, I just wanted to find out how raycast function works. Also, when I'm using PyCharm on python 3.10 virtual env, pycharm is giving me an error for the raycast function. Could you please clarify?

**Comment by y2bad** [comment]
what is the error you get?

**Comment by pokepetter** [comment]
There's no error. Since Python is dynamic, things can change at runtime. Therefore, your linter will sometimes think something is incorrect when it is in fact correct.
