### ISSUE TITLE
How to disable PlatformerController2d double jump?

### ISSUE THREAD

**Issue by Sheepeto** [pokepetter/ursina#420]
Is there a way to disable the double jumping ability of the platformercontroller2d
or would i just have to make my own one?

**Comment by pokepetter** [comment]
It has double jump?

**Comment by Sheepeto** [comment]
yes it does

https://user-images.githubusercontent.com/53502671/168420844-ae462947-3d61-45f1-81f5-f01d79dc37ee.mp4

**Comment by ShadityZ** [comment]
I can't replicate it. Are you using the vanilla PlatformerController2d, or are you using a modified one?
