### ISSUE TITLE
i went beyond 1000000000000000meters in my own game powered by ursina and heres the results

### ISSUE THREAD

**Issue by x17db19** [pokepetter/ursina#421]
coordinates displayed 1e+15
also my game has infinite generating world and every single entity beyond the 1e+15 limit were effected by a Vibration effect of some sort.
i went further and then the coordinates stopped displaying and then the game crashed. i have one screenshot of this unknown limit
in the following image voxels generating in the indescribable way
![XDDD](https://user-images.githubusercontent.com/106544970/171221280-440100e6-08e9-4393-8261-f8d31e885586.png)

 can anyone explain?
PS: coordinates are displayed in the python shell by pressing the "r" key

**Comment by 28klotlucas2** [comment]
Are the positions floats or intigers?

**Comment by epsseniyer** [comment]
Youre out of double limit
