### ISSUE TITLE
Ursina doens't work under Wayland

### ISSUE THREAD

**Issue by vitor9090** [pokepetter/ursina#423]
Ursina doens't work on Wayland because of an error in line 47 of window.py, the error states that the command "xrandr" doens't exist that's because the xrandr command only work in X11 systems.

**Comment by pokepetter** [comment]
How can I get the monitor's resolution from Wayland?

**Comment by vitor9090** [comment]
I couldn't find a way without installing a library, the best library i know for that is "screeninfo".
