### ISSUE TITLE
Shaders are applied to text, making it impossible to change their color to anything but black

### ISSUE THREAD

**Issue by ShadityZ** [pokepetter/ursina#431]
I found when activating any form of shaders:
```python
Entity.default_shader = basic_lighting_shader
sun = DirectionalLight()
sun.look_at(Vec3(1,-1,-1))
```
Because the text is on a 2D plain, the shaders don't know how to handle it, so it makes all text black. This makes it so changing the text color has no effect whatsoever. It has been a very annoying issue for me, as I like my games looking fancy. 

I have found a solution which is as simple as adding a line to the ```Text()``` entity's ```__init__()``` function:
```python
self.shader = None
```

This has been an issue that has been bugging me for a while, and I would love to see it fixed in the official Ursina repository, so I hope that you accept it.

Thanks, 
ShadityZ

**Comment by pokepetter** [comment]
Fixed.
