### ISSUE TITLE
Ursina "double_sided" argument not working

### ISSUE THREAD

**Issue by Spiceinajar** [pokepetter/ursina#432]
I tried to set my game's sky "double_sided" argument to false, but nothing changed.

`Sky(texture="texture.png", double_sided=False)`

help?

**Comment by pokepetter** [comment]
The default is for double_sided to be False, so it doesn't do anything.
What did you expect to happen?

**Comment by Spiceinajar** [comment]
@pokepetter well double sided makes the texture the same on the top and bottom instead of applying it normally, right? So I was expecting it to get rid of it.
