### ISSUE TITLE
Getting errors in compiled python exe that im not getting when running the .py file (ursina/panda3d)

### ISSUE THREAD

**Issue by Spiceinajar** [pokepetter/ursina#433]
I have an ursina project that runs just fine normally, but then I compiled it to exe using pyinstaller and got this error:
![Screenshot (19)](https://user-images.githubusercontent.com/89741444/174080724-fe5af268-6e8b-486f-9a79-e1c4cdeca4b8.png)
Could somebody please explain it? Thanks.

**Comment by pokepetter** [comment]
https://www.ursinaengine.org/building.html

**Comment by Spiceinajar** [comment]
@pokepetter Thanks, very helpful! :)
