### ISSUE TITLE
Ursina should use __slots__ for things like Entity() to improve performance

### ISSUE THREAD

**Issue by spidertyler2005** [pokepetter/ursina#434]
[Here is a good tutorial that explains it](https://www.youtube.com/watch?v=Fot3_9eDmOs)

If I remember correctly, it stops python from internally using a dict to represent classes. This improves performance.

Dicts can be slow and this is an extremely easy fix that can be applied to many classes. `Entity` is probably a good one to start with.

**Comment by pokepetter** [comment]
Won't work. Not only does a lot of variables not exist until you set them, you also can't set arbitrary variables if you use slots. I've used __slots__ in HitInfo, conversation.Node and CubicBezier where we know all possible members beforehand. Are there any other classes you think it could work with?

**Comment by spidertyler2005** [comment]
Ah, thanks for the answer. I didn't notice you were already using it. My bad. I'll continue the thread if I see anything today, otherwise I will close it.
