### ISSUE TITLE
Guide on how to texture an object

### ISSUE THREAD

**Issue by famecastle** [pokepetter/ursina#44]
This game engine is amazing! Unfortunately, especially to those not so experienced with 3d modelling / game development in general, it's quite hard to understand how to apply textures to the models.

A guide on that would be great. Just two examples which I don't know how to realize:

- I have a cube entity. The default one. How can I create a cube map texture (so not the same texture for every side of the cube) for it through the official Ursina engine? What does my texture need to look like? What methods do I need to call? Maybe I would like to texture your Minecraft code sample.

- I have modelled some basic stuff in blender. Let's say it's a low-poly car. I just switched to edit mode, pulled around some corners and then exported to a .obj file. How would I texture that one? Would I have to apply textures in Blender and somehow export them? I'm lost.

Thank you for your great work so far!

**Comment by pokepetter** [comment]
You should look up uv mapping. Here's an explanation: https://www.youtube.com/watch?v=scPSP_U858k

**Comment by famecastle** [comment]
Thanks, I indeed looked up UV unmapping. I'm just unsure about how to make that work in Ursina. Let's just assume that basic example of enhancing the Minecraft code sample. Let's say, I want to give it a grass texture which would consist of 6 images (= 6 sides of a cube)... how would I do that?

**Comment by pokepetter** [comment]
The uvs are part of the model, so you don't have to do anything, just set the texture you want (texture='file_name').

The easiest way to make a cube like that would be to replace the model with a custom one that's unwrapped how you want it. While it's possible to use 6 quads and 6 images to make one cube, it a bad idea since it's ~6 times less performant.

If you want to change the uvs in ursina without using a 3d program, you can modify/set model.uvs and then call model.generate() to update it.

**Comment by famecastle** [comment]
Thank you for the explanation! I didn't know it was that simple.

**Comment by famecastle** [comment]
Again, I've got a question. I've right now used the Blender default cube and scaled it by 0.5 along all axes (because I've seen that it's 2x2x2 by default). I switched to Edit Mode and checked the UV map. It was fine but just for the sake of correctness I pressed "u > UV Unwrap".

I had 6 tiles, so I combined them with ImageMagick into a single quadratic 512x512 cubemap so that it fits the Blender unwrapping.

![cubemap2](https://user-images.githubusercontent.com/11258821/82916791-c9443500-9f72-11ea-9ef8-8af90725206e.png)

As you can see in the image, I had to rotate each side by 90 degrees for them to show up properly.

Now it's looking good but not entirely perfect. I can see slim white lines on the edges of my cube - in my game as well as in Blender when applying the cubemap texture.

![image](https://user-images.githubusercontent.com/11258821/82917404-abc39b00-9f73-11ea-9773-2e35e63a467a.png)

However, I can't see the lines in my cubemap.png . Do you know if I'm doing anything wrong?

**Comment by pokepetter** [comment]
I belive those are uv seams. The common way to solve that is to extend the edges in the texture so there's less white space around the shape.
For pixel graphics you can just disable the bilinear filtering with Texture.default_filtering = None

**Comment by CREATOR118** [comment]
why is this so frickin hard

**Comment by CREATOR118** [comment]
how do i make my own textures using blender
and i need it to be a png uv map

btw pokepetter if u see this u might know me as 
"THE_godof_death" from your discord server :)

**Comment by kkhashayar** [comment]
Hi.
Can you please explain how I can use collision!? in 2D mode between two objects, it looks very complicated!
Thanks a lot.

**Comment by Borrito0** [comment]
The way I check for collisions is first:
- adding the box collider to an Entity:   your_model=Entity(model='quad',color=color.white,scale=(1,1),position=(0,0),collider='box')
-then doing the same thing with another object
- and then checking for a collision :
     hit_info=your_model.intersects()
        if hit_info.hit:
            #Do whatever you want

**Comment by Spiceinajar** [comment]
> You should look up uv mapping. Here's an explanation: https://www.youtube.com/watch?v=scPSP_U858k

what software do you recommend because i have had no luck in finding any good free ones.

**Comment by venaxyt** [comment]
Blender is probably the best free one, even it's very hard to use.

**Comment by Spiceinajar** [comment]
> Blender is probably the best free one, even it's very hard to use.

I made that comment a while ago. since then, I have already learned blender. thanks though.
