### ISSUE TITLE
Feature Request: Hide Rendered Window

### ISSUE THREAD

**Issue by sam-the-programmer** [pokepetter/ursina#442]
Hi there,

I am writing some simulations that use Ursina's collision systems, and it is perfect, despite Python's slow speed, for my uses. However, to increase speed, is it possible to be able to toggle rendering the scene, or perhaps the entire window. (Emphasis on _toggle_, so that you can enable it programmatically again later), to decrease the time the simulation takes?

In a nutshell:

 - Can you turn off the rendering programmatically?
 - Can you turn back on the rendering programmatically?
 - Does this speed things up?

Many thanks for your time.

**Comment by pokepetter** [comment]
It's not currently possible to run without a window, no. However, if you don't give Entities models in the first place or if you set .visible to False, they won't be rendered, but colliders will still be there. There's probably a theoretical performance increase by not having a window, but I doubt I will be noticeable in practice.

**Comment by sam-the-programmer** [comment]
Thank you for the clarification. I might use this project in a reinforcement learning framework, do you have any advice on performance tips?
