### ISSUE TITLE
Jumping

### ISSUE THREAD

**Issue by Donyeet** [pokepetter/ursina#450]
How do I change the jump mechanic in ursina? Because it's not smooth, and i'm making a platformer so I need smooth jump. Anyone know how to Fix this?

**Comment by epsseniyer** [comment]
Jumping already have in 2d but in 3d : 
![image](https://user-images.githubusercontent.com/66587693/185782777-e2fdfef0-ba6e-4232-a8f1-8733f60b2825.png)

**Comment by epsseniyer** [comment]
And I dont know how to close 2d Platformer jump // Now i trying to learn

**Comment by Donyeet** [comment]
It's 3d

**Comment by pokepetter** [comment]
You copy this: https://github.com/pokepetter/ursina/blob/master/ursina/prefabs/first_person_controller.py
and changge it to work how you'd like it work. Or you could write it from scratch.
