### ISSUE TITLE
Upgrading Docs?

### ISSUE THREAD

**Issue by PeaPals** [pokepetter/ursina#457]
Hi all, first of all, thanks for this great library, I have just started playing with ursina and I feel that ursina is easy and fun, with a very high potential. But coming to the reason for this issue, I personally feel like docs and home page are the first impression for any library/application/software, and I feel ursina can do a lot better here. Is there any work going on in this regard?

I have seen the repos auto doc generation and conversion to html from txt and all, I think streamlit fits perfectly for this case. It can automate your docs, make better UI and can help in easy updating of docs since everything remains in python only.

I can give it a try if you guys have plans to upgrade the docs, homepage and/or any other page ursina has like ursina-for-dummies

Cheers.

**Comment by pokepetter** [comment]
> I personally feel like docs and home page are the first impression for any library/application/software, and I feel ursina can do a lot better here.

Is there anything specific you'd say gives a bad impression? You have to realize the focus of a website should be the content itself. It shouldn't be fancy. There's also the fact that the website is almost never the first impression, since people usually come to it from a video or similar.

> Is there any work going on in this regard?

I did update the api reference today, to make it easier to read. There's still a lot of work to do in updating examples a such though.

> I have seen the repos auto doc generation and conversion to html from txt and all, I think streamlit fits perfectly for this case.

I don't see how streamlit is relevant to this. Seems like overkill for showing some text on a page.

> I can give it a try if you guys have plans to upgrade the docs, homepage and/or any other page 

I think if you want to contribute something, it should be faster than your work on DocNets which gets a 18/100 performance score. If you have any specific suggestions though, you're welcome to present them.

**Comment by PeaPals** [comment]
> Is there anything specific you'd say gives a bad impression? You have to realize the focus of a website should be the content itself. It shouldn't be fancy. There's also the fact that the website is almost never the first impression, since people usually come to it from a video or similar.

Nothing in particular as such which gave a total bad impression, just normal stuff like code going outside the code-box. But overall, its all about user-experience. as you said, the focus should be contents and not fancy. To be honest, I came to this library by an online article... so my impression for this project was actually your homepage. Although, I think you are right that mostly users come from videos and similar.

> I did update the api reference today, to make it easier to read. There's still a lot of work to do in updating examples a such though.

"make it easier to read" was one of my reasons for this issue. I had no intention of saying the docs are not good enough or lack content, what I meant was that this could be more enhanced experience for ursina users. A good documentation experience make it easier to study and understand, it increases the clarity of what exactly is happening in the docs and how stuff works.

I have seen some libraries where docs have made a significant contribution. One of the recent example related to this was [Starlite Docs](https://starlite-api.github.io/starlite/) made using [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)

> I don't see how streamlit is relevant to this. Seems like overkill for showing some text on a page.

I do understand your concern for streamlit being an overkill for showing just some simple text on a page, I recommended streamlit because I felt that it might be able to easily bind with the documentation_generator scripts and since we only need to show some simple text, headings and code sniplets, we might as well choose something simple to use rather than complex frontend libraries.

> I think if you want to contribute something, it should be faster than your work on DocNets which gets a 18/100 performance score. If you have any specific suggestions though, you're welcome to present them.

Coming to DocNets, this project was part of some hackathon event I attended which was build in around 3 days duration. It was mostly a speedrun project for which we had no concern for performance since we wanted everything up-and-running first. The repos visibility was set to public because that was something the organizing organization demanded. I didn't maintain it later since I wasn't interested in doing so, that is the reason the code is messed up on the clean code part from inside, and gives a very low performance score.



Overall, I do feel that contents take priority while making of docs, fanciness is a secondary aspect. The ursina docs is filled with the required content, no issue over there... as for the user-experience in docs... maybe ursina can look on it later if now isn't the right time to focus on this.

**Comment by PeaPals** [comment]
Apologies... I think I was referencing the other pages and not the main doc all along... [like this one](https://www.ursinaengine.org/ursina_for_dummies.html).

I just came across this, [api reference](https://www.ursinaengine.org/api_reference.html) and it feels a lot more better and almost what I was talking about the changes. My bad.
