### ISSUE TITLE
noticing a missing requirement 'screeninfo'

### ISSUE THREAD

**Issue by fload** [pokepetter/ursina#458]
on Ubuntu screeninfo (screeninfo==0.8)  is required to run Ursina consider adding to setup.py.

**Comment by pokepetter** [comment]
screeninfo is only a fallback if you're a distro without X11. In those cases I kind of assume you're willing to fix things yourself and install screeninfo manually

**Comment by pokepetter** [comment]
If you know if there's a way to detect this and get the max window size from Wayland, that would of course be appreciated.

**Comment by y2bad** [comment]
On some distros that use X11 Xlib isnt installed by default and when used with multiple monitors it returns the size of both monitors combined. What is the problem with using screenifo it works perfectly fine i dont see any isues or am I missing something?

**Comment by pokepetter** [comment]
There were cases where it didn't work properly
