### ISSUE TITLE
Help on Importing .blend animations

### ISSUE THREAD

**Issue by SeraphWedd** [pokepetter/ursina#46]
Is there a way to import 3D animations of an object in a .blend file? I was trying it with the Animation and Animator Classes but can't seem to succeed. Is this only for 2D animations?

**Comment by pshobowale** [comment]
You can import it, but color information gets lost. 

Example: 
        blob=Entity(parent=self.model,model="blob", color=color,position=origin,scale=(scale/10,scale/10,scale/10) 
        #You must not add file extensions or path, because it is determined by the engine
