### ISSUE TITLE
shaders in ursina didn't work

### ISSUE THREAD

**Issue by rhacker885** [pokepetter/ursina#461]
shaders didn't work, if i try run [example](https://github.com/pokepetter/ursina/blob/master/ursina/shaders/basic_lighting_shader.py) to shaders it shows me this

![Image](https://snipboard.io/wGVNPQ.jpg)

and this is lit_with_shadows_shader ![lit_with_shadows_shader](https://user-images.githubusercontent.com/61989014/189515964-7b7a70da-445e-4ada-adc9-ed785861b91b.png)

**Comment by rhacker885** [comment]
noly this 
`package_folder: C:\Users\*****\AppData\Local\Programs\Python\Python310\lib\site-packages\ursina
asset_folder: ******
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
:display:windisplay(warning): SetForegroundWindow() failed!
:prc(warning): changing default value for ConfigVariable paste-emit-keystrokes from '1' to '0'.
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
screen resolution: (1920, 1080)
os: Windows
development mode: True
application successfully started`

**Comment by pokepetter** [comment]
The first example with basic_lighting_shader looks correct.
The lit_with_shadows_shader does not. What is the code you used for that?

**Comment by rhacker885** [comment]
I don't know anymore but lit_with_shadows_shader does the same thing

**Comment by pokepetter** [comment]
Does the same thing?

**Comment by rhacker885** [comment]
yes, do the same thing

**Comment by pokepetter** [comment]
The images you posted are clearly different, so no, they do not do the same thing.

**Comment by pokepetter** [comment]
Same things as what? Please tell me what this thing is.

**Comment by rhacker885** [comment]
like there are no shaders

**Comment by rhacker885** [comment]
my error was still not resolved

**Comment by pokepetter** [comment]
What error?

**Comment by pokepetter** [comment]
`(3 aux display modules not yet loaded.) :display:windisplay(warning): SetForegroundWindow() failed! :prc(warning): changing default value for ConfigVariable paste-emit-keystrokes from '1' to '0'. :pnmimage:png(warning): iCCP: known incorrect sRGB profile`
Is not an error

**Comment by pokepetter** [comment]
You have to provide more information

**Comment by rhacker885** [comment]
when I try to add shaders to the code do not show up at all

**Comment by rhacker885** [comment]
just if i try shaders it didn't shows any shadows

**Comment by pokepetter** [comment]
Please include:

- Steps to reproduce, including code.
- Any errors or output you get.
- System information.
