### ISSUE TITLE
:display:x11display(warning): XF86DGA extension not available, cannot enable relative mouse mode

### ISSUE THREAD

**Issue by linux-leo** [pokepetter/ursina#465]
I'm using Wayland, but the window seems to use XWayland (a compatibility layer running a nested x server).

While trying to use the FirstPersonController. I got the error above, making me always point downwards and spinning while trying to move my mouse, when i unlock it, the issue disappears. So maybe implement some mouse centering and hiding code? I just want to know if anybody can reproduce.

**Comment by linux-leo** [comment]
Here's the related panda3d issue, which is fixed: https://github.com/panda3d/panda3d/issues/746

**Comment by linux-leo** [comment]
Some more information, mouse centering isn't possible on wayland, so the only solution is to get the panda3d fix working

**Comment by linux-leo** [comment]
Nevermind it also doesn't work on xorg, something must be wrong on my end.

**Comment by youshitsune** [comment]
I have same problem, I use DWM suckless desktop environment.
