### ISSUE TITLE
Window position/scale isn't saved when moved or resized

### ISSUE THREAD

**Issue by y2bad** [pokepetter/ursina#466]
If you move or resize the window on the desktop its position/size isnt saved

Code:
`from ursina import *

app = Ursina(borderless = False)

def input(key):
    mouse.locked = False #this is just to update the window

app.run()`

**Comment by y2bad** [comment]
Is this supposed to happen?

**Comment by stutsanks** [comment]
I guess, 'window.size = window.size' are probably two different variables. one is the default value and the other the current variable.

**Comment by y2bad** [comment]
this is just to update the window

**Comment by y2bad** [comment]
tried to explain it a bit better
