### ISSUE TITLE
PNG Support for Terrain

### ISSUE THREAD

**Issue by 22yeetz22** [pokepetter/ursina#469]
Support PNG for terrain heightmap (or at least make a warning).

Currently, if you pass a PNG in, it just makes a flat map.

This took me hours to debug

**Comment by pokepetter** [comment]
RGBA PNGs are supported

**Comment by 22yeetz22** [comment]
My image doesn't work unless I convert it into a jpeg:
![MHEIGHT](https://user-images.githubusercontent.com/74276537/195197944-63ffcc05-7116-4bbc-b5ff-79552176b946.png)
