### ISSUE TITLE
Wrong rotations

### ISSUE THREAD

**Issue by komaljeet** [pokepetter/ursina#47]
This is the bug:
Entity.rotation_z rotates on the y-axis
Entity.rotation_y rotates on the z-axis.

Vertical line is z-axis.

on panda3D, setHpr signature is this:
z =  heading/yaw
x = pitch
y = roll
setHpr(z, x, y)

**Comment by pokepetter** [comment]
It's not wrong or a bug. It's just a different coordinate system.

**Comment by pokepetter** [comment]
To clarify, you say which axis you want to rotate around. 
The coordinate system in ursina is x=right, y=up and z=forward, I think that's the most logical and practical.

**Comment by komaljeet** [comment]
This will confuse the hell out of everyone switching between 3D softwares and Ursina.

I guess at this point too much has been done to switch back to the correct approach.

**Comment by pokepetter** [comment]
Z-up up is not the "correct approach", people will never agree on this. Maya, OpenGL, Direct X and Unity3D all use y-up, so it depends on what you're used to really.

**Comment by komaljeet** [comment]
I realized that a bit late. Was mixing up maths and software XD
