### ISSUE TITLE
sample bugs?

### ISSUE THREAD

**Issue by bearney74** [pokepetter/ursina#471]
What is the purpose of bug.py, bug_2.py and bug_3.py?    

bug_3.py seems to work ok on my system but bug.py and bug_2.py don't..  Are these documenting discovered bugs ?  If so, wouldn't it be better to move them somewhere else so that new users don't get confused.   If they are supposed to work, then they don't under my system.  For bugs.py I do get some output in the display, but the window is blank.

My system:
Linux (lubuntu 22.04)
python version: 3.10.6
ursina version: 5.0.0

Here's the output:
Memview content : [0, 0, 0, 0, 0, 0]
Memview format : H
Memview length : 6
Copy to memview : [0, 1, 2, 0, 2, 3]
tri_data :
GeomTriangles (indexed):
  [ 0 1 2 ]
  [ 0 2 3 ]

screen resolution: Vec2(1920, 1080)
os: Linux
development mode: True
application successfully started
info: changed aspect ratio: 1.778 -> 1.778
info: changed aspect ratio: 1.778 -> 1.778

**Comment by pokepetter** [comment]
Nothing, I use them to reproduce bugs or experiment, I just accidentally committed them :P
