### ISSUE TITLE
ursina version?

### ISSUE THREAD

**Issue by bearney74** [pokepetter/ursina#472]
Is there a way to figure out which ursina version we have installed?
It would be cool to do something like:
import ursina
print(ursina.version)  # or maybe print(ursina.__version__)

Also for other libraries (panda, pillow, etc), can we figure out which versions are being used as well.

This could be nice for debugging, etc.   If there is a way can someone post it?

Btw..   I really like Ursina.  I teach college courses and I'm thinking about creating a game development class using Ursina.

**Comment by pokepetter** [comment]
pip list
