### ISSUE TITLE
mixamo to ursina

### ISSUE THREAD

**Issue by bearney74** [pokepetter/ursina#473]
I'm looking to download game characters from [mixamo](https://www.mixamo.com/) and use them in ursina.  I've downloaded a character in fbx format, and I'm looking into ways to use this in ursina (ie, FrameAnimation3d), but everything I have tried has failed.  

I've looked at other issues, and saw that someone has suggested using panda Actor class, and my attempts have failed with that.  I downloaded a gltf file and was not able to get the actor class to work.

I did have partial success with converting the fbx file in blender to obj files and then using FrameAnimator3d.  Blender also creates mtl files to go with each animation step, so any texture info got lost.  The animation had several hundred steps, so doing that seemed to slow ursina down quite a bit.

Could someone post instructions, like what file format to use when downloading from mixamo, and then how to convert that to something that ursina knows how to use?  It would be good if the textures would be used because some of the characters on mixamo seem quite complex.

Thanks!

**Comment by pokepetter** [comment]
Frame Animation3D can be good if you don't have many frames, it's a very old school way of doing things which means it has less features, but also less can go wrong. As long as you use only one texture on it, which you should anyway, it should work without an mtl.
From the faq:

How do I make a character animate?

You have two options here. The first one is using .glft files and panda3d's Actor:

```
from ursina import *
from direct.actor.Actor import Actor

app = Ursina()

entity = Entity()
#animations are stored within the file
actor = Actor("filename.gltf")
actor.reparent_to(entity)

actor.play("animation_name")

app.run()
```

See the panda3d documentation for more info.

**Comment by bearney74** [comment]
Thanks..  I did use that example from the FAQ to use a panda Actor, but it seemed to not work either.   I'll keep working on it, and if I can get something working, I'll post the solution.

**Comment by bearney74** [comment]
I keep getting :

:Actor(warning): assets/Thriller Part 1.gltf is not a character!

Does anyone know what might be causing this.  I've done some google searches and have not found a solution.  Does anyone have a url, etc that would point me in the right direction?

I promise once, I get it working, I will post something here showing how to solve it.

Thanks!

**Comment by bearney74** [comment]
I just found this video that might help: [https://www.youtube.com/watch?v=Z158bGot1S4](https://www.youtube.com/watch?v=Z158bGot1S4)

**Comment by bearney74** [comment]
[https://github.com/facebookincubator/FBX2glTF](https://github.com/facebookincubator/FBX2glTF) seems to be able to take a fbx file from mixamo (using default settings), and convert it to a gltf file that ursina/panda3d (actor class) can read and display properly.

I do have one issue.  I have several gltf files that I use in one actor, and I would like for each one to play after another so that the  position where one animation ends is where the new animation starts off.  Currently it looks like each animation starts at (0,0,0).

Does anyone have an idea why each animation starts at (0,0,0), instead of where the previous animation stopped?

 
``
self.actor = Actor("assets/Thriller0/Thriller0.gltf",
                           {
                           "0": "assets/Thriller0/Thriller0.gltf",
                           "1": "assets/Thriller0/Thriller0.gltf",
                           "2": "assets/Thriller1/Thriller1.gltf",
                           "3": "assets/Thriller2/Thriller2.gltf",
                           "4": "assets/Thriller3/Thriller3.gltf",
                           "5": "assets/Thriller4/Thriller4.gltf"
                           })
``

**Comment by bearney74** [comment]
I got this working.  I went to the panda3d github issue site and a few people there was able to steer me in the correct direction.

Here's the issue url: https://github.com/panda3d/panda3d/issues/1382
