### ISSUE TITLE
ui no longer appearing after ursina v5 update

### ISSUE THREAD

**Issue by RedHenDev** [pokepetter/ursina#478]
Here's some sample code (rest of code positions, adds textures, sorts logic for inventory items, etc.).

``hotbar = Entity(model='quad',parent=camera.ui)``
``hotbar.scale_y=0.08``
``hotbar.color=color.dark_gray``
``hotbar.render_queue=0``

Instead of my former ui entities on camera.ui, I'm just getting a white diamond.

Is there anything I need to change due to new update? 

Thanks for any help.

**Comment by pokepetter** [comment]
Looks correct here. Do you have a minimal reproducible example?

**Comment by RedHenDev** [comment]
Thanks.

```

from ursina import *
app=Ursina()

from ursina.prefabs.first_person_controller import FirstPersonController

subject=FirstPersonController()
subject.gravity=0

cube = Entity(model='cube', color=color.rgb(0,200,0), scale=2)
cube.texture='brick'
cube.position+=Vec3(0,0,10)

# Inventory hotbar example.
hotbar = Entity(model='quad',parent=camera.ui)
# Set the size and position.
hotbar.scale_y=0.08
# *** - corrects for fullScreen panel overflow.
# These seem to be the problem lines.
# Note that if commented out, the diamond still
# appears when hotbar ui set to invisible.
hotbar.scale_x=hotbar.scale_y*9*1.1 # Ought to be rowFit.
hotbar.y=-0.45 + (hotbar.scale_y*0.5)
# Appearance.
hotbar.color=color.pink
hotbar.render_queue=2

def input(key):
    if key=='i':
        hotbar.visible=False
    if key=='k':
        hotbar.visible=True

app.run()
```

**Comment by pokepetter** [comment]
Looks fine here

**Comment by RedHenDev** [comment]
OK. Thanks for checking.

I'll try to work out what's going on my end.

**Comment by RedHenDev** [comment]
Ah -- the issue has something to do with the following:

Setting parent of ui entity to

``camera.ui_camera

instead of

``camera.ui

improves things, but still leaves me with a diamond artefact at centre of screen.
Do you know if I can address this?

**Comment by RedHenDev** [comment]
OK -- some progress. 

The diamond artefact is just the FirstPersonController cursor, not my ui entity. With the new Ursina version, it just appears much larger.

(So I just need to scale down the FPC cursor to appear as it did in previous version of Ursina).

I think, then, that the changes that are causing my issues have to do with changes to the scaling of the ui and the (new?) use of the `camera.ui_camera` parenting instead of `camera.ui` parenting.

This may already be documented somewhere as a change -- apologies, I've just not found it yet. Thanks again for the help.

**Comment by pokepetter** [comment]
The thing is, I haven't changed anything I think would affect this. You probably shouldn't parent things to camera.ui_camera though. 
The FPC's cursor size has not been changed. Parenting has not been changed. Scale has not been changed. I have not seen any changes in any of my games.
Again, all looks as expected on my end, so I'm not sure what's wrong, how to reproduce it, what you expect it to look like or how it looks like for you.

**Comment by RedHenDev** [comment]
OK -- the issue my end is to do with scaling between Fullscreen mode and Windowed for camera.ui.

I'm developing in Windowed mode, so scaling and positioning ui entities and textures according to this mode. But when switching to Fullscreen, ui entities are massively scaled down (see shots below). In fact, the scale discrepancy is so different that for the Fullscreen shot below I magnified by a factor of 10 so that we can still see the ui (barely a speck else).

So -- before updating to v5 (apologies, it must have been months, possibly a year? between previous version of Ursina) Windowed mode and Fullscreen did yield a scaling discrepancy, but it was trivial. After I updated, my ui entities (windowed mode) just weren't showing at all (i.e. something had changed that affected camera.ui scaling indirectly).

My end, then, and for anyone else affected, the workaround is to check whether Fullscreen or Windowed mode and apply a scalar to ui as generally as possible. I will post again with example code and the right scale factor for this, until we can correct the issue -- no doubt connected to aspect ratio.

Hope this is helpful.

Windowed:
![Screenshot 2022-10-30 at 09 43 05](https://user-images.githubusercontent.com/24874180/198872457-bfa30ce9-b621-403a-8567-deab416ad1cc.png)

Fullscreen:
![Screenshot 2022-10-30 at 09 46 03](https://user-images.githubusercontent.com/24874180/198872492-354206f6-0a07-48f2-8b70-18be51a76b94.png)

**Comment by RedHenDev** [comment]
NB. we can also see the Frames-per-second and Red Cross in Fullscreen mode, which are scaled off somewhere as default in Windowed mode.

**Comment by RedHenDev** [comment]
Solved.

```
if window.fullscreen==False:
    camera.ui.scale_x*=0.05*1/window.aspect_ratio
    camera.ui.scale_y*=0.05
```

This corrects for the scaling discrepancy perfectly. 

I don't like my magic number in there, but otherwise it's a simple solution:

Windowed:
![Screenshot 2022-10-30 at 12 35 19](https://user-images.githubusercontent.com/24874180/198878970-2b5d6391-b356-4b12-8985-5ab344a040cf.png)

Fullscreen:
![Screenshot 2022-10-30 at 12 32 39](https://user-images.githubusercontent.com/24874180/198878984-14eeae21-1ea2-4a7a-b5bf-8d86c25073fc.png)
