### ISSUE TITLE
How can i create gravity functions for my ursina game?

### ISSUE THREAD

**Issue by SirBluberryDev** [pokepetter/ursina#479]
I am new to ursina and i want some y axis gravity functions for my game. how can i create that? i just want my player to have the ability to collide with the floor.
![image](https://user-images.githubusercontent.com/91642654/198891550-e77cf353-f93a-4110-8009-2d8235b038d4.png)
![image](https://user-images.githubusercontent.com/91642654/198891565-adc3e827-6f01-43a3-8e9e-e0bf17830796.png)

**Comment by RedHenDev** [comment]
There are two broad ways.

Try this simple first way to get you started:

Just replace my 'player' variable with whatever variable you use for your main player.

```
def update():
    ground_height = 0
    if player.y > ground_height:
        gravity_strength = 0.1
        player.y -= gravity_strength
    else: player.y = ground_height
```

Good luck!

**Comment by SirBluberryDev** [comment]
@RedHenDev thank you very much, man!
