### ISSUE TITLE
Incorrect content of held_keys

### ISSUE THREAD

**Issue by AStotal** [pokepetter/ursina#48]
I've just dived into code and found some strange thing.

`held_keys` contains incorrect key events. Just an example of code I used in main function of `ursina/input_handler.py`:

```python
    hk = None
    def update():
        # Print held_keys on its change
        global hk
        if hk != held_keys:
            hk = held_keys.copy()
            print(held_keys)
```
Then I pressed some keys and got the following output(with my comments):
```
defaultdict(<function <lambda> at 0x039CCF60>, {'left mouse down': 1, 'shift': 0})   # Press LMB
defaultdict(<function <lambda> at 0x039CCF60>, {'left mouse down': 1, 'shift': 0, 'left mouse': 0})  # Release LMB
defaultdict(<function <lambda> at 0x039CCF60>, {'left mouse down': 1, 'shift': 0, 'left mouse': 0, 'a': 1}) # Press 'a'
defaultdict(<function <lambda> at 0x039CCF60>, {'left mouse down': 1, 'shift': 0, 'left mouse': 0, 'a': 1, 'a hold': 1}) # Holding 'a'
defaultdict(<function <lambda> at 0x039CCF60>, {'left mouse down': 1, 'shift': 0, 'left mouse': 0, 'a': 0, 'a hold': 1})` # Release 'a'
```

How can I see mouse release wasn't detected at all. The 'a' button determined as always hold - looks not good. 
Is it expected behavior or it is a bug? If bug - please tell wht behavior is expeted

**Comment by pokepetter** [comment]
The only bug here is that some keys gets unnecessarily added, like the mouse buttons and the 'hold' variants. The 'a' button is *not* determined as always held though, it changes from 1 to 0 in your example above. print held_keys['a'] and you'll see it clearly.

I usually use mouse.left to check if it held, but I'll change held_keys so it works correctly with mouse buttons too.

**Comment by AStotal** [comment]
@pokepetter do you mind if I'll try to fix it?
