### ISSUE TITLE
i was wondering how i could make my ui background maintain to it's original size

### ISSUE THREAD

**Issue by SirBluberryDev** [pokepetter/ursina#480]
when i added a ui background, it is a square how do i fix that
![image](https://user-images.githubusercontent.com/91642654/198906001-e2d9a3ce-a88b-4bee-91d6-3951b5bc2d74.png)

**Comment by RedHenDev** [comment]
`background.scale_x *= window.aspect_ratio`

**Comment by SirBluberryDev** [comment]
@RedHenDev thanks
