### ISSUE TITLE
Text not appearing on top of some (textured) ui entities

### ISSUE THREAD

**Issue by RedHenDev** [pokepetter/ursina#481]
Text will appear over some ui entities, but not all. Not even when `always_on_top` property set to true.

Have tried various combinations of `render_queue` for my ui entities, which otherwise seem to work (e.g. draggable ui tiles with texture appear over the top of textured ui grid, and which itself appears over the top of a grey ui panel background quad).

But I can't get the text to appear on top. See screenshot below, where we can see text between other ui elements.

Relevant code:
```
t=Text(parent=camera.ui,render_queue=3,scale=2)
        t.origin=(0,0)
        t.text=("<black><bold>"+
                                str(this.blockType)+' '+
                                str(this.currentSpot.stack))
        t.position=this.currentSpot.position
        t.always_on_top=True
```

I've tried different parentings, different render_queue-ings -- but to no avail.

Any ideas?

![Screenshot 2022-11-09 at 19 45 11](https://user-images.githubusercontent.com/24874180/200926385-5e6e5188-0ff3-4a8a-9061-31597b319325.png)

**Comment by pokepetter** [comment]
The way to order ui entities is by setting `.z`. So `z=-1` will make it render above entities with `z=0` for example.

**Comment by RedHenDev** [comment]
Brilliant -- thank you, that worked (and I just needed to remove all my `render_queue` settings). So simple!

Thank you :)
