### ISSUE TITLE
In version 5.1.0 the window.borderless parameter is ignored (Linux)

### ISSUE THREAD

**Issue by misolietavec** [pokepetter/ursina#483]
After upgrading to 5.1.0 all my files with setting  `window.borderless = False` do not have border. Checked with downgrade to 5.0.0 (in the same clean virtual environment) - all works as it should.

**Comment by misolietavec** [comment]
Further investigation: I have `conda` environment and also `virtualenv` environment. In `virtualenv` the window border was not showing regardless of `ursina` version (5.0.0 or 5.1.0). Comparing the versions of `ursina` dependencies I found that in `conda` env. we have pillow 9.3.0 and in `virtualenv` it was 9.2.0. After upgrading to 9.3.0 the behaviour is consistent with conda environment (good with 5.0.0 and no border in 5.1.0). Maybe, this can help you to track the source of troubles...

**Comment by y2bad** [comment]
the change that causes this was made here https://github.com/pokepetter/ursina/commit/9c2094b68245f5bbc80ba9ab9698aaaf25780409

**Comment by pokepetter** [comment]
Thanks for the report.
Fixed
