### ISSUE TITLE
failed to input information in inputfield

### ISSUE THREAD

**Issue by chw-ob** [pokepetter/ursina#487]
![image](https://user-images.githubusercontent.com/113024028/204553895-a92175e5-fe54-441d-a52a-92252e2559d7.png)
i cann't put any information in the inputfield.Is there anything i did wrong?

**Comment by pokepetter** [comment]
The first field is an example of limit the input to numbers only, by using `limit_content_to`. If you remove this, you can input whatever characters you want.
The second field is an example of hiding the content with `hide_content=True`

**Comment by chw-ob** [comment]
Thank you for your reply!But i can not even input numbers to the field.Only 'TAB' can work(ursina version:5.1.0).

> The first field is an example of limit the input to numbers only, by using`limit_content_to`. If you remove this, you can input whatever characters you want.The second field is an example of hiding the content with`hide_content=True`

**Comment by pokepetter** [comment]
Can't reproduce.
