### ISSUE TITLE
obj texture problem

### ISSUE THREAD

**Issue by gnuchanos** [pokepetter/ursina#488]
![2022-12-06-093252_1280x1012_scrot](https://user-images.githubusercontent.com/117280480/205841482-b8b9d3e0-6f69-4f9e-b440-29d990ef8434.png)
![2022-12-06-093226_1280x1012_scrot](https://user-images.githubusercontent.com/117280480/205841485-09fe3268-4c43-4f2b-85f3-a96623d2f68b.png)
![2022-12-06-093223_1280x1012_scrot](https://user-images.githubusercontent.com/117280480/205841488-3064aec3-14dc-458a-a31f-b1f134e783dd.png)

**Comment by y2bad** [comment]
probably wrong uv-mapping

**Comment by GnuchanOS** [comment]
ı forget this thanks again
