### ISSUE TITLE
help on making player controller

### ISSUE THREAD

**Issue by ultraflame4** [pokepetter/ursina#49]
Is there a simple way to add in gravity and block collisions?
something like unity's rigidbody
~_im getting tired of trying and failing to do that_~

**Comment by DiamondsBattle** [comment]
A way to add gravity is by using Panda3d's BulletWorld, on wich you can find a tutorial [here](https://docs.panda3d.org/1.10/python/programming/physics/bullet/hello-world).
FOr some help, join the [Ursina Discord Server](https://discord.gg/UtZ8Xju).

**Comment by ultraflame4** [comment]
ok thks
