### ISSUE TITLE
Not rendering this *b.obj/*b.mtl properly

### ISSUE THREAD

**Issue by LoliHaxxer** [pokepetter/ursina#490]
this is the asset directory, and the texture files for white bishop (w_b.mtl) and black bishop (b_b.mtl) are causing problems
![image](https://user-images.githubusercontent.com/49691454/207469202-a4e22075-88a7-40dd-8130-e388e69af9d7.png)
as their textures (.mtl) aren't rendered
![image](https://user-images.githubusercontent.com/49691454/207470994-0991fd37-2999-4823-a5e4-8b4d6917df42.png)

After a bit of testing, apparently
![image](https://user-images.githubusercontent.com/49691454/207470353-084f0ac4-282e-4498-a92e-b9657af8a295.png)
.obj files with a filename that is potsfixed by 'b' do not load their corresponding textures.

I am not sure whether this is part of specification of .obj files, which I could not find in this case, or whether this is an issue with ursina

**Comment by pokepetter** [comment]
Fixed :)
There was an issue with the use of rstrip producing an incorrect path for the .mtl.  

Update with `pip install https://github.com/pokepetter/ursina/archive/master.zip
 --upgrade` and it should work.

**Comment by DanielMPR17** [comment]
It still doesnt work for me, can you please help me?

**Comment by pokepetter** [comment]
Doesn't sound like the same error.
