### ISSUE TITLE
FirstPersonController glitching through ceiling

### ISSUE THREAD

**Issue by ZombiesLoveZGames** [pokepetter/ursina#491]
I have had a problem with the FirstPersonController being able to jump up into the underside of meshs, and I have tried all sorts of coding to fix this, however nothing seems to be working. Is there anyway to stop this bug?

**Comment by pokepetter** [comment]
The FirstPersonController was not made for a game with ceilings, so it doesn't account for them. The PlatformerController2D does however, so maybe you can copy that ceiling check over? If you're making something serious you'll want to have local copy of the controller anyway, so you have full control.

**Comment by ZombiesLoveZGames** [comment]
Thank you, I had no idea. Now I can actually finish some of my previous attempts at a 3D game

**Comment by ZombiesLoveZGames** [comment]
Thank you, I had no idea. Now I can actually finish some of my previous attempts at a 3D game

**Comment by ZombiesLoveZGames** [comment]
I have tried this, but it doesn't seem to be working. I have also tried simillar ways but to no avail.

**Comment by vvvvvvitor** [comment]
duplicate of #165

**Comment by nosleepfor** [comment]
head_hit=raycast(player.world_position+Vec3(0,player.height,0), Vec3(0,1,0), 0.1, ignore=(player, ))
    if head_hit:
        player.start_fall()
        
You can add this to your update or FirstPersonController based class.

(after two years....)

**Comment by ZombiesLoveZGames** [comment]
Thank you for the help, honestly, I started a different project and have only come back to it now, but I appreciate the effort!
