### ISSUE TITLE
The *.stl mesh imports mirrored 

### ISSUE THREAD

**Issue by fader111** [pokepetter/ursina#493]
` Entity(model=_path, scale=(.1, .1, .1), y=-2,  flipped_faces=False, ) 
`
loads as a mirrored object. without flipped_faces=False mesh is transparent. 
In blender or Paint3D it loads correct. What can be the problem?

**Comment by pokepetter** [comment]
.stl is not supported by ursina. If the format is not supported, it will try to load it with assimp instead.  However, my guess is that .stl doesn't include coordinate system information, so it gets mirrored. I recommend using either .obj or .gltf/.glb. If you can't export to those formats, you can import the .stl to Blender and convert it there.

**Comment by fader111** [comment]
tryed that, has been exported as a .obj the mesh gets mirrored in ursina.
[ToothSurface_33.zip](https://github.com/pokepetter/ursina/files/10280515/ToothSurface_33.zip)

**Comment by fader111** [comment]
That helped. Thanks.
