### ISSUE TITLE
difficult to use

### ISSUE THREAD

**Issue by haisheng666** [pokepetter/ursina#494]
Your engine is very difficult to use. After open the sample file rubiks_cube.py , I don't know how to operate it, nor can I shut it down. Restarting the host does not work. It is like being stuck. I only see a lot of graphics rotating back and forth. Please improve the engine, and the basic example can be used normally, and then upload it to github, OK?

**Comment by haisheng666** [comment]
Broken things. I tried all kinds of methods but could not close the window. Finally, I had to restart the host to solve the problem. It was the first time I encountered such a garbage engine

**Comment by Fer-Jg** [comment]
Been using this for the last couple of hours from scratch and it's been pretty straight-forward, maybe not the best docs in the work but still kind of good, maybe it's just too complex for the world, try making an engine yourself that you can understand 😄

**Comment by pokepetter** [comment]
Restart the host? What are you talking about? Run it on your own computer.

There's literally a big red X in the corner you can click on to close the window. There's also multiple ways to close a program through your OS. I recommend learning about basic OS operations before starting programming.

You don't really provide any useful feedback here I can use to improve it.

**Comment by haisheng666** [comment]
Can you set the x in the upper right corner? Everyone's operating habits are like this. You have to set up a red X, and your engine is doomed to be difficult to use. Encapsulate the pands3d. It's not as good as it is. Please improve it

**Comment by haisheng666** [comment]
![image](https://user-images.githubusercontent.com/42937758/209905420-b30444f7-5b00-4344-8c60-f5466f979c48.png)
No, for many examples, clicking the red x in the upper right corner doesn't work. There is no response. The Ubuntu 22 system

**Comment by haisheng666** [comment]
It's really rubbish. No other program can be clicked and cannot exit. We have to restart the host to solve the problem. Don't reply. This item is completely unavailable. Go offline now

**Comment by haisheng666** [comment]
![image](https://user-images.githubusercontent.com/42937758/209906351-7591bd6c-e0ce-4e9f-b4a4-15712a38c0a4.png)

**Comment by y2bad** [comment]
what "host" so you need to restart?

**Comment by pokepetter** [comment]
When using the first person controller, the mouse is locked to the middle of the screens. That's why you can't click the button. But the button is there and it works. You can still press Alt+F4 to close the program like usual. Or Alt+Tab to the terminal and close that. Or you can press Shift+Q. 

It's not ok to behave like you're doing though.
