### ISSUE TITLE
AttributeError: 'Texture' object has no attribute '_cached_image'

### ISSUE THREAD

**Issue by Plizik** [pokepetter/ursina#499]
"C:\Users\chann\PycharmProjects\Project BM Revival\venv\Scripts\python.exe" "C:\Users\chann\PycharmProjects\Project BM Revival\main.py" 
package_folder: C:\Users\chann\PycharmProjects\Project BM Revival\venv\Lib\site-packages\ursina
asset_folder: C:\Users\chann\PycharmProjects\Project BM Revival
Traceback (most recent call last):
  File "C:\Users\chann\PycharmProjects\Project BM Revival\main.py", line 3, in <module>
    from entities.grass_block import GrassBlock
  File "C:\Users\chann\PycharmProjects\Project BM Revival\entities\grass_block.py", line 4, in <module>
    grass_texture = load_texture("textures/blocks/grass_block.png")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chann\PycharmProjects\Project BM Revival\venv\Lib\site-packages\ursina\texture_importer.py", line 40, in load_texture
    t = Texture(filename.resolve())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chann\PycharmProjects\Project BM Revival\venv\Lib\site-packages\ursina\texture.py", line 23, in __init__
    self._texture = loader.loadTexture(Filename.fromOsSpecific(str(value)))
                    ^^^^^^
NameError: name 'loader' is not defined. Did you mean: 'Loader'?
Exception ignored in: <function Texture.__del__ at 0x0000015F4846CE00>
Traceback (most recent call last):
  File "C:\Users\chann\PycharmProjects\Project BM Revival\venv\Lib\site-packages\ursina\texture.py", line 185, in __del__
    del self._cached_image
        ^^^^^^^^^^^^^^^^^^
AttributeError: 'Texture' object has no attribute '_cached_image'

Process finished with exit code 1

happened after i did this code

`from ursina import *
import os
os.chdir("assets/blocks/")
grass_texture = load_texture("grass_block.png")

class GrassBlock(Entity):
    def __init__(self, position=(0, 0, 0), texture = grass_texture):
        super().__init__(
            parent=scene, model='block.obj',
            scale=0.5, texture=texture, position=position,
            origin_y=0.5, color=color.color(0, 0, random.uniform(0.9, 1))
        )`

Why this happens? 
![Image with folders](https://user-images.githubusercontent.com/75259535/212144381-544d4456-3baa-411e-9851-68b6da960a11.png)

**Comment by Plizik** [comment]
I tried to remake it a little, issue remains

**Comment by pokepetter** [comment]
You need to create an instance of Ursina before loading textures. This is the way it's done in all the examples.
`load_texture()` is an internal function and should usually not be used, do `texture='grass_block'` instead. See https://www.ursinaengine.org/entity_basics.html#Texture

**Comment by pokepetter** [comment]
> I tried to remake it a little, issue remains upd. i tried to run a code in bug-report #498, level editor run has the same issue

That code doesn't even mention textures, how can you get the same error?

**Comment by Plizik** [comment]
> You need to create an instance of Ursina before loading textures. This is the way it's done in all the examples.
> 
> `load_texture()` is an internal function and should usually not be used, do `texture='grass_block'` instead. See https://www.ursinaengine.org/entity_basics.html#Texture

now i did this, but it crashes. did the path to png right tho

**Comment by Plizik** [comment]
> > I tried to remake it a little, issue remains upd. i tried to run a code in bug-report #498, level editor run has the same issue
> 
> 
> 
> That code doesn't even mention textures, how can you get the same error?

idk how this happened, maybe there are logs explaining what program does besides console?

**Comment by Plizik** [comment]
> You need to create an instance of Ursina before loading textures. This is the way it's done in all the examples.
> 
> `load_texture()` is an internal function and should usually not be used, do `texture='grass_block'` instead. See https://www.ursinaengine.org/entity_basics.html#Texture

now it's fixed, i made platform 256x256 this is why it crashed
