### ISSUE TITLE
Mouse scroll is always active in held_keys

### ISSUE THREAD

**Issue by AStotal** [pokepetter/ursina#50]
Checkout wtih the following update function and croll

```python
def update():
    if any(held_keys.values()):
        print(held_keys)
```

**Comment by pokepetter** [comment]
I agree it shouldn't be there, but what issue does it cause?

**Comment by AStotal** [comment]
Actually nothing 😄 

![image](https://i.imgflip.com/44fawu.jpg)

**Comment by pokepetter** [comment]
I guess you could count the number of held keys I guess. Fixed now.

**Comment by imvickykumar999** [comment]
`defaultdict(<function <lambda> at 0x0000016BCB84CCC0>, {'w': 0, 's': 0, 'd': 0, 'a': 1, 'shift': 0})`

I could not see `mouse scroll` detection!
