### ISSUE TITLE
[Tool] I got a way to see the old cheatsheet (was apparently removed.)

### ISSUE THREAD

**Issue by ANDREI12333** [pokepetter/ursina#501]
https://raw.githack.com/pokepetter/ursina/v3.2.2/docs/cheat_sheet.html

**Comment by pokepetter** [comment]
What's the issue? Why would you need the old cheat sheet? If you do, you can get it from the git repo as it stores the whole history of the project.

**Comment by ANDREI12333** [comment]
I know but that's linking to the same thing just rendering it instead of having to download it to see it.

**Comment by pokepetter** [comment]
Ok, but what's the point of the issue? What should i fix or help you with?
