### ISSUE TITLE
load_model loads models incorectly

### ISSUE THREAD

**Issue by ZombiesLoveZGames** [pokepetter/ursina#502]
I have been having trouble lately with load_model, as it is being loaded wierdly resulting in an error:
 'panda3d.core.NodePath' object has no attribute 'vertices'
I have some Ideas on how to get around this, but they are very ineficient.
Any Ideas?

**Comment by pokepetter** [comment]
Can you post code?

If you need to load a model for things like procedural generation and *need* to access its vertices, make sure to do:
```
m = load_model('my_model', use_deepcopy=True)
```

**Comment by ZombiesLoveZGames** [comment]
This works!
I didn't know that the solution would be so simple.
The code I am using is this:

from ursina import *
from random import randint as r

class WorldGenerator(Entity):
	def __init__(self):
		super().__init__()
		self.chunk_size = 3
		# self.plane_entity = Entity()
		# e = Entity(model = 'plane.obj', visible = False, parent = self.plane_entity)
		# self.plane_entity.combine()
		# self.plane_entity.visible = False
		self.plane_model = load_model('plane', use_deepcopy=True)
		self.combiner = Entity(model = Mesh(), texture = 'Terrain/Tilemap', tileset_size = [31, 30])

	def generate_chunk(self, off = [0, 0]):
		for x in range(-self.chunk_size, self.chunk_size + 1):
			for z in range(-self.chunk_size, self.chunk_size + 1):
				self.combiner.model.vertices.extend([ Vec3(x + off[0], -0.05, z + off[1]) + v for v in self.plane_model.vertices])

				uvsx = r(5, 7)
				self.combiner.model.uvs.extend([Vec2(uvsx, 21) + u for u in self.plane_model.uvs])

		self.combiner.model.generate()

The commented out lines are my old attempts. Thanks again.

**Comment by pokepetter** [comment]
Glad you solved it. I know it's a bit annoying to have to specify if it should use deepcopy, but it's for performance reasons.
