### ISSUE TITLE
Shaders don't work

### ISSUE THREAD

**Issue by rhacker885** [pokepetter/ursina#506]
i tried shader but they didnt work, i think it's because my hardware. 
i tried run basic_lighting_shader.py but there is no shadows too:
![image](https://user-images.githubusercontent.com/61989014/216110736-d2cd56ea-d73f-45a6-a9a9-465a7430204e.png)

hardware:
CPU:
	Intel(R) Core(TM) i3-4160T CPU @ 3.10GHz

	speed:	3,10 GHz
	sockets:	1
	cores:	2
	logic processors:	4
	virtualization:	Enabled
	L1:	128 kB
	L2:	512 kB
	L3:	3,0 MB
GPU:
        Intel(R) HD Graphics 4400

	driver version:	20.19.15.5171
	driver date:	04.11.2020
	DirectX:	12 (FL 11.1)
	fyzical position:	Sběrnice PCI 0, zařízení 2, funkce 0

        memory: 2GB
RAM:
	8,0 GB DDR3

	speed:	1600 MHz
	slots used:	2 z 4
	parametrs:	SODIMM
	hardware reservation:	95,6 MB

(I am sorry for my english im not that good)

**Comment by pokepetter** [comment]
That's how the basic_lighting_shader looks like. For cast shadows, use lit_with_shadows_shader as described in the documentation under DirectionalLight.

**Comment by rhacker885** [comment]
> lit_with_shadows_shader

lit with shadows shader look like that

![image](https://user-images.githubusercontent.com/61989014/222908237-a6fe3040-9f79-4fe0-9b45-b2e929787fe7.png)
