### ISSUE TITLE
Bad Performance with very little loaded in

### ISSUE THREAD

**Issue by Recentaly** [pokepetter/ursina#507]
Game runs at 12 FPS with nothing but a baseplate with some trees loaded in. Task Manager reports 30% GPU Usage, what's happening here?

**Comment by Recentaly** [comment]
Code: https://pastebin.com/NeG6Y5Bs

Link to the .blend file
[map_1.zip](https://github.com/pokepetter/ursina/files/10714493/map_1.zip)

**Comment by y2bad** [comment]
looks like the mesh collider may be the problem

**Comment by Recentaly** [comment]
Yup, that solved it. Know any other collider othan than box? box collider makes the trees pass-through

**Comment by pokepetter** [comment]
You should think of mesh colliders as having one collider for each triangle. That quickly becomes expensive. If possible,  use a primitive collider like box collider instead. If that's not possible, see if you can use multiple box colliders to match the shape. If that's not possible, make a low poly mesh to use as a mesh collider.
