### ISSUE TITLE
How to compile game?

### ISSUE THREAD

**Issue by lmaochroch** [pokepetter/ursina#51]
Hi!
I have a problem with compiling a game.Its nothing fancy, just wanted to try it out. In the FAQ on the ursinaengine.org i found how to do it. I tried it and in just copied python. Nothing else. Can someone tell me what am i doing wrong? Thanks!

**Comment by DiamondsBattle** [comment]
Have you got an error and if not, what command are you executing ?
The right command is [`python -m ursina.build`](https://www.ursinaengine.org/cheat_sheet.html#build) executed in your program directory (Builds only for Windows for now)
For any other questions, feel free to join the [Ursina Discord Server](https://discord.gg/UtZ8Xju)

**Comment by lmaochroch** [comment]
It just copies python into the build directory. Wirhout compiling the script

**Comment by pokepetter** [comment]
Do you have a main.py file?

**Comment by pokepetter** [comment]
By the way, it doesn't actually compile anything. The script just movies Python, needed modules and the game into a folder. Python code gets compiled when you run it.

You might be able to use other python packaging tools as well, but you might have to specify what to include.

**Comment by lmaochroch** [comment]
Yes, i do have main.py file
