### ISSUE TITLE
Mouse Y position always return 0.015559285879135132 when no mouse movement

### ISSUE THREAD

**Issue by malonn23** [pokepetter/ursina#510]
I'm having trouble with the camera (first person controller) and the mouse y.  I'm on Fedora 37 Linux.  When the mouse is not moving, the mouse.y property returns 0.015559285879135132 all the time.  Furthermore, when using velocity, the mouse tends to move upwards towards the top of the screen (first person controller).  Lifting and setting down my mouse during movement always causes the mouse to jump up pretty sharply.  It's like the mouse is too sensitive on the y axis.  I've a half-ass workaround like so
```
y = mouse.y
if y == 0.015559285879135132:
    y = 0
```
But it's still very sensitive to lifting and placing back down the mouse, as well as simple button presses—the mouse always moves up.  It's like it wants to move up all the time.  I don't know if it's an OS issue or what, but it's annoying.

**Comment by pokepetter** [comment]
I had the bug where to camera rotated upwards too. It somehow happened because I set the initial window size in window.py. I did fix that though. Does this still happen in the most recent version from github?

**Comment by malonn23** [comment]
Haven't tried the GitHub code.  I found the problem to be (I believe) the mouse y position is set each frame to a number.  It should be reset to zero.  Let me check the latest code and see if it fixes it.  Post back in a bit...

**Comment by malonn23** [comment]
Yep, latest code fixed it.  Thanks pokepetter!
