### ISSUE TITLE
loader is not defined

### ISSUE THREAD

**Issue by mscheltienne** [pokepetter/ursina#511]
Here: https://github.com/pokepetter/ursina/blob/83cb3a3392e4d2f261e6c75354f908b6ca59b31a/ursina/texture_importer.py#L34

And here: https://github.com/pokepetter/ursina/blob/83cb3a3392e4d2f261e6c75354f908b6ca59b31a/ursina/texture.py#L23

The variable `loader` is not defined?

The following code snippet fails:

```
from ursina import load_texture

texture = load_texture("road.png", "/home/scheltie/Downloads/assets/")
```

And this is imported but unused: https://github.com/pokepetter/ursina/blob/83cb3a3392e4d2f261e6c75354f908b6ca59b31a/ursina/texture.py#L6

**Comment by mscheltienne** [comment]
Ok, but I really don't get how to load a texture from a full path. In my case, I would like to define a mini-game in a class defined in a package. Thus, I do not like the idea of putting the assets alongside the `.py` file. Instead, I prefer to put them in a resource folder in my package and provide the path to this folder via the `importlib` module:

```
from importlib.resources import files

texture = files("demo_realtime.feedbacks") / "resources" / "road.png"
```

But I can't figure out how to tell Ursina that the texture is at this *full-path*.

**Comment by pokepetter** [comment]
I don't recommend doing that. You're just making things more complicated for no reason. 
It's possible to load a texture with an absolute path with Texture(absolute_path), but again, there's no need to do that if you keep your project structure flat. It's also possible to modify application.asset_folder to change where ursina searches for assets.

**Comment by mscheltienne** [comment]
I did notice `application.asset_folder`, trying that one for now.. I'll try instantiating the Texture class directly too.
It looks to me like Ursina bases its search for assets on the *current working directory*. I can not guarantee what will be the current working directory at runtime for the class in a pip installed package. Not being able to provide the `texture` as the path to a file is not practical.
