### ISSUE TITLE
Is it possible to mark some input as consumed to stop input propagation

### ISSUE THREAD

**Issue by albfan** [pokepetter/ursina#518]
trying to isolate input to entities, all of the receives the input.

Probably it wont hurt to allow input to return a value (default would be None with no return) that way one can stop the propagation when right entity consume the data.

I can provide a patch if sounds good

**Comment by pokepetter** [comment]
Even if you make the entity "eat" the input, there's still a chance there's an entity before it in the list of entities and that will get run anyway. I guess if you're careful about the order it would work. Just implementing what you suggest wouldn't be hard though. Might be useful.

**Comment by pokepetter** [comment]
It should be obvious it's stopping the input propagation. Any suggestions for that? I don't think the behavior is going to be obvious if you just return `True` or something. Unless you add a comment every time 
```py
return True # stop input propagation```

**Comment by albfan** [comment]
yes, the order of entities listening is probably not warrantied, but we can test that

the concept of consumed input is pretty standard, I think people will get what that means

I think must be it:
```
diff --git i/ursina/main.py w/ursina/main.py
index ea10270..cde63a7 100644
--- i/ursina/main.py
+++ w/ursina/main.py
@@ -194,13 +194,16 @@ class Ursina(ShowBase):
                 continue
 
             if hasattr(entity, 'input') and callable(entity.input):
-                entity.input(key)
+                if entity.input(key):
+                    break
 
+            if consumed:
+                break
             if hasattr(entity, 'scripts'):
                 for script in entity.scripts:
                     if script.enabled and hasattr(script, 'input') and callable(script.input):
-                        script.input(key)
-
+                        if script.input(key):
+                            break
 
         mouse.input(key)
```

to show a practical usage of this, I extend some entities representing a nested menus:

```
 main
    start game
    settings
       controls
       video
       audio
    credits
```
 and just want to consume Esc key to go back to parent menu. It almost works, but I need the Esc to not be propagated to parent entity (or it will go to parent too) as my first entity consumed the input.
 
 I see lot of conditions on ursina games (if entity enabled and looks like this will help to deal with input more easily)
 
 Just if you see it helpful, I agreed with stay simple for this engine

**Comment by albfan** [comment]
This is how I deal with that example now:

Menu:
```
from ursina import *

class Menu(Entity):
    def __init__(self, parent_menu = None, **kwargs):
        super().__init__(**kwargs)
        self.parent_menu = parent_menu

    def on_toggle(self):
        pass

    def toggle(self):
        self.enabled = not self.enabled
        self.on_toggle()
        self.parent_menu.enabled = not self.parent_menu.enabled
```

and in general entity managing input:

```
        if key == "escape":
            for menu in (menu for menu in self.menus if (isinstance(menu, Menu) and menu.enabled)):
                menu.toggle()
                break
```

I would just prefer to deal with input on Menu, and toggle (disable current and enable parent) from Menu class itself

**Comment by albfan** [comment]
hmm, yes I see Animator in some menus. I was sure there should be a way to deal with that.

Will try to find other scenarios where set input as consumed might work better. Let me open the PR to discuss there

**Comment by albfan** [comment]
Let's review #526 (still on top of that mess I create. I can rework if you push force master to remove all form ursina history)
