### ISSUE TITLE
Is it possible to reload too other modules created for game?

### ISSUE THREAD

**Issue by albfan** [pokepetter/ursina#520]
I get this try to stay small and easy, but hot reloader for other modules looks like a great addition.

I just tried to modify a button text in another module, and saving main class no change is reflected

**Comment by pokepetter** [comment]
No, it currently only reloads `__main__`. I think automatically going through all the modules that's been imported and reloading could easily cause a lot of problems, and be slower too. A lot of the iteration speed with ursina comes from being able to just load the part of the game you're working on, so it doesn't get slow the bigger the project gets. Of course to test something in context, you'll probably have to load *some* of the stuff. 

It's possible to manually instantiate a HotReloader and point to the file you want it to reload, for example:
```py
custom_reloader = HotReloader(application.asset_folder / 'other_script.py')
```
You might run into issues if something in module a depends on something in module b though.

**Comment by albfan** [comment]
Yes, tried that, but I just get a blank window

I see other tries using importlib and honestly none works in all cases either

If you ever want to do something about this just let me know, I will be more than happy to test things.

Closing by now
