### ISSUE TITLE
ButtonList that never disable the selected item

### ISSUE THREAD

**Issue by albfan** [pokepetter/ursina#522]
I have some use case, but most  general would be to see all the time choose item in a difficulty level for a game:

```
easy
intermediate
hard
```

and don't want to use button_group.

I just workaround with this class wrapper (forcing `selection_marker` always enabled)

```
        class MyButtonList(ButtonList):
            def __init__(self, button_dict, **kwargs):
                super().__init__(button_dict, **kwargs)
            def input(self, key):
                super().input(key)
                self.selection_marker.enabled = True
```

but would be great if we have a property like `keep_select_highlight` in `ButtonList` instead of that workaround.

btw, that class wrapper start with first element selected, so it just works.

let me know if this looks interesting to open a PR, I'm ok if that's not the intention for this UI component

**Comment by pokepetter** [comment]
I added this, just set clear_selected_on_enable to False. I also added the ability to set .selected though code.
