### ISSUE TITLE
Using unicode

### ISSUE THREAD

**Issue by albfan** [pokepetter/ursina#523]
I see errors using unicode:

```
:text(warning): No definition in  for character U+2b06
```

for

```
Button("Up: ⬆")
```

tried to load config for panda, but unsuccesfully:

```
from panda3d.core import loadPrcFile
from panda3d.core import ConfigPageManager

print(ConfigPageManager.getGlobalPtr())

loadPrcFile('etc/config.prc')
```

where etc/config.prc contains:

```
text-encoding utf8
```

is it possible to use unicode characters?

**Comment by pokepetter** [comment]
It's possible if you use a font with support for those symbols. Different fonts have different amount of symbols. The easiest way to change font is:
```py
Text.default_font = 'unifont-15.0.01.otf'
```
Make sure to include the font file in the asset folder.

**Comment by albfan** [comment]
Got it from https://github.com/multitheftauto/unifont/releases and just works!

Cool
