### ISSUE TITLE
Prefab tilemap not included with pip

### ISSUE THREAD

**Issue by marcoslorhanbs** [pokepetter/ursina#531]
# Tilemap not inclued
I have installed ursina throught pip but when i tried to import the prefab tilemap it didnt find it because it was not downloaded or installed with pip

python_version = 3.8
i have tried update the ursina but doesnt solved
Any Idea?

**Comment by marcoslorhanbs** [comment]
# Issue Update
I have tried downloading the tilemap file from this repo but even with this solution we got a problem:
1. First: 'NoneType' object has no attribute 'width'
2. Second: self.grid = [[self.tilemap.get_pixel(x,y) for y in range(self.tilemap.height)] for x in range(self.tilemap.width)]

**Comment by pokepetter** [comment]
You have to give it a tilemap and a tileset: https://www.ursinaengine.org/api_reference.html#Tilemap. The default should be included in the repo though.
