### ISSUE TITLE
monitor /showbase resolution incompatiblity

### ISSUE THREAD

**Issue by ursinaguy** [pokepetter/ursina#543]
how to full-screen an ursina window when its resolution is less than monitor resolution
- tried Ursina(size=(x,x),fullscreen=True) but it still shows the app in a window

**Comment by imbomania** [comment]
from ursina import *

app = Ursina()
window.borderless = False 
window.size = 800, 600 
or
window.fullscreen = True 

window.show_ursina_splash = True

app.run()

**Comment by ursinaguy** [comment]
@imbomania  
your answer didnt work
i also tried 
window.fullscreen=true 
window.size= 800,600 
but it changes the monitor resolution and the  game is still a window ,
declaring window. size=800,600 first before window.fullscreen 
only full-screens the window but the resolution is changed to the monitor resolution

**Comment by pokepetter** [comment]
You can't have it be fullscreen in a lower resolution. 
You can change the display settings in your OS and set it to a lower resolution and then go fullscreen, but you'd get a blurry image. Monitors don't use nearest neighbor upscaling, so it doesn't look crisp.
If it's just of a visual effect, maybe this is what you want? https://github.com/pokepetter/ursina/blob/master/ursina/shaders/screenspace_shaders/pixelation_shader.py
