### ISSUE TITLE
Glow map /  emission map support in Ursina

### ISSUE THREAD

**Issue by ursinaguy** [pokepetter/ursina#550]
Is there any way to add an emissive texture (a texture that  glows in certain given areas ) to an entity in Ursina ?
If yes how to apply it ?
note : i need it to make power orbs , magical stuff etc... if there is any alternative sharing it would be appreciated

**Comment by IndividualCoder** [comment]
No bro, currently there is not glow map / emission map 
I'm also suffering from the same problem

**Comment by ursinaguy** [comment]
the game looks dead without glow maps, do you know any  good source to learn panda 3d emission mapping?

**Comment by IndividualCoder** [comment]
> the game looks dead without glow maps, do you know any good source to learn panda 3d emission mapping?

yes! panda's official docs site:https://docs.panda3d.org/1.10/python/programming/render-attributes/materials
I'd say if you don't know panda3d at all, you should learn panda3d from starting

**Comment by IndividualCoder** [comment]
well I know what you need! 
But you will have to rework on your models(maybe). https://docs.panda3d.org/1.10/python/programming/models-and-actors/attaching-objects-to-joints This link tells how to parent things to a cretain part of a mesh. You can use it to reparent your light to your moodel's area(where you want the light). You might have to read some pages before this page to get a full understanding.
I'm only 14 and from India so don't mind my english.

**Comment by ursinaguy** [comment]
@IndividualCoder thanks for your help again .
If you really want to be a contributor contact me on the following Gmail address  : pappapappa36912@gmail.com

**Comment by IndividualCoder** [comment]
> @IndividualCoder thanks for your help again . If you really want to be a contributor contact me on the following Gmail address : [pappapappa36912@gmail.com](mailto:pappapappa36912@gmail.com)

If you don't know how to add contributors to a github repo, watch this video: https://youtu.be/LhSYiHKlSI4
