### ISSUE TITLE
Gun recoil not working with FPC.

### ISSUE THREAD

**Issue by IndividualCoder** [pokepetter/ursina#551]
I tried using camera.rotation to simulate recoil for my FPS game but it didn't worked. The camera seems to glitched out. I've done some experiments to find out how FPC works. Looks like it does not changes camera's rotation. Idk how it works please tell me and help me. Also another request, Please add materials to the engine. 

Also I am making a GUI engine for ursina to make it easier to use. When it's done, I public the code On my repo and in this chat

**Comment by Tanay-ErrorCode** [comment]
@IndividualCoder Can you give us some code, so we can, fix your problem?

**Comment by vvvvvvitor** [comment]
I feel like this should be closed as it's not really an issue with the engine itself, or it doesn't seem like one.

**Comment by IndividualCoder** [comment]
Got it
