### ISSUE TITLE
Using Tkinter with Ursina

### ISSUE THREAD

**Issue by zachyboy12** [pokepetter/ursina#553]
Hi,
I am making a program that allows you to make games without coding, and I need to use `tkinter` because it has very helpful widgets and geometry managers.
So how can you put `ursina` in a frame in a `tkinter` window?
Thank you!

**Comment by Plizik** [comment]
probably impossible since they use kinda the same methods of creating windows. but if i find one i'll tell

**Comment by PythonicHTML** [comment]
You could try modifying the Ursina window to remove the close button and then center the it over a fullscreen Tkinter window. You could then use Tkinter widgets to modify the Ursina scene. Not sure if it would work correctly (with Ursina and Tkinter having separate update loops) but it might be worth a try.
