### ISSUE TITLE
Separate camera rendering. It is even possible?

### ISSUE THREAD

**Issue by IndividualCoder** [pokepetter/ursina#556]
I am making a 3d game engine (my repo "Ursina editor"). I want UI elements  like unreal engine. World renders by a separate camera and UI elements by a different camera. It happens in ursina by defalut  but items rendered by UI camera are stick on top of world camera. I want them to take their own space in the world (like camera takes half of the screen and ui camera takes other half). Can you help me.
![InEditorTesting_Topic](https://github.com/pokepetter/ursina/assets/121798131/a56ba677-d36e-4591-a3cd-81866a37588c)
Like in this pic, blue area is rendered by world cam. red area is rendered by UI cam. Can we get same results in ursina
BTW Thanks in advance.

**Comment by pokepetter** [comment]
Currently, no. But you could just cover up the scene view with UI.

**Comment by IndividualCoder** [comment]
got it
used panda's display region. thanks btw
