### ISSUE TITLE
light.py Raises error when DirectionalLighting is used.

### ISSUE THREAD

**Issue by PythonicHTML** [pokepetter/ursina#558]
```
DirectionalLight(parent=pivot, y=2, z=3, shadows=True)
```

Creating directional light as shown above results in this error:
```
C:\\ursina\lights.py", line 27, in __init__
    render.setLight(self.attachNewNode(self._light))
NameError: name 'render' is not defined
```

I checked lights.py and there is, indeed, no other mention of "render." 

Thanks in advance.

**Comment by pokepetter** [comment]
Please post full code to reproduce it.
My guess is that you forgot to instantiate Ursina before DirectionalLight

**Comment by PythonicHTML** [comment]
That was the issue, thanks.
