### ISSUE TITLE
Lighting not work

### ISSUE THREAD

**Issue by milen-prg** [pokepetter/ursina#561]
I'm on Windows 10 Pro 64bit, with updated Python 3.11, panda3d and ursina.
I try basic lighting example:

`from ursina import *
from ursina.shaders import lit_with_shadows_shader # you have to apply this shader to enties for them to receive shadows.

app = Ursina()

EditorCamera()

Entity(model='plane', scale=10, color=color.gray, shader=lit_with_shadows_shader)
Entity(model='cube', y=1, shader=lit_with_shadows_shader)

pivot = Entity()

DirectionalLight(parent=pivot, y=2, z=3, shadows=True)
AmbientLight(parent=pivot, y=2, z=3, shadows=True)

app.run()
`

But the result is:

![изображение](https://github.com/pokepetter/ursina/assets/59639866/655c7d3a-1232-4d49-be76-239b24b5512a)

The message in the console is:

package_folder: C:\Python311\Lib\site-packages\ursina
asset_folder: C:\Users\mlap\Documents\ursinas
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
:prc(warning): changing default value for ConfigVariable paste-emit-keystrokes from '1' to '0'.
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
os: Windows
development mode: True
application successfully started
info: changed aspect ratio: 1.779 -> 1.779
info: changed aspect ratio: 1.779 -> 1.779

Other Ursina examples (most of them) works, the pure Panda 3d lighting works fine, but this, why?!
I have OpenGL 4.3.

**Comment by pokepetter** [comment]
This shader uses GLSL version 150. Maybe that's not supported by your system? You could try a different version to see if that works. I have OpenGL 4.6.0 and it works there at least.

I think most of these shader issues with incompatible version/system will disappear when panda3d's new shader pipeline gets released.

**Comment by milen-prg** [comment]
But  GLSL version 150 uses OpenGL 3.2. On my system OpenGL 4.3 works fine, with Panda3D directly and many others 3d libraries I play with different shaders, lighting, etc.
Can I change some settings of the Ursina without access its source?

**Comment by pokepetter** [comment]
No, you'd have to change it in the source code. Shaders are in ursina/shaders/. I have never encountered problems with shaders myself, so it's hard for me to say what the cause could be.
