### ISSUE TITLE
Make ursina.build via Nuitka

### ISSUE THREAD

**Issue by nyakokitsu** [pokepetter/ursina#564]
Meow

**Comment by pokepetter** [comment]
?
If you want to use nuitka, can't you just use nuitka?

**Comment by nyakokitsu** [comment]
> ? If you want to use nuitka, can't you just use nuitka?

Wouldn't it be better to implement nuitka in yursina.build in order to protect the built applications from decompilation and allow building on all platforms?

**Comment by pokepetter** [comment]
Single executable isn't that great for games anyway since it makes it harder to patch. I know you don't have to do that ,but still. My question is, what's the point of making ursina.build use nuitka when you could just use nuitka?

**Comment by nyakokitsu** [comment]
Multi platform for example

**Comment by pokepetter** [comment]
If you want to use nuitka, just use nuitka. Having ursina.build use nuitka doesn't make any sense when you can just call nuitka directly.
