### ISSUE TITLE
FirstPersonController camera is clipping up on Arch Linux 

### ISSUE THREAD

**Issue by youshitsune** [pokepetter/ursina#566]
When I try to run FPS sample and Minecraft clone sample game works normally until I move my mouse. Then camera automatically clips up. First I had warning for xf86dga and installed libxxf86dga from AUR. But camera is still clipping.

**Comment by youshitsune** [comment]
It works on LXDE, but I don't understand why doesn't it work on DWM.

**Comment by y2bad** [comment]
Is your window borderless? If yes this could cause the issue. Try disabling it by setting `window.borderless` to False.

**Comment by youshitsune** [comment]
I've set ``window.borderless = False`` and it now works.
