### ISSUE TITLE
Add variables for editor ui labels

### ISSUE THREAD

**Issue by sir-vladimir** [pokepetter/ursina#577]
![image](https://github.com/pokepetter/ursina/assets/69652964/1198b306-08c5-49ad-9a2e-9dd9c728ad7e)
```
# Does not disable labels
window.entity_counter.enabled = False
window.collider_counter.enabled = False
# Disables entire ui
window.editor_ui.disable()
```
I would call this a bug / missing feature
It's easy to fix but should be included in the library

**Comment by y2bad** [comment]
why would you need this?

**Comment by pokepetter** [comment]
Done.
