### ISSUE TITLE
How to set maximum and minimum zoom of an entity in using EditorCamera()? 

### ISSUE THREAD

**Issue by Sonarjit** [pokepetter/ursina#582]
I want to set a maximum and minimum zoom limits of an entity in my ursina app. I use to EditorCamera() attribute to rotate and zoom the object. How can I set the zoom limits?

**Comment by y2bad** [comment]
The thing is EditorCamera doesn't change the entities it just moves and rotates the camera around a pivot.
If you want to limit how much you can zoom you probably have to modify the source of EditorCamera.

**Comment by pokepetter** [comment]
```py
from ursina import *

app = Ursina()

Entity(model='cube')

ec = EditorCamera()
def update():
    ec.target_z = clamp(ec.target_z, -10, -2)

app.run()
```
