### ISSUE TITLE
Can networking.py make WAN connections?

### ISSUE THREAD

**Issue by IndividualCoder** [pokepetter/ursina#585]
I want to ask if the networking of the engine can be used to make global games AKA can it be used to make WAN  connections?

**Comment by IndividualCoder** [comment]
Getting it on discussions tab

**Comment by IndividualCoder** [comment]
Was left unanswered on discussions tab

**Comment by ursinaguy** [comment]
I dont know about about the engine-provided networking but you can do a functional local online and splitscreen multiplayer using python socket and pickle library .
here is a link to a good series that explains how to do so :
https://www.youtube.com/watch?v=_fx7FQ3SP0U&list=PLzMcBGfZo4-kR7Rh-7JCVDN8lm3Utumvq

**Comment by IndividualCoder** [comment]
want to integrate intworking in ursina editor so me and my friend can make games together without any issue with distance

**Comment by ursinaguy** [comment]
An easier solution would be to  use the Code With Me plugin in PyCharm which enables real time remote python coding for you and your friends .

**Comment by IndividualCoder** [comment]
We don't want to "code" by just writing seamlessly. I am making a game editor like unity or godot where you can work graphically

**Comment by pokepetter** [comment]
I don't know, I didn't make the networking. Did you try?
I assume you can though.

Also, please update the title as it's not very descriptive.

**Comment by IndividualCoder** [comment]
> I don't know, I didn't make the networking. Did you try? I assume you can though.
so who made it, ask them if it can make global connections please

**Comment by Squigglecito** [comment]
The networking can make connections across WAN.

**Comment by IndividualCoder** [comment]
> The networking can make connections across WAN.

how?? any example code?

**Comment by IndividualCoder** [comment]
ok, thank you very much

**Comment by IndividualCoder** [comment]
ok, thank you very much
