### ISSUE TITLE
 Error  for panda 3d setTexture()

### ISSUE THREAD

**Issue by ursinaguy** [pokepetter/ursina#589]
I am trying to apply a glow map on my model using panda 3d method mentioned in panda3d documentation https://docs.panda3d.org/1.10/python/programming/texturing/texture-modes

here is my code : 

`from settings import *
from map_generator import *
from camera_animation import *
from HUD  import  *
from direct.showbase.ShowBase import ShowBase
from ursina.shaders import lit_with_shadows_shader
from panda3d.core import loadPrcFileData
from panda3d.core import Texture as PandaTexture
from panda3d.core import SamplerState
from panda3d.core import Filename
from panda3d.core import PNMImage
from pathlib import Path
from direct.showbase import Loader

app = Ursina(vsync= True )
scene.setShaderAuto()
Entity.default_shader = lit_with_shadows_shader
Ground = Entity( model="cube" , collider= "box" ,rotation= (0,0,0),scale =(500,0,500),position = (0,0.49,50) ,texture="resources/textures/dirt.png",texture_scale=(300,300))

cube = load_model("CUBE")
cube.setPos(0,5,5)
cube.reparent_to(scene)
ts = TextureStage("ts")
ts.setMode(TextureStage.MModulateGlow)
cube.setTexture(ts,load_texture("Baked_Light.png"))

EditorCamera()
def update() :
   pass
app.run()
`

the Error  
TypeError: Arguments must match:
set_texture(const NodePath self, Texture tex)
set_texture(const NodePath self, TextureStage stage, Texture tex)
set_texture(const NodePath self, Texture tex, const SamplerState sampler)
set_texture(const NodePath self, Texture tex, int priority)
set_texture(const NodePath self, TextureStage stage, Texture tex, const SamplerState sampler, int priority)
set_texture(const NodePath self, TextureStage stage, Texture tex, int priority)
set_texture(const NodePath self, Texture tex, const SamplerState sampler, int priority)

Process finished with exit code 1

**Comment by ursinaguy** [comment]
@pokepetter i think you changed its name when making Ursina just like you changed loader.loadmodel() into load_model()
if that is true can you tell us the new name as i dont seem to find it

**Comment by IndividualCoder** [comment]
you should ask this on the community section of the panda3d.org because they know the code deeply as the wrote it
