### ISSUE TITLE
ursina does not install

### ISSUE THREAD

**Issue by pem120** [pokepetter/ursina#597]
log
Collecting ursina
  Obtaining dependency information for ursina from https://files.pythonhosted.org/packages/2c/ca/15c417ef8cd0d35a9911b4f32d6470c32b5806352ed1eba1a32489a8dd14/ursina-6.1.2-py3-none-any.whl.metadata
  Using cached ursina-6.1.2-py3-none-any.whl.metadata (4.9 kB)
INFO: pip is looking at multiple versions of ursina to determine which version is compatible with other requirements. This could take a while.
  Obtaining dependency information for ursina from https://files.pythonhosted.org/packages/de/64/54ea475b7f550b6586e76e77b5c793f76fb7cc3a3f0fe74e3af6dd5f0a67/ursina-6.1.1-py3-none-any.whl.metadata
  Using cached ursina-6.1.1-py3-none-any.whl.metadata (4.9 kB)
  Obtaining dependency information for ursina from https://files.pythonhosted.org/packages/3d/5b/b0336f5731b87192d001fde6ae5d0a96946101a38d20f06e749145c26ef7/ursina-6.1.0-py3-none-any.whl.metadata
  Using cached ursina-6.1.0-py3-none-any.whl.metadata (4.9 kB)
  Obtaining dependency information for ursina from https://files.pythonhosted.org/packages/db/a8/97b3fd9aac086c1d00a6b7dca593570f0fb3cc385c778df9e6df1cce7299/ursina-6.0.0-py3-none-any.whl.metadata
  Using cached ursina-6.0.0-py3-none-any.whl.metadata (4.9 kB)
  Using cached ursina-5.3.0-py3-none-any.whl (2.4 MB)
  Using cached ursina-5.2.0-py3-none-any.whl (2.4 MB)
  Using cached ursina-5.1.0-py3-none-any.whl (5.2 MB)
  Using cached ursina-5.0.0-py3-none-any.whl (2.4 MB)
INFO: pip is still looking at multiple versions of ursina to determine which version is compatible with other requirements. This could take a while.
  Using cached ursina-4.1.1-py3-none-any.whl (1.3 MB)
  Using cached ursina-4.1.0-py3-none-any.whl (1.3 MB)
  Using cached ursina-4.0.0.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from ursina)
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/98/d7/1cc7a11118408ad21a5379ff2a4e0b0e27504c68ef6e808ebaa90ee95902/numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata
  Using cached numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting ursina
  Using cached ursina-3.6.0-py3-none-any.whl (1.1 MB)
  Using cached ursina-3.5.0-py3-none-any.whl (1.1 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached ursina-3.4.0-py3-none-any.whl (1.1 MB)
  Using cached ursina-3.3.1-py3-none-any.whl (1.1 MB)
  Using cached ursina-3.3.0-py3-none-any.whl (1.1 MB)
  Using cached ursina-3.2.2-py3-none-any.whl (1.1 MB)
  Using cached ursina-3.1.2-py3-none-any.whl (1.0 MB)
  Using cached ursina-3.1.1.tar.gz (969 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached ursina-3.1.0-py3-none-any.whl (1.0 MB)
  Using cached ursina-3.0.0-py3-none-any.whl (2.3 MB)
  Using cached ursina-0.3-py3-none-any.whl (1.0 MB)
  Using cached ursina-0.2-py3-none-any.whl (1.0 MB)
ERROR: Cannot install ursina==0.2, ursina==0.3, ursina==3.0.0, ursina==3.1.0, ursina==3.1.1, ursina==3.1.2, ursina==3.2.2, ursina==3.3.0, ursina==3.3.1, ursina==3.4.0, ursina==3.5.0, ursina==3.6.0, ursina==4.0.0, ursina==4.1.0, ursina==4.1.1, ursina==5.0.0, ursina==5.1.0, ursina==5.2.0, ursina==5.3.0, ursina==6.0.0, ursina==6.1.0, ursina==6.1.1 and ursina==6.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    ursina 6.1.2 depends on panda3d
    ursina 6.1.1 depends on panda3d
    ursina 6.1.0 depends on panda3d
    ursina 6.0.0 depends on panda3d
    ursina 5.3.0 depends on panda3d
    ursina 5.2.0 depends on panda3d
    ursina 5.1.0 depends on panda3d
    ursina 5.0.0 depends on panda3d
    ursina 4.1.1 depends on panda3d
    ursina 4.1.0 depends on panda3d
    ursina 4.0.0 depends on panda3d
    ursina 3.6.0 depends on panda3d
    ursina 3.5.0 depends on panda3d
    ursina 3.4.0 depends on panda3d
    ursina 3.3.1 depends on panda3d
    ursina 3.3.0 depends on panda3d
    ursina 3.2.2 depends on panda3d
    ursina 3.1.2 depends on panda3d
    ursina 3.1.1 depends on panda3d
    ursina 3.1.0 depends on panda3d
    ursina 3.0.0 depends on panda3d
    ursina 0.3 depends on panda3d
    ursina 0.2 depends on panda3d

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by y2bad** [comment]
use python 3.10

**Comment by pokepetter** [comment]
3.12 is not supported yet by panda3d. It will probably be soon, but for now, use an older version of Python.
