### ISSUE TITLE
Package resources are accessed from path

### ISSUE THREAD

**Issue by ergoithz** [pokepetter/ursina#6]
Accesing package resources from filesystem is considered bad practice as it won't allow the package to be zip_safe (unable to use the package in compressed mode), breaking application 'freeze' functionality (heavily used by python commercial applications) as provided by nuitka standalone, cx_freeze, py2exe/py2app, etc.

Those calls could be either be replaced by importlib.resources/importlib_resources or, alternatively, implementing a configurable resource loader whith appropriate hooks to do so.

**Comment by pokepetter** [comment]
I haven't looked into this properly yet, but making a nuitka standalone does seem to work.
