### ISSUE TITLE
How to draw lines and curves to use in trajectories ?

### ISSUE THREAD

**Issue by Areiban** [pokepetter/ursina#60]
Hello, my name is Adrian and I'm very happy to work with your amazing project; but I have some dudes with respect to work with physics and plot lines to visualice trajectories for the actors

**Comment by pokepetter** [comment]
You can make a Mesh with render mode 'line':
```python
points = [Vec3(0,0,0), Vec3(0,.5,0), Vec3(1,1,0)]
curve_renderer = Entity(model=Mesh(vertices=points, mode='line'))
```
Another example:
```python
# get points using the curve.in_out_sine function with a resolution of 32
curve_renderer = Entity(model=Mesh(vertices=[Vec3(i / 31, curve.in_out_sine(i / 31), 0) for i in range(32)], mode='line', thickness=2))
```
You can also give it a list of colors if you want that too.
For varying thickness you can use the Prismatoid class.

**Comment by Areiban** [comment]
> You can make a Mesh with render mode 'line':
> 
> ```python
> points = [Vec3(0,0,0), Vec3(0,.5,0), Vec3(1,1,0)]
> curve_renderer = Entity(model=Mesh(vertices=points, mode='line'))
> ```
> 
> Another example:
> 
> ```python
> # get points using the curve.in_out_sine function with a resolution of 32
> curve_renderer = Entity(model=Mesh(vertices=[Vec3(i / 31, curve.in_out_sine(i / 31), 0) for i in range(32)], mode='line', thickness=2))
> ```
> 
> You can also give it a list of colors if you want that too.
> For varying thickness you can use the Prismatoid class.

Thank you so much =)...  
By the way , I want to ask you if the API somehow provides functions for working with physics and Path Finding?

**Comment by DiamondsBattle** [comment]
To work with Physics you can use [Panda3D's Bullet World](https://docs.panda3d.org/1.10/python/programming/physics/bullet/hello-world). I am considering adding it to ursina in a simpler way.
