### ISSUE TITLE
NameError: name 'Ursina' is not defined

### ISSUE THREAD

**Issue by Desiro444** [pokepetter/ursina#61]
Hello,

I installed Ursina using pip (pip install ursina) and checked that it was there using pip list, however when running the example code on [this page](https://www.ursinaengine.org/ursina_for_dummies.html), I get this error:

Traceback (most recent call last):
  File "[redacted]", line 1, in <module>
    from ursina import *                    # Import the ursina engine
  File "[redacted]", line 3, in <module>
    app = Ursina()                          # Initialise your Ursina app
NameError: name 'Ursina' is not defined

Code:
from ursina import *                    # Import the ursina engine

app = Ursina()                          # Initialise your Ursina app
app.run()                               # Run the app

I don't know where I have gone wrong. Any help appreciated, cheers.

edit: removed code formatting as it isn't exactly working as i hoped it would.

**Comment by DiamondsBattle** [comment]
Is the problem fixed ? Otherwise try reinstalling it (``pip install ursina --upgrade``) or try installing the dev version (``pip install git+https://github.com/pokepetter/ursina --upgrade``).

**Comment by Desiro444** [comment]
> Is the problem fixed ? Otherwise try reinstalling it (`pip install ursina --upgrade`) or try installing the dev version (`pip install git+https://github.com/pokepetter/ursina --upgrade`).

Problem still persists. Just checked, can confirm this isn't a pip problem.

**Comment by DiamondsBattle** [comment]
Try checking if the first import in ``C:\Users\[redacted]\AppData\Local\Programs\Python\Python[version]\Lib\site-packages\ursina\__init__.py`` is ``from ursina.main import Ursina`` and that in the ``main.py`` file a class ``Ursina(ShowBase)`` exists.

**Comment by Desiro444** [comment]
> Try checking if the first import in `C:\Users\[redacted]\AppData\Local\Programs\Python\Python[version]\Lib\site-packages\ursina\__init__.py` is `from ursina.main import Ursina` and that in the `main.py` file a class `Ursina(ShowBase)` exists.

Both exist.

**Comment by DiamondsBattle** [comment]
Try not using vev if you are.

**Comment by DiamondsBattle** [comment]
Fixed ?

**Comment by DiamondsBattle** [comment]
That's pretty strange 🤔... If you weren't using ``venv`` you could try using it.

**Comment by Desiro444** [comment]
Tested on home computer, worked. Only difference between the two was the python version - it appears ursina does not work on python 3.8.

tl'dr: use python 3.7 and not 3.8.

Closing issue as problem is "fixed".

**Comment by dprajapati199** [comment]
It's not working on my machine first time, I just change my file name which i running the code from ursina.py to main.py and now it's works, also i m running it on venv enviroment. I think you also make naming mistake

**Comment by DeFiDegenDude** [comment]
**no module named ursina**
