### ISSUE TITLE
Converting ui cordinates into entity cordinates

### ISSUE THREAD

**Issue by Gabrielcmf** [pokepetter/ursina#63]
Is there a function or some easy way to do this ? I tried to get the ratio between the mouse ui cords and an entity's cords but the resulting ratio was never consistent.

Any help is appreciated

**Comment by pokepetter** [comment]
What are you trying to do? Is mouse.point maybe what you want? That way you can get the mouse position relative to the entity.

**Comment by Gabrielcmf** [comment]
> What are you trying to do? Is mouse.point maybe what you want? That way you can get the mouse position relative to the entity.

I'm trying to create a "interface" of sorts, so maps can be made mostly without coding, the mouse would be used to create rectangular entities, by clicking in two different spots and using the coordinates to get width, height and the x and y.

I tried using mouse.point and mouse.world.point before, but they always be None, do both of the .point functions always need an object as reference?

**Comment by pokepetter** [comment]
The easiest is just to create a big quad with a collider and use mouse.world_point. It needs a collider for the mouse ray to hit it.
```
camera.orthographic = True
plane = Entity(model='quad', color=color.azure, z=10, collider='box', scale=100) # create an invisible plane for the mouse to collide with

def input(key):
    if key == 'left mouse down':
        e = Entity(model='quad', position=mouse.world_point, z=0)

```

**Comment by Gabrielcmf** [comment]
I will try the above and see if it solves my problem. Also, how does input() work  ? Whenever I try to use it I'm always met with and error in the likes of "Name key not defined", while in the api reference and the example above it is not defined, leaving me confused on how it works

**Comment by pokepetter** [comment]
Don't forget the `key` parameter.

Whenever you press a key, ursina tries to call input('the_key_you_pressed') on all the entities and `__main__`.
For input in `__main__` like above you only need `def input(key):`, and if it's in a class inheriting Entity it's `def input(self, key):`

**Comment by Gabrielcmf** [comment]
Ok, now I understand it

**Comment by Gabrielcmf** [comment]
It's working know, the coordinate conversion is pin point, thank you for you help, I will close the issue now
