### ISSUE TITLE
Screen Tearing [macOS 10.15.6]

### ISSUE THREAD

**Issue by JT-Potato** [pokepetter/ursina#64]
I've followed the default example (And tweaked the window settings a bit), but I noticed some screen tearing.

I thought Vsync would fix the issue, so I enabled it (Even though it looks like it's on by default) and it didn't work. Just for kicks, I turned off Vsync, and it still was the same.

Could anyone help me? (I can't get screenshots of the screen tearing, it's a bit hard to do that), but I can give you my code.

**Comment by DiamondsBattle** [comment]
Do you mean your frames 'cut' in half or is your framerate not constant ?

**Comment by JT-Potato** [comment]
Cut. It's as if it were combining the top half of 1 frame and the bottom half of the next or something

**Comment by DiamondsBattle** [comment]
Usually VSync corrects that, could be that VSync is not supported by your computer.

**Comment by JT-Potato** [comment]
I highly doubt it because the games that I play show a considerable difference between VSync and not VSync.
(And my GPU supports VSync)

**Comment by DiamondsBattle** [comment]
Did you try your code on Windows ? Could you show your code ?

**Comment by JT-Potato** [comment]
Yes I did try on Windows, it was completely fine.

My code is split up into multiple files, but here are my settings for the window:
```
from ursina import *

def styling():
    window.borderless = False
    window.vsync = True
    window.title = "Unnamed Game"
    window.size = (1920, 1080)
    window.fullscreen = False
    window.exit_button.visible = False
    window.color = color.rgb(54,199,242)
    window.show_ursina_splash = False
```
