### ISSUE TITLE
Mouse Velocity Issues - macOS [10.15.6]

### ISSUE THREAD

**Issue by JT-Potato** [pokepetter/ursina#65]
Here I am with another macOS related issue.

I have 2 computers, one running Windows, and one running macOS.  I wanted to make a first-person game, so I locked the mouse and took the velocity as the input for how the camera is rotated. It works fine on Windows - buttery smooth. On macOS, it is far more jittery, and some times the view just "jumps" to a completely different orientation. Are there any workarounds for this? Or is there a simple fix I'm not aware of?

EDIT:
I found that the velocity just spikes, even though it should be a semi-constant movement. While moving, `mouse.velocity` is nearly always 0 on every axis. Without mouse locking, it behaves the same - except the mouse is obviously not locked.

EDIT 2:
I don't understand why it's even happening - mouse.py looks fine to me. The only reason it would return 0 is if the mouse wasn't moving.

EDIT 3:
If more than one instance of `update()` is running at the same time, it could just be constantly setting the mouse to 0 before any script has a chance to read a value???? I'm not good at Python, but I do want this to work. I hope someone has a solution...

**Comment by DiamondsBattle** [comment]
**Reply to your Discord message :**
It is simply not possible to speed up the calling of ``update()``, since it is called every frame. You could try working it out using ``threading`` with a custom function.
