### ISSUE TITLE
Typo on documentation Entity Basics - Other Magic Functions

### ISSUE THREAD

**Issue by Progman2002** [pokepetter/ursina#652]
Typo on https://www.ursinaengine.org/entity_basics.html at the bottom:

> Sometimes you want side effects when you enable/disable and entity, ...

Should be

> Sometimes you want side effects when you enable/disable an entity, ...

**Comment by Maksim-Karpov** [comment]
I think, the documentaion isn't being updated anymore.

**Comment by pokepetter** [comment]
Fixed in the source. Will be fixed on the live page after the next release.
