### ISSUE TITLE
Graphics issues when converting to .exe

### ISSUE THREAD

**Issue by Dinorigami-SLHIIDE-dev** [pokepetter/ursina#659]
I made a game using Ursina, followed [this](https://www.ursinaengine.org/building.html) guide to convert my game to EXE format using auto-py-to-exe. This is what the game looks like when I run my script on VS Code : 
![image](https://github.com/pokepetter/ursina/assets/135609438/d2778054-93bb-4443-ab31-cbf74dd6eaa2)

Unfortunately, the .alpha property of entities does not seem to work and the icons of button entities are flattened and are not well-positioned.

![image](https://github.com/pokepetter/ursina/assets/135609438/8c092e2c-9c57-4641-8038-35749b310cd8)

Also we cant change the "enabled" property in mid-game, it is only set at the beginning and does not seem to be changed.

Any ideas?

**Comment by developer-1v** [comment]
That's not good. I can probably help but haven't ran across these issues myself. Can you create a MRE Minimal Reproducible Example (and build it into an .exe). Then I can build the same one over here and try to diagnose.

**Comment by Dinorigami-SLHIIDE-dev** [comment]
I managed to solve it . The auto-py-to-exe did not use the same python version (v3.11.2) as the Visual Studio Code interpreter and some functions were probably not supported in python 3.10.
