### ISSUE TITLE
Ursina Build too little info

### ISSUE THREAD

**Issue by alseenwalnoot** [pokepetter/ursina#660]
Ursina build to convert has almost no documentation, How do i use it?? Have been a long time user of Ursina but i just cant figure out how to do it. I always just stuck with the old auto-py-to-exe but its really anoying to use. the problem exists within how do i include my own seperate scripts (for example a script called library.py)

Thanks in advance :)

**Comment by pokepetter** [comment]
You cd to your project directory and write `python -m ursina.build`. There's documentation here: https://www.ursinaengine.org/building.html#Building%20Your%20App%20with%20ursina.build
All scripts in the project folder will be automatically included, so you don't have think about that.
