### ISSUE TITLE
Feature - allow the Audio class to allow .mp3 files. 

### ISSUE THREAD

**Issue by lucaheyworth** [pokepetter/ursina#666]
![Grapply](https://github.com/pokepetter/ursina/assets/162014348/22568d6f-fd43-41a1-873f-3a6b5f78219d)

He says:
 **"I want to be able to play a mp3 file without converting it to wav so please allow .mp3 files to be sutible to play.
I love Ursina and I am making a game that I plan to release on steam so I don't want to ask for too much but I'm not too keen on converting audio files so right now I have 2 choices: 1.Use pygame, I don't want to have to many imports and pygame is another game engine. 2. Convert the file, it is a big audio file (BIG BIG) so that might take a while. I have huge hopes for Ursina I think it will become a MASIVE game engine!**

**Comment by pokepetter** [comment]
,mp3 is supported. If it doesn't work, try converting it to .ogg. This can be automated with Python. .ogg is simply better in every way, it's smaller and better quality.
