### ISSUE TITLE
Remove all entities

### ISSUE THREAD

**Issue by lucaheyworth** [pokepetter/ursina#667]
I want to remove all entities when level 2 is finished

My code for spawning entities:

```
class levels:
    if current_level == 1:
        Platform((7, 5))
        Grapple((11, 8))
        Platform((13, 7))
        Platform((17, 10))
        Platform((-15, 17))
        Platform((-12, 22))
        SuperGrapple((-7, 16))
        Platform((-5, 12))
        Platform((5, 21))
        Grapple((5, 23))
        Platform((0, 18))
        Platform((12, 25))
        Platform((9, 28))
        Platform((17, 34))
        Platform((-17, 36))
        Grapple((8, 42))
        Platform((12, 39))
        Platform((5, 41))
        EleKill((-17, 39), (1))
        Platform((-3, 38))
        Platform((-1, 43))
        Platform((-2, 48))
        SuperGrapple((0, 45))
        Platform((16, 44))
        Platform((-15, 41))
        Platform((-7, 51))
        Platform((11, 50))
        Platform((15, 52))
        Grapple((13, 51))
        Platform((-17, 57))
        Platform((-11, 55))
        Platform((9, 60))
        Platform((4, 62))
        Grapple((5, 63))
        EleKill((17, 58), (2))
        Platform((0, 68))
        Platform((-15, 73))
        Grapple((-7, 74))
        Platform((3, 76))
    elif current_level == 2:
        Platform((6, 7))
        EleKill((0, 0), 2)
            
levels()
```
This is in the update function
My code for removing entities(that doesn't work):
```
    if current_level == 1 and player.y > 75:
        scene.clear()
        camera.y = 0
        global code_ran_2
        if not code_ran_2:
            mixer.init()
            mixer.Sound("Python\\Grapplax\\Game over.mp3").play()
            code_ran_2 = True
        current_level = 2
        levels()
```

If you wan't to see full code go to https://github.com/lucaheyworth/Grapplax/blob/main/Grapplax.py

**Comment by LOUKOUKOU** [comment]
You can add all the levels to an object in the levels function, something like this

`
class levels:
    level = []
    current_level = 0
    setLevel(_current_level) 
      if current_level == 1:
        return (
        Platform((7, 5)),
        Grapple((11, 8)),
        Platform((13, 7)),
        Platform((17, 10)),
        Platform((-15, 17)),
        Platform((-12, 22)),
        SuperGrapple((-7, 16)),
        Platform((-5, 12)),
        Platform((5, 21)),
        Grapple((5, 23)),
        Platform((0, 18)),
        Platform((12, 25)),
        Platform((9, 28)),
        Platform((17, 34)),
        Platform((-17, 36)),
        Grapple((8, 42)),
        Platform((12, 39)),
        Platform((5, 41)),
        EleKill((-17, 39), (1)),
        Platform((-3, 38)),
        Platform((-1, 43)),
        Platform((-2, 48)),
        SuperGrapple((0, 45)),
        Platform((16, 44)),
        Platform((-15, 41)),
        Platform((-7, 51)),
        Platform((11, 50)),
        Platform((15, 52)),
        Grapple((13, 51)),
        Platform((-17, 57)),
        Platform((-11, 55)),
        Platform((9, 60)),
        Platform((4, 62)),
        Grapple((5, 63)),
        EleKill((17, 58), (2)),
        Platform((0, 68)),
        Platform((-15, 73)),
        Grapple((-7, 74)),
        Platform((3, 76))
        )
    elif current_level == 2:
        return (Platform((6, 7)),
        EleKill((0, 0), 2))
       .... 
     def setLevel(level): 
        current_level = level
        for c in level:
          destroy(c)
       level = setLevel(current_level)
`

And then you call the levels once, and just call setLevel when you want to go to the next level.
Though, instead of the if statement, I'd probably use a config file
