### ISSUE TITLE
how to load multi textures for one model

### ISSUE THREAD

**Issue by billyboo84** [pokepetter/ursina#672]
I want an FPS with Ursina and I'm trying to put several textures on a single entity but I don't know how to do it.
here is my code

```
texture1=load_texture("step1f.png")
texture2=load_texture('graytall.png')


test=Entity(model='e1m2', collider='mesh', scale=200,texture=[texture1,texture2])
```

it would be great if someone could help me

**Comment by pokepetter** [comment]
You can't. You either have to use an atlas texture/trim sheet, or you have to use multiple entities.
