### ISSUE TITLE
Cannot build to exe because of module not found error

### ISSUE THREAD

**Issue by ZombiesLoveZGames** [pokepetter/ursina#673]
I tried to convert my multi-file project to exe using pyinstaller and auto-py-to-exe and searched for advice but nothing works, the program keeps raising the error:
Module object for pyimod02_importers is NULL
I have read [https://www.ursinaengine.org/building.html#Building%20Your%20App%20with%20ursina.build](url) but I get even more errors. I do not use any other external modules other than ursina.
Any help will be appreciated

**Comment by pokepetter** [comment]
Maybe this issue can help? https://github.com/pokepetter/ursina/issues/671

**Comment by Leonmmcoset** [comment]
https://github.com/pyinstaller/pyinstaller/issues/8442
This will help(I am #671 's author)
