### ISSUE TITLE
FirstPersonController sees through entities because of shaders

### ISSUE THREAD

**Issue by valmme** [pokepetter/ursina#679]
I make the game and to create a player, I use the FirstPersonController class. I also use the shader `pixelation_shader`. But with shaders there is a problem. I made a room in the game out of rectangular entities, but if I use any shader, the player can see through these walls when he get too close. When I remove the import of this shader, the bug is corrected
![изображение](https://github.com/pokepetter/ursina/assets/111056676/bd65cef6-d4a0-4970-80ce-61abc07a2c9e)

**Comment by pokepetter** [comment]
This is due to the near clip plane. Assigning a shader to the camera will set this to 1, since shaders using the depth texture will break otherwise. You can change the near clip plane this by setting `camera.clip_plane_near`

**Comment by valmme** [comment]
@pokepetter Thanks
