### ISSUE TITLE
Operation of color.rgb()

### ISSUE THREAD

**Issue by tahoemike** [pokepetter/ursina#684]
Using the latest distribution on github, the following code in update()

ball.color=color.rgb(randint(0,255),randint(0,255),randint(0,255))

always produces a white ball, whereas using color.rgb32(randint(0,255),randint(0,255),randint(0,255)) 
or color.random_color() both work as expected.  Tested on Windows 10 desktop with nvidia display and Windows 11 Lenovo laptop.

**Comment by tahoemike** [comment]
I see that color.rgb expects a fractional value.  What I don't understand is that example code (for example Ursina Engine tutorials) show the usage I described and generates colors.

**Comment by pokepetter** [comment]
The `rgb` function was changed recently to only expect 0.0-1.0. There's `rgba32` for 0-255. Where is this "Ursina Engine tutorials" you're talking about?
