### ISSUE TITLE
How to detect the top and bottom of an entity

### ISSUE THREAD

**Issue by DPthang411** [pokepetter/ursina#697]
I wanna make a platformer but don't wanna use the built in 2d controller, so I can use that knowledge to create top down maze game controller. But unlike pygame ursina doesn't have left,top left,... So is there a way to detect if the top of player collided with the bottom of platform so they bounce off or the legs of player collided with the top of the ground so they can stand on?

**Comment by imbomania** [comment]
You can create child Entities with parents bounds without a model, but with a collider and name it "top" or "bottom", and just check thru hit_info what you touched. 
Also there is a python tags system, but for that you need to dig into panda3d manuals.

**Comment by DPthang411** [comment]
I don't kinda understand ur idea. But I have used raycast. At the first, it worked pretty well but when I let 3 rays in each direction with one in the middle and 2 in the corners, the player teleported from 1 to another direction.

**Comment by imbomania** [comment]
Just a simple example:
```
from ursina import *

app = Ursina()
camera.position = (0, 5, -50)

player = Entity(name="player", model="cube", color=color.red, position=(0,1,0))
head_collider = Entity(name="head", collider="box", parent=player, scale=(1, .25, 1), position=(0, .75, 0))
legs_collider = Entity(name="legs", collider="box", parent=player, scale=(1, .25, 1), position=(0, -.75, 0))

ground = Entity(name="ground", model="cube", collider="box", scale=(100, 1, 100), texture="grass")
roof = Entity(name="roof", model="cube", collider="box", scale=(100, 1, 100), texture="brick", position=(0,10,0))


def update():
    head_hit = head_collider.intersects() #checks for collisions from head
    legs_hit = legs_collider.intersects() #checks for collisions from legs

    if held_keys["up arrow"]:
        if not head_hit:
            player.y += player.y * time.dt * 4
        else:
            print(f"hit >{head_hit.entity.name}<")
    if held_keys["down arrow"]:
        if not legs_hit:
            player.y -= player.y * time.dt * 4
        else:
            print(f"stand on >{legs_hit.entity.name}<")

app.run()
```

**Comment by DPthang411** [comment]
oh yes, what i need is the part to stop the entity from moving through others. Plss help me if u can!

**Comment by imbomania** [comment]
Well, i'll explain my example, and then you understand all.
Look, we have a bunch of Entities creation at start. All of them have it's own collider(look at [API refrence](https://www.ursinaengine.org/api_reference.html#Collider) ). Just remember, you can create just empty entity and place in it collider with size and shape you need(scale=(x, y, z))(if you need an ivisible wall, for example) and then name it: "player", "wall", "roof", e.t.c.
Then, in update method you need to `hit = player.intersects()`, this will write an entity which collides with yours entity and then you just check by name what collides with yours entity:
```
if hit(is not None):
    player.(x or what direction you need) += time.dt * speed(in example 4) #there we moving
else:
    (if hit is exist)if hit.entity.name == "wall":

#and there you can do what you need if yours entity collides with wall. For example, you can give it a reverse impulse:
        player.(x or what direction you need) -= time.dt * speed(in example 4)
```

You can complicate it by check more than one name in hit(if yours entity collides more than one collider):

```
if hit:
    hit_names = [hit.entity.name for hit.entity in hit.entities]
if "wall" in hit_names and "spikes" in hit_names:
    destroy(player)
```
As you already understand, "spikes" is a another collider, that can be placed near "wall" collider, and if you touch both of them, player destroys.

**Comment by DPthang411** [comment]
Ye I understood it. But do u know how to stop Entity from moving through other entities?

**Comment by imbomania** [comment]
Look at colliders scale, if collider scale less than entity's bounds(if model is defined), than visible part of entity will pass through other entites. As i said, you need to match scales. You can `entity.collider.visible = True` and `entity.visible = False` if you need to see the size of collider.
