### ISSUE TITLE
issue with 2d platformer example

### ISSUE THREAD

**Issue by alexlep** [pokepetter/ursina#7]
Hey,
on launching platformer example and clicking any button I'm getting:
https://hastebin.com/setuyabeda.makefile

Ubuntu 18.04, python 3.7.5.
pip freeze under link above.

**Comment by pokepetter** [comment]
That error shouldn't affect anything. Are there any issues otherwise?
I've pushed a fix for the underlying cause of the error message.

**Comment by alexlep** [comment]
Oh, sorry, this error was appearing once key is pressed instead of some movement of green block, etc.
If nothing should happen once I'm pressing cursor keys (or wasd) - I believe it's ok. Please correct me if I'm wrong.

**Comment by pokepetter** [comment]
You should be able to move right and left when pressing d or a, and jump with space. Is that not the case?

**Comment by alexlep** [comment]
I'm sorry for misleading. You are right, a/d/space presses work for me.
Thanks a lot for your work, exploring your engine now.

**Comment by alexlep** [comment]
small clarification - a/d won't work for me until I'll hit space.
Once space was pressed - other keys start to work for me also.

**Comment by alexlep** [comment]
Also this bug with "falling under the ground" once I hit space - is it ok?
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/VNDCJtQs/2dplatormfer.gif' border='0' alt='2dplatormfer'/></a>

**Comment by pokepetter** [comment]
This happens because the example controller is incomplete and thankfully not because of something with the engine. I just haven't got to handling roof and wall collisions properly, though I hope to get to that eventually.

**Comment by arydevy** [comment]
When i press space the player doaent jump

**Comment by pokepetter** [comment]
It's really been improved now and you can't jump through ceilings anymore, so I'm closing this.
