### ISSUE TITLE
Exception: Error in Mesh. Ensure Mesh is valid and the inputs have same length

### ISSUE THREAD

**Issue by ShivamKR12** [pokepetter/ursina#713]
PS C:\Users\Shivam\Desktop\voxel 3d\Rally-master> py main.py

Hello from the Rally Server!

warning: Tried to instantiate Entity before Ursina. Please create an instance of Ursina first (app = Ursina()) Traceback(filename='C:\\Users\\Shivam\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ursina\\audio.py', lineno=17, function='__init__', code_context=['        super().__init__(**kwargs)\n'], index=0, positions=Positions(lineno=17, end_lineno=17, col_offset=8, end_col_offset=34)) 
no audio found with name: /ringtones/clicking.ogg supported formats: .ogg, .wav
warning: missing audio clip: /ringtones/clicking.ogg 
warning: Tried to instantiate Entity before Ursina. Please create an instance of Ursina first (app = Ursina()) Traceback(filename='C:\\Users\\Shivam\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ursina\\audio.py', lineno=17, function='__init__', code_context=['        super().__init__(**kwargs)\n'], index=0, positions=Positions(lineno=17, end_lineno=17, col_offset=8, end_col_offset=34))
no audio found with name: /ringtones/subtle.ogg supported formats: .ogg, .wav
warning: missing audio clip: /ringtones/subtle.ogg
warning: Tried to instantiate Entity before Ursina. Please create an instance of Ursina first (app = Ursina()) Traceback(filename='C:\\Users\\Shivam\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ursina\\audio.py', lineno=17, function='__init__', code_context=['        super().__init__(**kwargs)\n'], index=0, positions=Positions(lineno=17, end_lineno=17, col_offset=8, end_col_offset=34))
no audio found with name: /ringtones/uplifting.ogg supported formats: .ogg, .wav
warning: missing audio clip: /ringtones/uplifting.ogg
warning: Tried to instantiate Entity before Ursina. Please create an instance of Ursina first (app = Ursina()) Traceback(filename='C:\\Users\\Shivam\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ursina\\ursinastuff.py', lineno=230, function='__call__', code_context=['        obj = type.__call__(cls, *args, **kwargs)\n'], index=0, positions=Positions(lineno=230, end_lineno=230, col_offset=14, end_col_offset=49))
info: Using primary monitor: Monitor(x=0, y=0, width=1366, height=768, width_mm=344, height_mm=193, name='\\\\.\\DISPLAY1', is_primary=True)
:prc(warning): Invalid integer value for ConfigVariable win-size: 614.4000244140625
:prc(warning): Invalid integer value for ConfigVariable win-size: 1092.800048828125
Known pipe types:
  wglGraphicsPipe
(3 aux display modules not yet loaded.)
set window position: Vec2(137, 77)
:prc(warning): changing default value for ConfigVariable paste-emit-keystrokes from '1' to '0'.
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
package_folder: C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina
asset_folder: .
set fullscreen to True
Monitor(x=0, y=0, width=1366, height=768, width_mm=344, height_mm=193, name='\\\\.\\DISPLAY1', is_primary=True)
set window position: Vec2(0, 0)
---------------set size to: Vec2(1366, 768)
read obj at: assets\cars\sports-car.obj
read obj at: assets\cars\sports-car.obj
Traceback (most recent call last):
:thread(error): Exception occurred within PythonThread PythonThread-0
Traceback (most recent call last):
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh.py", line 90, in _set_array_data
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh.py", line 90, in _set_array_data
    vmem[:] = a
    vmem[:] = a
    ~~~~^^^
    ~~~~^^^
ValueError: memoryview assignment: lvalue and rvalue have different structures

ValueError: memoryview assignment: lvalue and rvalue have different structures

During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:


Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\Shivam\Desktop\voxel 3d\Rally-master\main.py", line 106, in <module>
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\direct\stdpy\thread.py", line 107, in threadFunc      
    car = Car()
          ^^^^^
    function(*args, **kwargs)
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\ursinastuff.py", line 230, in __call__
  File "C:\Users\Shivam\Desktop\voxel 3d\Rally-master\main.py", line 95, in load_assets
    obj = type.__call__(cls, *args, **kwargs)
    load_model(m)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh_importer.py", line 79, in load_model      
  File "C:\Users\Shivam\Desktop\voxel 3d\Rally-master\car.py", line 11, in __init__
    m = obj_to_ursinamesh(path=path, name=name, return_mesh=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    super().__init__(
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh_importer.py", line 375, in obj_to_ursinamesh
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\entity.py", line 107, in __init__
    setattr(self, key, kwargs[key])
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\entity.py", line 198, in model_setter
    return Mesh(
           ^^^^^
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh.py", line 69, in __init__
    m = load_model(value, application.asset_folder)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self.generate()
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh_importer.py", line 79, in load_model      
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh.py", line 180, in generate
    m = obj_to_ursinamesh(path=path, name=name, return_mesh=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self._set_array_data(vdata.modify_array(color_attribute_index), self._ravel(self.colors), 'f')
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh_importer.py", line 375, in obj_to_ursinamesh
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh.py", line 92, in _set_array_data
    return Mesh(
    raise Exception(f'Error in Mesh. Ensure Mesh is valid and the inputs have same length: vertices:{len(self.vertices)}, triangles:{len(self.triangles)}, normals:{len(self.normals)}, colors:{len(self.colors)}, uvs:{len(self.uvs)}')
           ^^^^^
Exception: Error in Mesh. Ensure Mesh is valid and the inputs have same length: vertices:8724, triangles:0, normals:8724, colors:8548, uvs:8724
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh.py", line 69, in __init__
    self.generate()
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh.py", line 180, in generate
    self._set_array_data(vdata.modify_array(color_attribute_index), self._ravel(self.colors), 'f')
  File "C:\Users\Shivam\AppData\Local\Programs\Python\Python312\Lib\site-packages\ursina\mesh.py", line 92, in _set_array_data
    raise Exception(f'Error in Mesh. Ensure Mesh is valid and the inputs have same length: vertices:{len(self.vertices)}, triangles:{len(self.triangles)}, normals:{len(self.normals)}, colors:{len(self.colors)}, uvs:{len(self.uvs)}')
Exception: Error in Mesh. Ensure Mesh is valid and the inputs have same length: vertices:8724, triangles:0, normals:8724, colors:8548, uvs:8724
PS C:\Users\Shivam\Desktop\voxel 3d\Rally-master>

**Comment by ShivamKR12** [comment]
EXPLATION BY CHATGPT:

warning: Tried to instantiate Entity before Ursina. Please create an instance of Ursina first (app = Ursina()):

This indicates that you're trying to create an Entity object before initializing the Ursina application instance. Ursina requires that you first create an instance of Ursina using app = Ursina() before creating other entities. Ensure that your code follows this order.
no audio found with name: ...:

This warning suggests that the audio files referenced in your project are not found at the specified paths. Ensure that the audio files (clicking.ogg, subtle.ogg, uplifting.ogg) are correctly placed in the ringtones folder and that the paths in your code are correct.
Exception: Error in Mesh. Ensure Mesh is valid and the inputs have same length:

This is a critical error indicating that there’s an issue with the mesh data being loaded. Specifically, the error message details a mismatch between the number of vertices, triangles, normals, colors, and UVs:

Vertices: 8724
Triangles: 0
Normals: 8724
Colors: 8548
UVs: 8724
This means that the mesh data being loaded has inconsistent lengths for these attributes. For a mesh to be valid, all attributes (vertices, triangles, normals, colors, UVs) must have compatible lengths. If they don’t, the mesh cannot be properly constructed.

**Comment by ShivamKR12** [comment]
@pokepetter please help man

**Comment by pokepetter** [comment]
How can I reproduce it?

**Comment by ShivamKR12** [comment]
copy this repo:
https://github.com/mandaw2014/Rally

**Comment by ShivamKR12** [comment]
![Screenshot 2024-08-21 145850](https://github.com/user-attachments/assets/00d2c7d4-42fd-4647-9cf4-a262c7e83966)
here's the version that i used

**Comment by ShivamKR12** [comment]
![Screenshot 2024-08-21 150051](https://github.com/user-attachments/assets/4e5673f0-7ab8-4484-a6b1-761389ebc7b1)
![Screenshot 2024-08-21 150114](https://github.com/user-attachments/assets/f2115f1e-269d-4caa-b15d-607040029a8b)
![Screenshot 2024-08-21 150129](https://github.com/user-attachments/assets/729e48a9-d54a-4d70-a151-5b3b1ff0e9f5)
here's the console message.

**Comment by ShivamKR12** [comment]
also, is this not a ursina function "render.setShaderAuto()" ?

**Comment by ShivamKR12** [comment]
@pokepetter but it works for ursina 5.2.0
![Screenshot 2024-08-21 151920](https://github.com/user-attachments/assets/6eaad50b-c91f-4987-a488-2b2b18cfb0ad)
![Screenshot 2024-08-21 151935](https://github.com/user-attachments/assets/21f795da-73ee-4c5e-902b-57b7d9c4169a)

**Comment by ShivamKR12** [comment]
i have no idea about the version in between.

**Comment by pokepetter** [comment]
The issue is that sports-car.obj has fewer vertex colors than vertices. So the obj is kind of invalid in that sense.

**Comment by pokepetter** [comment]
Looking at the .objs, none of them seems to have been triangulated, which they must be. This is probably the root of the issue.

**Comment by ShivamKR12** [comment]
@pokepetter if it is the cause , then should we do?

**Comment by pokepetter** [comment]
If you delete the.mtl files, the models will successfully load. They don't seem to be used, but I'm not sure, there could be a small tint to some materials.
However, there are other issues with the code, like incorrect variables to Audio and incorrect origin value for text. `origin = 0` should be `origin = (0,0)`.

If you could somehow figure out which specific version Rally was made with, and install that, that would work too.

**Comment by ShivamKR12** [comment]
(sorry for the late reply) so ya, it was made using ursina==4.1.1, ursinanetworking==2.1.4

**Comment by ShivamKR12** [comment]
but it works best with ursina==5.2.0, aftre a few updates were made by its creator
