### ISSUE TITLE
load obj model failed

### ISSUE THREAD

**Issue by kane-cloud** [pokepetter/ursina#716]
ursina 7.0.0 failed to load obj model and have below errors, I degraded the version to 3.5.0 works fine. weird！！！

********************************CODE************************************************
from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController
from numpy import floor
from perlin_noise import PerlinNoise

app = Ursina()

window.color = color.rgba32(94, 190 , 243, 100)
window.fullscreen=True
terrain=Entity(model=None,collider=None, texture='gold.png')
noise=PerlinNoise(octaves=4,seed=2025)
freq=48
terrain_width=100
for i in range(terrain_width*terrain_width):
    gold_cube=Entity(model='cube',texture='gold.png')
    gold_cube.x=floor(i/terrain_width)
    gold_cube.z=floor(i%terrain_width)
    gold_cube.y = floor((noise([gold_cube.x/freq,gold_cube.z/freq])) *9)# 第4步
    gold_cube.parent=terrain

terrain.combine()
terrain.collider='mesh'

chickenModel=load_model('steve.obj')
xiao_ji=Entity(model=chickenModel,scale=1,x=22,z=16,y=7.1,texture='chicken.png',double_sided=True)

s =FirstPersonController()
s.cursor.visible=False
s.gravity=0.1

s.x=s.z=1
s.y=1
def update():
    pass
app.run()

***********************************CODE*********************************************
********************************ERROR************************************************
info: Using primary monitor: Monitor(x=0, y=0, width=1728, height=1117, width_mm=None, height_mm=None, name=None, is_primary=True)
:prc(warning): Invalid integer value for ConfigVariable win-size: 1382.4000244140625
:prc(warning): Invalid integer value for ConfigVariable win-size: 893.5999755859375
Known pipe types:
  CocoaGraphicsPipe
(3 aux display modules not yet loaded.)
set window position: Vec2(173, 112)
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
package_folder: /Users/kane.lc/Documents/Daren/python/venv/lib/python3.11/site-packages/ursina
asset_folder: /Users/kane.lc/Documents/Daren/python/20240804/我的世界
set fullscreen to True
Monitor(x=0, y=0, width=1728, height=1117, width_mm=None, height_mm=None, name=None, is_primary=True)
set window position: Vec2(0, 0)
---------------set size to: Vec2(1728, 1117)
read obj at: /Users/kane.lc/Documents/Daren/python/20240804/我的世界/assets/steve/steve.obj
Traceback (most recent call last):
  File "/Users/kane.lc/Documents/Daren/python/venv/lib/python3.11/site-packages/ursina/mesh.py", line 90, in _set_array_data
    vmem[:] = a
    ~~~~^^^
ValueError: memoryview assignment: lvalue and rvalue have different structures

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kane.lc/Documents/Daren/python/20240804/我的世界/my_world.py", line 25, in <module>
    chickenModel=load_model('steve.obj')
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kane.lc/Documents/Daren/python/venv/lib/python3.11/site-packages/ursina/mesh_importer.py", line 79, in load_model
    m = obj_to_ursinamesh(path=path, name=name, return_mesh=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kane.lc/Documents/Daren/python/venv/lib/python3.11/site-packages/ursina/mesh_importer.py", line 375, in obj_to_ursinamesh
    return Mesh(
           ^^^^^
  File "/Users/kane.lc/Documents/Daren/python/venv/lib/python3.11/site-packages/ursina/mesh.py", line 69, in __init__
    self.generate()
  File "/Users/kane.lc/Documents/Daren/python/venv/lib/python3.11/site-packages/ursina/mesh.py", line 183, in generate
    self._set_array_data(vdata.modify_array(uv_attribute_index), self._ravel(self.uvs), 'f')
  File "/Users/kane.lc/Documents/Daren/python/venv/lib/python3.11/site-packages/ursina/mesh.py", line 92, in _set_array_data
    raise Exception(f'Error in Mesh. Ensure Mesh is valid and the inputs have same length: vertices:{len(self.vertices)}, triangles:{len(self.triangles)}, normals:{len(self.normals)}, colors:{len(self.colors)}, uvs:{len(self.uvs)}')
Exception: Error in Mesh. Ensure Mesh is valid and the inputs have same length: vertices:216, triangles:0, normals:216, colors:0, uvs:216

Process finished with exit code 1

********************************ERROR************************************************

**Comment by pokepetter** [comment]
Can you share the model?

**Comment by CardboardDog** [comment]
This model has 216 vertices and 0 triangles, so I am going to assume it's not triangulated. Try importing it into Blender or a similar program, then export it as .obj with triangulate checked.
