### ISSUE TITLE
Failed to apply a texture on a Pipe()

### ISSUE THREAD

**Issue by Dinorigami-SLHIDE** [pokepetter/ursina#718]
Hello,
I try to apply a texture to an Entity with a Pipe as a model.
If I take the pipe.py script and choose to add a `texture="my_image"` to the Entity called "e" on its declaration in the example script, I get a pipe with the average colour of my image. That is, cyan.
![image](https://github.com/user-attachments/assets/a66a1e12-e696-4c84-b0fa-d5c1bb3ba6a0)
How to apply it properly? I need it so I can add custom textures on the TrailRenderer() class.
Any help would be appreciated!

**Comment by pokepetter** [comment]
Pipe has uvs now.
