### ISSUE TITLE
Little Blue Square

### ISSUE THREAD

**Issue by lucaheyworth** [pokepetter/ursina#720]
This my player file:
![Grapply](https://github.com/user-attachments/assets/2af99042-37f5-4b0d-885f-0c6626b4380a)
but in game it appears like this:
![Screenshot 2024-09-19 162819](https://github.com/user-attachments/assets/4398d35e-86d7-4a4c-9051-c0ae5af27446)
This is the code used to render the the player:
`
player = PlatformerController2d()
player.x = 1
player.y = raycast(player.world_position, player.down).world_point[1] + .01
player.texture = load_texture('Grapply.png')
`

I am trying to remove that little blue square.

**Comment by pokepetter** [comment]
Doesn't happen when I load it.

**Comment by SpinNeutron** [comment]
I know this is marked complete but the blue cube persists.


It must come from [platformer_controller_2d.py](https://github.com/pokepetter/ursina/blob/aa57ada950752ba62b65ad5a40717f566b2b3c6e/ursina/prefabs/platformer_controller_2d.py#L53)

![ursina](https://github.com/user-attachments/assets/6f999071-c1ef-4ba1-80b6-e8d909a7fb8a)
