### ISSUE TITLE
When there are too many files in my project folder, the startup will be slow

### ISSUE THREAD

**Issue by mibino** [pokepetter/ursina#729]
When there are too many files in my project folder, the startup will be slow
当我的项目文件夹文件过多时，启动会很慢

**Comment by pokepetter** [comment]
You can try finding a way to reduce the number of files, or you can specify the path further. For example `model='textures/character/something` instead of `model='something'`. Keep in mind that the folder the script is considered the project folder by ursina and assumes all those files are part of the program/game, so putting the script in a folder with unrelated files is not a good idea.

**Comment by mibino** [comment]
So...in that case...i cannot make the Minecraft Launcher for ursina...



---- Replied Message ----
| From | Petter ***@***.***> |
| Date | 10/28/2024 23:29 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [pokepetter/ursina] When there are too many files in my project folder, the startup will be slow (Issue #729) |

You can try finding a way to reduce the number of files, or you can specify the path further. For example model='textures/character/something instead of model='something'. Keep in mind that the folder the script is considered the project folder by ursina and assumes all those files are part of the program/game, so putting the script in a folder with unrelated files is not a good idea.

**Comment by mibino** [comment]
So...in that case...i cannot make the Minecraft Launcher of ursina...



---- Replied Message ----
| From | Petter ***@***.***> |
| Date | 10/28/2024 23:29 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [pokepetter/ursina] When there are too many files in my project folder, the startup will be slow (Issue #729) |

You can try finding a way to reduce the number of files, or you can specify the path further. For example model='textures/character/something instead of model='something'. Keep in mind that the folder the script is considered the project folder by ursina and assumes all those files are part of the program/game, so putting the script in a folder with unrelated files is not a good idea.
