### ISSUE TITLE
Panda3d 1.10.6.post2 doesn't have windows wheels

### ISSUE THREAD

**Issue by jtiai** [pokepetter/ursina#73]
Latest version of Ursina has panda3d 1.10.6.post2 as a dependency. That version doesn't have Windows wheels and thus Ursin installation fails.

According to documentation Ursina should work on Windows.

**Comment by jtiai** [comment]
Seems that this is issue when trying to install Ursina with pipenv which seems to detect unpinned version of panda3d so that it picks latest version. Pip somehow seems to pick latest installable version (which is 1.10.6)

**Comment by DiamondsBattle** [comment]
Working fine on Windows for me.

**Comment by jtiai** [comment]
Pipenv tool doesn't work. It has crossplatform locking and it doesn't know how to pick platform spesific version.

Pip works due it's package resolution picking latest version it can for particular platform. 

In this case pip picks 1.10.6 pipenv picks 1.10.6.post2.

**Comment by DiamondsBattle** [comment]
So why do you use ``pipenv`` ?

**Comment by DiamondsBattle** [comment]
``pip`` works so why not using it 🤔 ?

**Comment by jtiai** [comment]
Because pipenv is a bit more convenient for vscode and pycharm since both tools recon Pipfile OOTB and can configure used (virtual environment) python automatically.

It probably would be good to add note that Windows users who want to use pipenv to pin down correct version of panda3d.

Poetry (another virtualenv + package management tool) does exactly same as pipenv while resolving panda3d.

**Comment by jtiai** [comment]
Looks like latest pipenv works correctly.
