### ISSUE TITLE
wayland keypress issue

### ISSUE THREAD

**Issue by zacekjakub** [pokepetter/ursina#734]
Hello, is it only me for who the keypress doesnt work as intended for? Even with those bare examples I run, if I press a D to move right, it goes right until I press A to reverse it. The same for W and S. And after this, you can't use that side again.

Here is some debug info I collected.

```
Key event: d
Movement flags - Forward: False, Backward: False, Left: True, Right: True
Key event: d
Movement flags - Forward: False, Backward: False, Left: True, Right: True
Key event: d
Movement flags - Forward: False, Backward: False, Left: True, Right: True
Key event: d
Movement flags - Forward: False, Backward: False, Left: True, Right: True
Key event: left mouse down
Movement flags - Forward: False, Backward: False, Left: True, Right: True
```

Is this a known issue on Wayland?

**Comment by a2cy** [comment]
Seems like an issue with your code 
I'm on wayland too and everything is working fine

**Comment by pokepetter** [comment]
Can't reproduce.
