### ISSUE TITLE
connecting through Websockets 

### ISSUE THREAD

**Issue by blenderlab** [pokepetter/ursina#78]
Hello, 
I'd like to use my Ursina project with Websockets, but it seems impossible to implement WS: 

-  Threading crash the Engine
- Threading the Websocket connection don't work at all.

Is it possible to implement a Websocket thread inside the Engine ? 
Thomas

**Comment by pokepetter** [comment]
I don't know anything about Websockets, but for safe threading you can use panda3d Thread module, which you just use instead of Python's:
`from panda3d.core import Thread`

**Comment by blenderlab** [comment]
Ho yeah ! of course, I forgot that there is Panda3D behind Ursina. Let's go back coding !
