### ISSUE TITLE
Ursina doesn't work wth Pycharm

### ISSUE THREAD

**Issue by UntriexTv** [pokepetter/ursina#82]
Hello, I have a strange problem with Ursina and Pycharm.
I can run example code in IDLE, but if i run code in Pycharm (interpreter is setted same as idle) i get this errorTraceback (most recent call last):
  File "C:/Users/editedusername/PycharmProjects/3d/ursina.py", line 1, in <module>
    from ursina import *
  File "C:\Users\forsecurityreasons\PycharmProjects\3d\ursina.py", line 3, in <module>
    app = Ursina()
NameError: name 'Ursina' is not defined
Same interpreter with IDLE and it runs just fine
I am using Python 3,8 32bit and newest pycharm community 2020.3

**Comment by pokepetter** [comment]
I just tried it and it worked fine. Are you sure you're not using a virtual environment or something?
Also, you probably shouldn't call the script ursina.py

**Comment by UntriexTv** [comment]
... Yeah it was the name. Really stupid mistake... sorry. When it worked with IDLE (i created another file "test.py") i figured out that it was incompatibility with Pycharm.... somethink simple as script name, it didn't occur to me.
Thank you so much
