### ISSUE TITLE
importlib.metadata  worked  on python version 3.8 and above , not below 

### ISSUE THREAD

**Issue by beardad1975** [pokepetter/ursina#84]
Try to  upgrade  to newest ursina.
But python 3.7.8 has the error message.
No module named 'importlib.metadata' 

I thought the problem is at 
https://github.com/pokepetter/ursina/blob/bdc49933dba2986d85bb7e6536097feeee5aeb23/ursina/application.py#L3

After using python version 3.8 , then there is no problem.

**Comment by pokepetter** [comment]
Fixed
