### ISSUE TITLE
Remove framerate limitation ?

### ISSUE THREAD

**Issue by apirrone** [pokepetter/ursina#86]
Hello,

I can't find how to remove the limitation on the frame rate, right now it seems to be capped at 60 fps, and I have a 144hz monitor so I would like to enjoy that :) 

Thanks !

**Comment by pokepetter** [comment]
You can set `window.vsync = False`, before Ursina()
It should set the limit your monitor's framerate, I don't know why it doesn't.

**Comment by apirrone** [comment]
Yes sorry I actually found the where the problem comes from but forgot to remove the Issue. It seems to come from my Ubtuntu installation, the framerate is limited to 60fps system wide. On my other computer it works just fine.
