### ISSUE TITLE
Question on how to use albedo specular normal texture trio

### ISSUE THREAD

**Issue by Oderjunkie** [pokepetter/ursina#88]
I've modeled an AK-47 for a game, and it has a .obj file, an albedo texture, a specular texture, and a normal texture.

The files are named:
ak47.obj
AK47.png (Albedo)
AK47Shine.png (Specular)
AK47Normal.png (Normal)

I'm currently using `Entity(model='ak47', texture='AK47')`. but I need something like `Entity(model='ak47', texture='AK47', specular='AK47Shine', normal='AK47Normal')`.
I dug around in the `Entity()` documentation and didn't find anything for this.

I wasn't sure where to post questions, apologies if this is the wrong place.

**Comment by pokepetter** [comment]
That's not supported. You'd have to write a shader.
