### ISSUE TITLE
Help on importing 3D objects

### ISSUE THREAD

**Issue by steger123** [pokepetter/ursina#89]
I'm trying to find any example code, how to import 3D objects in the Ursina engine, but without any success.
(.egg, .obj, .fbx, etc. for example exported from Blender) 

In Panda3D it looks like this:
self.tree = self.loader.loadModel('my-models/christmas_tree')
self.tree = setPos(1,1,1)
self.tree = reparentTo(self.render)

- How can I do the same in Ursina ?
- Which format I have to use ? .obj ?

Thank You for Your quick answer in advance.

**Comment by pokepetter** [comment]
`self.tree = Entity('christmas_tree', position=(1,1,1))`

https://www.ursinaengine.org/entity_basics.html#Setting%20a%20model

**Comment by steger123** [comment]
Thank You for the answer. I have the following code:

from ursina import *
app = Ursina()
lett = Entity('my-models/10187_LettuceBibb_v1-L2.obj', position=(1, 1, 1)) 
s = Sky()
#ground = Entity(model='plane', color=color.gray, scale=100)
ec=EditorCamera(zoom_speed = 0.1, move_speed = 5 )
app.run()

The program running and the blue skybox appearing. I can rotate the camera, but I don't find the object.
I attached the OBJ file. Opening in Blender 2.79 without any issue.
[lettuce.zip](https://github.com/pokepetter/ursina/files/5651519/lettuce.zip)

**Comment by pokepetter** [comment]
It's model='my-models/10187_LettuceBibb_v1-L2.obj'
Forgot that in my answer, but the documentations is correct.

**Comment by steger123** [comment]
Based on my example, kindly provide a short sample script. Thank You very much for Your help in advance !
