### ISSUE TITLE
Run a single update of ursina 

### ISSUE THREAD

**Issue by Shirnia** [pokepetter/ursina#94]
I wish to train an AI on a game using Ursina and Gym. 
To do this some key information must be accessed by the AI. Generally gym environment (game) has [3 key functions](https://towardsdatascience.com/creating-a-custom-openai-gym-environment-for-stock-trading-be532be3910e): 
Step: Execute one time step within the environment
Reset: Reset the state of the environment to an initial state
Render: Render the environment to the screen
Obviously render and reset are easy in this case, however I am not sure how to run an application one step at a time, based off all the samples, the "easiest" way to create and run an application is app.run(). 
Is there a way to have something like app.step()?

**Comment by pokepetter** [comment]
You can now use `app.step()` to update once, instead of `app.run()` which will run continuously.
