### ISSUE TITLE
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ursina/mesh_importer.py", line 155, in get_blender     return application.blender_paths['default'] KeyError: 'default'

### ISSUE THREAD

**Issue by MorwinX** [pokepetter/ursina#96]
Hey, so I am making a version of 3d chess using your engine (Ursina Engine). I was coding and when I ran the code I got this error. Here is the full error: Traceback (most recent call last):
  File "/Users/harshitsharda/Desktop/3d Chess/3dChess.py", line 109, in <module>
    King = King()
  File "/Users/harshitsharda/Desktop/3d Chess/3dChess.py", line 37, in __init__
    origin_y = 0.5)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ursina/entity.py", line 102, in __init__
    setattr(self, key, value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ursina/entity.py", line 178, in __setattr__
    m = load_model(value, application.asset_folder)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ursina/mesh_importer.py", line 56, in load_model
    if compress_models(path=path, name=name):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ursina/mesh_importer.py", line 167, in compress_models
    blender = get_blender(blend_file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ursina/mesh_importer.py", line 155, in get_blender
    return application.blender_paths['default']
KeyError: 'default'

The error is really confusing. Look's like the blender files aren't loading. The code is below. I couldn't link the blender files in GitHub so sorry for that.

Code:
from ursina import *
from ursina.prefabs.first_person_controller import FirstPersonController

app = Ursina()

block_pick = 1
window.fps_counter.enabled = False
window.exit_button.visible = False

def update():
	global block_pick

	if held_keys['1']: block_pick = 1
	if held_keys['2']: block_pick = 2
	if held_keys['3']: block_pick = 3
	if held_keys['4']: block_pick = 4
	if held_keys['5']: block_pick = 5
	if held_keys['6']: block_pick = 6

class Voxel(Button):
	def __init__(self, position = (0,0,0), ):
		super().__init__(
			parent = scene,
			position = position,
			model = 'cube',
			origin_y = 0.5,
			texture = texture,
			color = color.color(0,0,random.uniform(0.9,1)),
			scale = 0.5)

class King(Entity):
	def __init__(self, position = (0,0,0)):
		super().__init__(
			parent = scene,
			model = 'Assets/King',
			origin_y = 0.5)

	def input(self,key):
		if self.hovered:
			if key == 'left mouse down':
				if block_pick == 1: king = King(position = self.position + mouse.normal)

class Knight(Entity):
	def __init__(self, position = (0,0,0)):
		super().__init__(
			parent = scene,
			model = 'Assets/Knight',
			origin_y = 0.5)

	def input(self,key):
		if self.hovered:
			if key == 'left mouse down':
				if block_pick == 2: Knight = Knight(position = self.position + mouse.normal)

class Bishop(Entity):
	def __init__(self, position = (0,0,0)):
		super().__init__(
			parent = scene,
			model = 'Assets/Bishop',
			origin_y = 0.5)

	def input(self,key):
		if self.hovered:
			if key == 'left mouse down':
				if block_pick == 3: Bishop = Bishop(position = self.position + mouse.normal)

class Queen(Entity):
	def __init__(self, position = (0,0,0)):
		super().__init__(
			parent = scene,
			model = 'Assets/Queen',
			origin_y = 0.5)

	def input(self,key):
		if self.hovered:
			if key == 'left mouse down':
				if block_pick == 2: Queen = Queen(position = self.position + mouse.normal)

class Rook(Entity):
	def __init__(self, position = (0,0,0)):
		super().__init__(
			parent = scene,
			model = 'Assets/Rook',
			origin_y = 0.5)

	def input(self,key):
		if self.hovered:
			if key == 'left mouse down':
				if block_pick == 2: Rook = Rook(position = self.position + mouse.normal)

class Pawn(Entity):
	def __init__(self, position = (0,0,0)):
		super().__init__(
			parent = scene,
			model = 'Assets/Pawn',
			origin_y = 0.5)

	def input(self,key):
		if self.hovered:
			if key == 'left mouse down':
				if block_pick == 2: Pawn = Pawn(position = self.position + mouse.normal)

for z in range(20):
	for x in range(20):
		voxel = Voxel(position = (x,0,z))

King = King()
Queen = Queen()
Knight = Knight()
Bishop = Bishop()
Rook = Rook()
Pawn = Pawn()
player = FirstPersonController()
app.run()

**Comment by pokepetter** [comment]
What type of file are you trying to load?
Do you have Blender installed?

**Comment by ChrisSpinu** [comment]
Well, I have the same error, but I am trying to import a blender scene. So I can't say anything about this.

**Comment by pokepetter** [comment]
Have you tried the newest version? I did a change to this recently for a different issue. Most likely it doesn't find Blender because it's not at the default location most likely. In any case, you can provide the path manually to application.blender_paths['default] = some_path for now.

**Comment by ChrisSpinu** [comment]
I will try.
