### ISSUE TITLE
How to check if two objects touch each other or not?

### ISSUE THREAD

**Issue by HLD202** [pokepetter/ursina#97]
I tried to check if two objects touch each other or not with following code:
for example:
`
        if self.y >= ceiling.y - .2 or self.y <= floor.y + .2:
            self.y -= self.y_speed
            self.y_speed *= -1

        if left_paddle.y + 1 > self.y > left_paddle.y - 1:
            if abs(left_paddle.x) - abs(self.x) <= .5:
                self.x -= self.x_speed
                self.x_speed *= -1

        if right_paddle.y + 1 > self.y > right_paddle.y - 1:
            if right_paddle.x - self.x <= .5:
                self.x -= self.x_speed
                self.x_speed *= -1
`
is there a function or a easier way to do this?

**Comment by pokepetter** [comment]
You can add box colliders with `collider='box'` and use entity.intersects() to check if it intersects other colliders.
Example:
```python
hit_info = ball.intersects()
if hit_info.hit:    # hit wall, so change direction
    ball.rotation_z *= -abs(hit_info.world_normal.normalized()[1])
```
