### ISSUE TITLE
Collision.

### ISSUE THREAD

**Issue by kkhashayar** [pokepetter/ursina#98]
I find it very hard to understand the collision system in Ursina, can you please explain a little more?
just a basic example of two objects collide in 2D mode.
Thank you.

**Comment by dreamsoftunitedkingdom** [comment]
yes, I would like more code examples on github that have the correct code for all basic game development things possible with ursina. 
In this way everybody can check the examples and less problems/questions will need to be posted in github.

Jessica

**Comment by pokepetter** [comment]
https://www.ursinaengine.org/collision.html
